++ ls caseresult/ -ltr
++ wc -l
+ filename=case68
+ mkdir caseresult/case68
+ ssh hadoop@master mkdir /home/hadoop/git/physical_design/caseresult/case68
+ RESULT_DIR=/home/hadoop/git/physical_design/caseresult/case68
+ TEN=10
+ SIXTY=60
+ SLEEP_TIME=300
+ YCSB_DIR=/home/hadoop/ycsb-0.1.4
+ number_of_operations=10000000
+ number_of_threads=20
+ number_of_records=10000000
+ output_file_suffix=.dat
+ experiment_list_file=/home/hadoop/git/physical_design/case68.list
+ clean=false
+ create=false
+ load=false
+ random_read=false
+ workloada=false
+ workloadb=false
+ workloadc=false
+ scan=false
+ all=false
+ for i in '$@'
+ '[' clean == all ']'
+ '[' clean == clean ']'
+ clean=true
+ for i in '$@'
+ '[' create == all ']'
+ '[' create == clean ']'
+ '[' create == create ']'
+ create=true
+ for i in '$@'
+ '[' load == all ']'
+ '[' load == clean ']'
+ '[' load == create ']'
+ '[' load == load ']'
+ load=true
+ let counter=1
+ cd /home/hadoop/ycsb-0.1.4
++ pwd
+ echo /home/hadoop/ycsb-0.1.4
/home/hadoop/ycsb-0.1.4
+ read line
+ false
+ true
+ echo 'sleeping for 60 ...'
sleeping for 60 ...
+ sleep 60
+ echo 'droping usertable...'
droping usertable...
+ ssh hadoop@master /home/hadoop/hbase/bin/hbase shell /home/hadoop/git/physical_design/delete_table
0 row(s) in 3.1770 seconds

0 row(s) in 0.7940 seconds

0 row(s) in 0.0630 seconds

+ echo 'sleeping for 300 ...'
sleeping for 300 ...
+ sleep 300
+ false
+ true
+ echo 'creating usertable...'
creating usertable...
+ create_statement='create '\''usertable'\'', { NAME=>'\''family'\'', CONFIGURATION => { '\''hbase.hregion.majorcompaction'\'' => '\''0'\'' } ,  COMPRESSION=>'\''GZ'\''}, SPLITS => ['\''user1'\'', '\''user2'\'', '\''user3'\'', '\''user4'\'', '\''user5'\'', '\''user6'\'', '\''user7'\'', '\''user8'\'', '\''user9'\'']'
+ echo create ''\''usertable'\'',' '{' 'NAME=>'\''family'\'',' CONFIGURATION '=>' '{' ''\''hbase.hregion.majorcompaction'\''' '=>' ''\''0'\''' '}' , 'COMPRESSION=>'\''GZ'\''},' SPLITS '=>' '['\''user1'\'',' ''\''user2'\'',' ''\''user3'\'',' ''\''user4'\'',' ''\''user5'\'',' ''\''user6'\'',' ''\''user7'\'',' ''\''user8'\'',' ''\''user9'\'']'
+ echo 'exit '
+ scp /home/hadoop/git/physical_design/caseresult/case68/create_1.script hadoop@master:/home/hadoop/git/physical_design/caseresult/case68/create_1.script
+ create_table /home/hadoop/git/physical_design/caseresult/case68/create_1.script
+ echo 'creating table...'
creating table...
+ echo /home/hadoop/git/physical_design/caseresult/case68/create_1.script
/home/hadoop/git/physical_design/caseresult/case68/create_1.script
+ ssh hadoop@master /home/hadoop/hbase/bin/hbase shell /home/hadoop/git/physical_design/caseresult/case68/create_1.script
0 row(s) in 1.7660 seconds

+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ false
+ true
+ echo 'loading data...'
loading data...
+ echo 'starting time: '
starting time: 
++ date +%s
+ echo 1405029563
1405029563
++ echo /home/hadoop/git/physical_design/caseresult/case68/load_1.dat
+ ./ld 10000000 20 /home/hadoop/git/physical_design/caseresult/case68/load_1.dat
Loading workload...
Starting test.
2014-07-10 14:59:23:470 0 sec: 0 operations; 
14/07/10 14:59:23 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/10 14:59:23 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm43.almaden.ibm.com
14/07/10 14:59:23 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/10 14:59:23 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/10 14:59:23 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/10 14:59:23 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf
14/07/10 14:59:23 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/10 14:59:23 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/10 14:59:23 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/10 14:59:23 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/10 14:59:23 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/10 14:59:23 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/10 14:59:23 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/10 14:59:23 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/10 14:59:23 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/10 14:59:23 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x62565cf8, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/10 14:59:23 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x62565cf8 connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/10 14:59:23 INFO zookeeper.ClientCnxn: Opening socket connection to server slave1/9.1.143.59:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/10 14:59:23 INFO zookeeper.ClientCnxn: Socket connection established to slave1/9.1.143.59:2181, initiating session
14/07/10 14:59:23 INFO zookeeper.ClientCnxn: Session establishment complete on server slave1/9.1.143.59:2181, sessionid = 0x14723f5df720011, negotiated timeout = 90000
2014-07-10 14:59:33:471 10 sec: 213636 operations; 21361.46 current ops/sec; [INSERT AverageLatency(us)=373.58] 
2014-07-10 14:59:43:472 20 sec: 213636 operations; 0 current ops/sec;  
2014-07-10 14:59:53:472 30 sec: 441700 operations; 22806.4 current ops/sec; [INSERT AverageLatency(us)=1579.31] 
2014-07-10 15:00:03:473 40 sec: 471122 operations; 2942.2 current ops/sec; [INSERT AverageLatency(us)=696.02] 
2014-07-10 15:00:13:473 50 sec: 471438 operations; 31.6 current ops/sec; [INSERT AverageLatency(us)=111150.42] 
2014-07-10 15:00:23:473 60 sec: 539685 operations; 6824.7 current ops/sec; [INSERT AverageLatency(us)=5073.44] 
2014-07-10 15:00:33:474 70 sec: 821377 operations; 28166.38 current ops/sec; [INSERT AverageLatency(us)=475.44] 
2014-07-10 15:00:43:474 80 sec: 821377 operations; 0 current ops/sec;  
14/07/10 15:00:49 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 3015 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56505 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 10067 ms, replay 3015 ops.
14/07/10 15:00:49 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2822 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56505 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 10008 ms, replay 2822 ops.
14/07/10 15:00:49 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2673 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56505 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 10095 ms, replay 2673 ops.
14/07/10 15:00:49 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2640 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56505 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:53 PDT 2014, retrying after 10082 ms, replay 2640 ops.
14/07/10 15:00:49 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2328 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56505 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:53 PDT 2014, retrying after 10029 ms, replay 2328 ops.
14/07/10 15:00:49 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2824 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56505 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 10049 ms, replay 2824 ops.
14/07/10 15:00:49 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 1533 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56505 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:54 PDT 2014, retrying after 10048 ms, replay 1533 ops.
14/07/10 15:00:49 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2766 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56505 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:54 PDT 2014, retrying after 10081 ms, replay 2766 ops.
14/07/10 15:00:49 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 3139 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56505 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 10068 ms, replay 3139 ops.
14/07/10 15:00:49 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2820 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56505 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 10002 ms, replay 2820 ops.
14/07/10 15:00:49 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2289 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56505 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:51 PDT 2014, retrying after 10064 ms, replay 2289 ops.
14/07/10 15:00:49 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 1923 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56505 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:54 PDT 2014, retrying after 10037 ms, replay 1923 ops.
14/07/10 15:00:49 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2233 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56505 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:54 PDT 2014, retrying after 10014 ms, replay 2233 ops.
14/07/10 15:00:49 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 2798 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56505 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 10021 ms, replay 2798 ops.
14/07/10 15:00:49 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2802 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56505 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 10044 ms, replay 2802 ops.
14/07/10 15:00:49 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 1891 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56505 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 10072 ms, replay 1891 ops.
14/07/10 15:00:49 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2670 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56505 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:50 PDT 2014, retrying after 10057 ms, replay 2670 ops.
14/07/10 15:00:49 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 1851 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56505 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:53 PDT 2014, retrying after 10047 ms, replay 1851 ops.
14/07/10 15:00:49 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2827 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56505 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 10066 ms, replay 2827 ops.
2014-07-10 15:00:53:475 90 sec: 835827 operations; 1444.86 current ops/sec; [INSERT AverageLatency(us)=2347.97] 
14/07/10 15:01:01 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 1533 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1347, waitTime=2673, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:54 PDT 2014, retrying after 10076 ms, replay 1533 ops.
14/07/10 15:01:01 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 2673 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1347, waitTime=2673, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 10012 ms, replay 2673 ops.
14/07/10 15:01:01 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2820 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1347, waitTime=2673, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 10096 ms, replay 2820 ops.
14/07/10 15:01:01 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 2328 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1347, waitTime=2673, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:53 PDT 2014, retrying after 10058 ms, replay 2328 ops.
14/07/10 15:01:01 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 2798 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1347, waitTime=2673, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 10020 ms, replay 2798 ops.
14/07/10 15:01:01 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 1923 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1347, waitTime=2673, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:54 PDT 2014, retrying after 10004 ms, replay 1923 ops.
14/07/10 15:01:01 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2289 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1347, waitTime=2673, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:51 PDT 2014, retrying after 10053 ms, replay 2289 ops.
14/07/10 15:01:01 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2822 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1347, waitTime=2673, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 10050 ms, replay 2822 ops.
14/07/10 15:01:01 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 3015 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1347, waitTime=2673, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 10056 ms, replay 3015 ops.
14/07/10 15:01:01 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2640 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1347, waitTime=2673, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:53 PDT 2014, retrying after 10042 ms, replay 2640 ops.
14/07/10 15:01:01 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2233 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1347, waitTime=2673, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:54 PDT 2014, retrying after 10053 ms, replay 2233 ops.
14/07/10 15:01:01 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 2827 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1347, waitTime=2673, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 10026 ms, replay 2827 ops.
14/07/10 15:01:01 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2670 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1347, waitTime=2673, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:50 PDT 2014, retrying after 10000 ms, replay 2670 ops.
14/07/10 15:01:01 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 3139 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1347, waitTime=2673, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 10034 ms, replay 3139 ops.
14/07/10 15:01:01 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 1851 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1347, waitTime=2673, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:53 PDT 2014, retrying after 10055 ms, replay 1851 ops.
14/07/10 15:01:01 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 2802 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1347, waitTime=2673, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 10073 ms, replay 2802 ops.
14/07/10 15:01:01 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 2824 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1347, waitTime=2673, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 10088 ms, replay 2824 ops.
14/07/10 15:01:01 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 2766 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1347, waitTime=2673, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:54 PDT 2014, retrying after 10044 ms, replay 2766 ops.
14/07/10 15:01:01 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 1891 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1347, waitTime=2673, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 10006 ms, replay 1891 ops.
2014-07-10 15:01:03:475 100 sec: 835827 operations; 0 current ops/sec;  
2014-07-10 15:01:13:476 110 sec: 835827 operations; 0 current ops/sec;  
14/07/10 15:01:14 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 failed 1891 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1440, waitTime=2800, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20128 ms, replay 1891 ops.
14/07/10 15:01:14 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 failed 1851 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1440, waitTime=2800, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:53 PDT 2014, retrying after 20101 ms, replay 1851 ops.
14/07/10 15:01:14 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 3139 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1440, waitTime=2800, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20134 ms, replay 3139 ops.
14/07/10 15:01:14 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 failed 2827 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1440, waitTime=2800, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20093 ms, replay 2827 ops.
14/07/10 15:01:14 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 failed 2289 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1440, waitTime=2800, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:51 PDT 2014, retrying after 20130 ms, replay 2289 ops.
14/07/10 15:01:14 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 2820 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1440, waitTime=2800, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20178 ms, replay 2820 ops.
14/07/10 15:01:14 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 failed 2640 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1440, waitTime=2800, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:53 PDT 2014, retrying after 20168 ms, replay 2640 ops.
14/07/10 15:01:14 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 failed 2824 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1440, waitTime=2800, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20093 ms, replay 2824 ops.
14/07/10 15:01:14 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 failed 2798 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1440, waitTime=2800, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20041 ms, replay 2798 ops.
14/07/10 15:01:14 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 1923 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1440, waitTime=2800, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:54 PDT 2014, retrying after 20038 ms, replay 1923 ops.
14/07/10 15:01:14 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 failed 2670 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1440, waitTime=2800, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:50 PDT 2014, retrying after 20029 ms, replay 2670 ops.
14/07/10 15:01:14 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 failed 2673 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1440, waitTime=2800, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20025 ms, replay 2673 ops.
14/07/10 15:01:14 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 2233 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1440, waitTime=2800, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:54 PDT 2014, retrying after 20096 ms, replay 2233 ops.
14/07/10 15:01:14 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 2328 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1440, waitTime=2800, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:53 PDT 2014, retrying after 20062 ms, replay 2328 ops.
14/07/10 15:01:14 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 2822 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1440, waitTime=2800, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20064 ms, replay 2822 ops.
14/07/10 15:01:14 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 failed 2766 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1440, waitTime=2800, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:54 PDT 2014, retrying after 20058 ms, replay 2766 ops.
14/07/10 15:01:14 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 failed 1533 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1440, waitTime=2800, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:54 PDT 2014, retrying after 20062 ms, replay 1533 ops.
14/07/10 15:01:14 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 failed 2802 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1440, waitTime=2800, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20175 ms, replay 2802 ops.
14/07/10 15:01:14 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 failed 3015 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1440, waitTime=2800, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20108 ms, replay 3015 ops.
2014-07-10 15:01:23:476 120 sec: 835827 operations; 0 current ops/sec;  
2014-07-10 15:01:33:477 130 sec: 902693 operations; 6685.93 current ops/sec; [INSERT AverageLatency(us)=5641.86] 
14/07/10 15:01:35 INFO client.AsyncProcess: #14, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014
14/07/10 15:01:35 INFO client.AsyncProcess: #11, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:54 PDT 2014
14/07/10 15:01:35 INFO client.AsyncProcess: #12, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014
14/07/10 15:01:36 INFO client.AsyncProcess: #6, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:50 PDT 2014
14/07/10 15:01:36 INFO client.AsyncProcess: #7, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:54 PDT 2014
14/07/10 15:01:36 INFO client.AsyncProcess: #11, table=usertable, attempt=13/35 failed 2328 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1708, waitTime=2034, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:53 PDT 2014, retrying after 20128 ms, replay 2328 ops.
14/07/10 15:01:36 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 failed 2233 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1708, waitTime=2034, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:54 PDT 2014, retrying after 20148 ms, replay 2233 ops.
14/07/10 15:01:36 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 failed 2822 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1708, waitTime=2034, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20020 ms, replay 2822 ops.
14/07/10 15:01:36 INFO client.AsyncProcess: #3, table=usertable, attempt=13/35 failed 2827 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1708, waitTime=2034, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20155 ms, replay 2827 ops.
14/07/10 15:01:36 INFO client.AsyncProcess: #6, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:53 PDT 2014
14/07/10 15:01:36 INFO client.AsyncProcess: #14, table=usertable, attempt=13/35 failed 2766 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1708, waitTime=2034, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:54 PDT 2014, retrying after 20026 ms, replay 2766 ops.
14/07/10 15:01:36 INFO client.AsyncProcess: #4, table=usertable, attempt=13/35 failed 2824 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1713, waitTime=2000, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20099 ms, replay 2824 ops.
14/07/10 15:01:36 INFO client.AsyncProcess: #18, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014
14/07/10 15:01:36 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014
14/07/10 15:01:36 INFO client.AsyncProcess: #6, table=usertable, attempt=13/35 failed 1891 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1714, waitTime=2110, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20006 ms, replay 1891 ops.
14/07/10 15:01:36 INFO client.AsyncProcess: #11, table=usertable, attempt=13/35 failed 3139 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1714, waitTime=2110, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20130 ms, replay 3139 ops.
14/07/10 15:01:36 INFO client.AsyncProcess: #7, table=usertable, attempt=13/35 failed 1851 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1714, waitTime=2110, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:53 PDT 2014, retrying after 20135 ms, replay 1851 ops.
14/07/10 15:01:36 INFO client.AsyncProcess: #19, table=usertable, attempt=13/35 failed 2289 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1714, waitTime=2110, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:51 PDT 2014, retrying after 20192 ms, replay 2289 ops.
14/07/10 15:01:36 INFO client.AsyncProcess: #8, table=usertable, attempt=13/35 failed 3015 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1714, waitTime=2110, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20121 ms, replay 3015 ops.
14/07/10 15:01:39 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2840 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1736, waitTime=2423, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:00:32 PDT 2014, retrying after 10030 ms, replay 2840 ops.
14/07/10 15:01:39 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2649 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1751, waitTime=2410, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:00:31 PDT 2014, retrying after 10060 ms, replay 2649 ops.
14/07/10 15:01:39 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2267 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1751, waitTime=2410, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:00:32 PDT 2014, retrying after 10017 ms, replay 2267 ops.
14/07/10 15:01:39 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2664 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1751, waitTime=2410, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:00:31 PDT 2014, retrying after 10098 ms, replay 2664 ops.
14/07/10 15:01:39 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2605 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1751, waitTime=2410, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:00:30 PDT 2014, retrying after 10098 ms, replay 2605 ops.
14/07/10 15:01:39 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2660 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1751, waitTime=2410, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:00:32 PDT 2014, retrying after 10047 ms, replay 2660 ops.
14/07/10 15:01:39 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2648 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1751, waitTime=2410, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:00:31 PDT 2014, retrying after 10017 ms, replay 2648 ops.
14/07/10 15:01:39 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2640 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1751, waitTime=2410, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:00:31 PDT 2014, retrying after 10069 ms, replay 2640 ops.
14/07/10 15:01:39 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2792 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1751, waitTime=2410, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:00:31 PDT 2014, retrying after 10054 ms, replay 2792 ops.
14/07/10 15:01:39 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 2616 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1751, waitTime=2410, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:00:32 PDT 2014, retrying after 10006 ms, replay 2616 ops.
2014-07-10 15:01:43:477 140 sec: 1042012 operations; 13931.9 current ops/sec; [INSERT AverageLatency(us)=2392.37] 
14/07/10 15:01:50 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:00:32 PDT 2014
14/07/10 15:01:51 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:00:32 PDT 2014
14/07/10 15:01:51 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:00:31 PDT 2014
14/07/10 15:01:51 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:00:32 PDT 2014
14/07/10 15:01:51 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:00:30 PDT 2014
14/07/10 15:01:51 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:00:31 PDT 2014
14/07/10 15:01:51 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:00:31 PDT 2014
14/07/10 15:01:51 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:00:32 PDT 2014
14/07/10 15:01:51 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 2792 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2172, waitTime=2024, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:00:31 PDT 2014, retrying after 10069 ms, replay 2792 ops.
14/07/10 15:01:51 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:00:31 PDT 2014
2014-07-10 15:01:53:478 150 sec: 1351972 operations; 30992.9 current ops/sec; [INSERT AverageLatency(us)=792.65] 
14/07/10 15:01:58 INFO client.AsyncProcess: #14, table=usertable, attempt=14/35 failed 2766 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2374, waitTime=2025, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:54 PDT 2014, retrying after 20115 ms, replay 2766 ops.
14/07/10 15:01:58 INFO client.AsyncProcess: #2, table=usertable, attempt=14/35 failed 2822 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2374, waitTime=2025, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20111 ms, replay 2822 ops.
14/07/10 15:01:59 INFO client.AsyncProcess: #11, table=usertable, attempt=14/35 failed 3139 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2376, waitTime=2250, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20162 ms, replay 3139 ops.
14/07/10 15:01:59 INFO client.AsyncProcess: #2, table=usertable, attempt=14/35 failed 2233 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2376, waitTime=2250, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:54 PDT 2014, retrying after 20146 ms, replay 2233 ops.
14/07/10 15:01:59 INFO client.AsyncProcess: #7, table=usertable, attempt=14/35 failed 1851 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2376, waitTime=2250, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:53 PDT 2014, retrying after 20082 ms, replay 1851 ops.
14/07/10 15:01:59 INFO client.AsyncProcess: #4, table=usertable, attempt=14/35 failed 2824 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2376, waitTime=2250, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20143 ms, replay 2824 ops.
14/07/10 15:01:59 INFO client.AsyncProcess: #3, table=usertable, attempt=14/35 failed 2827 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2376, waitTime=2250, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20013 ms, replay 2827 ops.
14/07/10 15:01:59 INFO client.AsyncProcess: #11, table=usertable, attempt=14/35 failed 2328 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2376, waitTime=2250, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:53 PDT 2014, retrying after 20024 ms, replay 2328 ops.
14/07/10 15:01:59 INFO client.AsyncProcess: #6, table=usertable, attempt=14/35 failed 1891 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2376, waitTime=2250, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20010 ms, replay 1891 ops.
14/07/10 15:01:59 INFO client.AsyncProcess: #8, table=usertable, attempt=14/35 failed 3015 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2376, waitTime=2250, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20165 ms, replay 3015 ops.
14/07/10 15:01:59 INFO client.AsyncProcess: #19, table=usertable, attempt=14/35 failed 2289 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2389, waitTime=2287, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:51 PDT 2014, retrying after 20045 ms, replay 2289 ops.
2014-07-10 15:02:03:478 160 sec: 1406211 operations; 5423.9 current ops/sec; [INSERT AverageLatency(us)=466.32] 
14/07/10 15:02:04 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 failed 2792 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2455, waitTime=2525, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:00:31 PDT 2014, retrying after 20008 ms, replay 2792 ops.
2014-07-10 15:02:13:479 170 sec: 1515098 operations; 10887.61 current ops/sec; [INSERT AverageLatency(us)=1415.02] 
14/07/10 15:02:21 INFO client.AsyncProcess: #14, table=usertable, attempt=15/35 failed 2766 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2889, waitTime=2424, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:54 PDT 2014, retrying after 20158 ms, replay 2766 ops.
14/07/10 15:02:21 INFO client.AsyncProcess: #2, table=usertable, attempt=15/35 failed 2822 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2889, waitTime=2424, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20182 ms, replay 2822 ops.
14/07/10 15:02:21 INFO client.AsyncProcess: #8, table=usertable, attempt=15/35 failed 3015 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2889, waitTime=2424, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20022 ms, replay 3015 ops.
14/07/10 15:02:21 INFO client.AsyncProcess: #7, table=usertable, attempt=15/35 failed 1851 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2889, waitTime=2424, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:53 PDT 2014, retrying after 20191 ms, replay 1851 ops.
14/07/10 15:02:21 INFO client.AsyncProcess: #2, table=usertable, attempt=15/35 failed 2233 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2889, waitTime=2424, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:54 PDT 2014, retrying after 20071 ms, replay 2233 ops.
14/07/10 15:02:21 INFO client.AsyncProcess: #6, table=usertable, attempt=15/35 failed 1891 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2889, waitTime=2424, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20190 ms, replay 1891 ops.
14/07/10 15:02:21 INFO client.AsyncProcess: #3, table=usertable, attempt=15/35 failed 2827 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2889, waitTime=2424, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20010 ms, replay 2827 ops.
14/07/10 15:02:21 INFO client.AsyncProcess: #11, table=usertable, attempt=15/35 failed 2328 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2889, waitTime=2424, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:53 PDT 2014, retrying after 20159 ms, replay 2328 ops.
14/07/10 15:02:21 INFO client.AsyncProcess: #11, table=usertable, attempt=15/35 failed 3139 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2889, waitTime=2424, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20156 ms, replay 3139 ops.
14/07/10 15:02:21 INFO client.AsyncProcess: #4, table=usertable, attempt=15/35 failed 2824 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2889, waitTime=2424, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20168 ms, replay 2824 ops.
14/07/10 15:02:21 INFO client.AsyncProcess: #19, table=usertable, attempt=15/35 failed 2289 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2911, waitTime=2037, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:51 PDT 2014, retrying after 20117 ms, replay 2289 ops.
2014-07-10 15:02:23:479 180 sec: 1716685 operations; 20158.7 current ops/sec; [INSERT AverageLatency(us)=311.72] 
14/07/10 15:02:26 INFO client.AsyncProcess: #1, table=usertable, attempt=13/35 failed 2792 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2995, waitTime=2040, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:00:31 PDT 2014, retrying after 20159 ms, replay 2792 ops.
2014-07-10 15:02:33:480 190 sec: 1858025 operations; 14132.59 current ops/sec; [INSERT AverageLatency(us)=714.55] 
2014-07-10 15:02:43:480 200 sec: 1898106 operations; 4008.1 current ops/sec; [INSERT AverageLatency(us)=238.57] 
14/07/10 15:02:43 INFO client.AsyncProcess: #2, table=usertable, attempt=16/35 failed 2233 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3419, waitTime=2153, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:54 PDT 2014, retrying after 20173 ms, replay 2233 ops.
14/07/10 15:02:43 INFO client.AsyncProcess: #3, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014
14/07/10 15:02:43 INFO client.AsyncProcess: #8, table=usertable, attempt=16/35 failed 3015 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3419, waitTime=2153, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20054 ms, replay 3015 ops.
14/07/10 15:02:43 INFO client.AsyncProcess: #14, table=usertable, attempt=16/35 failed 2766 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3419, waitTime=2153, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:54 PDT 2014, retrying after 20155 ms, replay 2766 ops.
14/07/10 15:02:43 INFO client.AsyncProcess: #11, table=usertable, attempt=16/35 failed 3139 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3419, waitTime=2153, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20127 ms, replay 3139 ops.
14/07/10 15:02:43 INFO client.AsyncProcess: #4, table=usertable, attempt=16/35 failed 2824 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3419, waitTime=2153, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20100 ms, replay 2824 ops.
14/07/10 15:02:43 INFO client.AsyncProcess: #11, table=usertable, attempt=16/35 failed 2328 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3419, waitTime=2153, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:53 PDT 2014, retrying after 20153 ms, replay 2328 ops.
14/07/10 15:02:43 INFO client.AsyncProcess: #6, table=usertable, attempt=16/35 failed 1891 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3425, waitTime=2149, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20069 ms, replay 1891 ops.
14/07/10 15:02:43 INFO client.AsyncProcess: #19, table=usertable, attempt=16/35 failed 2289 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3425, waitTime=2149, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:51 PDT 2014, retrying after 20087 ms, replay 2289 ops.
14/07/10 15:02:43 INFO client.AsyncProcess: #2, table=usertable, attempt=16/35 failed 2822 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3425, waitTime=2149, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20148 ms, replay 2822 ops.
14/07/10 15:02:43 INFO client.AsyncProcess: #7, table=usertable, attempt=16/35 failed 1851 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3425, waitTime=2149, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:53 PDT 2014, retrying after 20070 ms, replay 1851 ops.
14/07/10 15:02:43 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2850 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3425, waitTime=2149, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:01:52 PDT 2014, retrying after 10033 ms, replay 2850 ops.
14/07/10 15:02:48 INFO client.AsyncProcess: #1, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:00:31 PDT 2014
2014-07-10 15:02:53:481 210 sec: 2056989 operations; 15886.71 current ops/sec; [INSERT AverageLatency(us)=2750.14] 
14/07/10 15:02:55 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:01:52 PDT 2014
2014-07-10 15:03:03:481 220 sec: 2288743 operations; 23175.4 current ops/sec; [INSERT AverageLatency(us)=872.79] 
14/07/10 15:03:05 INFO client.AsyncProcess: #8, table=usertable, attempt=17/35 failed 3015 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4075, waitTime=2455, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20095 ms, replay 3015 ops.
14/07/10 15:03:05 INFO client.AsyncProcess: #11, table=usertable, attempt=17/35 failed 2328 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4075, waitTime=2455, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:53 PDT 2014, retrying after 20147 ms, replay 2328 ops.
14/07/10 15:03:05 INFO client.AsyncProcess: #4, table=usertable, attempt=17/35 failed 2824 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4075, waitTime=2455, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20101 ms, replay 2824 ops.
14/07/10 15:03:05 INFO client.AsyncProcess: #6, table=usertable, attempt=17/35 failed 1891 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4075, waitTime=2455, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20139 ms, replay 1891 ops.
14/07/10 15:03:05 INFO client.AsyncProcess: #11, table=usertable, attempt=17/35 failed 3139 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4075, waitTime=2455, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20174 ms, replay 3139 ops.
14/07/10 15:03:05 INFO client.AsyncProcess: #14, table=usertable, attempt=17/35 failed 2766 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4075, waitTime=2455, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:54 PDT 2014, retrying after 20041 ms, replay 2766 ops.
14/07/10 15:03:05 INFO client.AsyncProcess: #7, table=usertable, attempt=17/35 failed 1851 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4075, waitTime=2455, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:53 PDT 2014, retrying after 20041 ms, replay 1851 ops.
14/07/10 15:03:05 INFO client.AsyncProcess: #2, table=usertable, attempt=17/35 failed 2233 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4075, waitTime=2455, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:54 PDT 2014, retrying after 20160 ms, replay 2233 ops.
14/07/10 15:03:05 INFO client.AsyncProcess: #19, table=usertable, attempt=17/35 failed 2289 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4075, waitTime=2455, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:51 PDT 2014, retrying after 20188 ms, replay 2289 ops.
14/07/10 15:03:05 INFO client.AsyncProcess: #2, table=usertable, attempt=17/35 failed 2822 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4075, waitTime=2455, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20015 ms, replay 2822 ops.
2014-07-10 15:03:13:482 230 sec: 2366929 operations; 7817.82 current ops/sec; [INSERT AverageLatency(us)=1104.59] 
14/07/10 15:03:20 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2699 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56506 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:02:32 PDT 2014, retrying after 10075 ms, replay 2699 ops.
2014-07-10 15:03:23:482 240 sec: 2366929 operations; 0 current ops/sec;  
14/07/10 15:03:28 INFO client.AsyncProcess: #19, table=usertable, attempt=18/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:51 PDT 2014
14/07/10 15:03:28 INFO client.AsyncProcess: #7, table=usertable, attempt=18/35 failed 1851 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4436, waitTime=2028, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:53 PDT 2014, retrying after 20044 ms, replay 1851 ops.
14/07/10 15:03:28 INFO client.AsyncProcess: #2, table=usertable, attempt=18/35 failed 2822 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4436, waitTime=2028, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20187 ms, replay 2822 ops.
14/07/10 15:03:28 INFO client.AsyncProcess: #14, table=usertable, attempt=18/35 failed 2766 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4436, waitTime=2028, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:54 PDT 2014, retrying after 20012 ms, replay 2766 ops.
14/07/10 15:03:28 INFO client.AsyncProcess: #4, table=usertable, attempt=18/35 failed 2824 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4439, waitTime=2046, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20088 ms, replay 2824 ops.
14/07/10 15:03:28 INFO client.AsyncProcess: #2, table=usertable, attempt=18/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:54 PDT 2014
14/07/10 15:03:28 INFO client.AsyncProcess: #8, table=usertable, attempt=18/35 failed 3015 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4439, waitTime=2046, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20133 ms, replay 3015 ops.
14/07/10 15:03:28 INFO client.AsyncProcess: #6, table=usertable, attempt=18/35 failed 1891 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4439, waitTime=2046, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20165 ms, replay 1891 ops.
14/07/10 15:03:28 INFO client.AsyncProcess: #11, table=usertable, attempt=18/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:53 PDT 2014
14/07/10 15:03:28 INFO client.AsyncProcess: #11, table=usertable, attempt=18/35 failed 3139 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4444, waitTime=2049, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20183 ms, replay 3139 ops.
14/07/10 15:03:31 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:02:32 PDT 2014
2014-07-10 15:03:33:482 250 sec: 2577810 operations; 21088.1 current ops/sec; [INSERT AverageLatency(us)=2422.08] 
2014-07-10 15:03:43:483 260 sec: 2920121 operations; 34227.68 current ops/sec; [INSERT AverageLatency(us)=396.68] 
14/07/10 15:03:50 INFO client.AsyncProcess: #7, table=usertable, attempt=19/35 failed 1851 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5315, waitTime=3023, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:53 PDT 2014, retrying after 20137 ms, replay 1851 ops.
14/07/10 15:03:50 INFO client.AsyncProcess: #14, table=usertable, attempt=19/35 failed 2766 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5315, waitTime=3023, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:54 PDT 2014, retrying after 20099 ms, replay 2766 ops.
14/07/10 15:03:50 INFO client.AsyncProcess: #6, table=usertable, attempt=19/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014
14/07/10 15:03:50 INFO client.AsyncProcess: #2, table=usertable, attempt=19/35 failed 2822 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5323, waitTime=2088, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20060 ms, replay 2822 ops.
14/07/10 15:03:50 INFO client.AsyncProcess: #8, table=usertable, attempt=19/35 failed 3015 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5323, waitTime=2088, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20083 ms, replay 3015 ops.
14/07/10 15:03:50 INFO client.AsyncProcess: #11, table=usertable, attempt=19/35 failed 3139 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5323, waitTime=2088, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20156 ms, replay 3139 ops.
14/07/10 15:03:50 INFO client.AsyncProcess: #4, table=usertable, attempt=19/35 failed 2824 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5323, waitTime=2088, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20073 ms, replay 2824 ops.
2014-07-10 15:03:53:483 270 sec: 2999365 operations; 7924.4 current ops/sec; [INSERT AverageLatency(us)=3038.17] 
2014-07-10 15:04:03:484 280 sec: 3001074 operations; 170.88 current ops/sec; [INSERT AverageLatency(us)=4852.02] 
14/07/10 15:04:12 INFO client.AsyncProcess: #7, table=usertable, attempt=20/35 failed 1851 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5645, waitTime=2129, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:53 PDT 2014, retrying after 20054 ms, replay 1851 ops.
14/07/10 15:04:12 INFO client.AsyncProcess: #14, table=usertable, attempt=20/35 failed 2766 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5645, waitTime=2129, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:54 PDT 2014, retrying after 20044 ms, replay 2766 ops.
2014-07-10 15:04:13:484 290 sec: 3098541 operations; 9746.7 current ops/sec; [INSERT AverageLatency(us)=1482.73] 
14/07/10 15:04:13 INFO client.AsyncProcess: #2, table=usertable, attempt=20/35 failed 2822 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5648, waitTime=2646, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20077 ms, replay 2822 ops.
14/07/10 15:04:13 INFO client.AsyncProcess: #8, table=usertable, attempt=20/35 failed 3015 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5648, waitTime=2646, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20130 ms, replay 3015 ops.
14/07/10 15:04:13 INFO client.AsyncProcess: #11, table=usertable, attempt=20/35 failed 3139 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5648, waitTime=2646, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20089 ms, replay 3139 ops.
14/07/10 15:04:13 INFO client.AsyncProcess: #4, table=usertable, attempt=20/35 failed 2824 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5648, waitTime=2646, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20042 ms, replay 2824 ops.
2014-07-10 15:04:23:485 300 sec: 3209736 operations; 11118.39 current ops/sec; [INSERT AverageLatency(us)=539.14] 
14/07/10 15:04:33 INFO client.AsyncProcess: #7, table=usertable, attempt=21/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:53 PDT 2014
2014-07-10 15:04:33:485 310 sec: 3622900 operations; 41316.4 current ops/sec; [INSERT AverageLatency(us)=658.53] 
14/07/10 15:04:33 INFO client.AsyncProcess: #14, table=usertable, attempt=21/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:54 PDT 2014
14/07/10 15:04:35 INFO client.AsyncProcess: #4, table=usertable, attempt=21/35 failed 2824 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6495, waitTime=2698, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20168 ms, replay 2824 ops.
14/07/10 15:04:35 INFO client.AsyncProcess: #8, table=usertable, attempt=21/35 failed 3015 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6547, waitTime=2004, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20188 ms, replay 3015 ops.
14/07/10 15:04:35 INFO client.AsyncProcess: #11, table=usertable, attempt=21/35 failed 3139 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6495, waitTime=2698, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20075 ms, replay 3139 ops.
14/07/10 15:04:35 INFO client.AsyncProcess: #2, table=usertable, attempt=21/35 failed 2822 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6495, waitTime=2698, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014, retrying after 20078 ms, replay 2822 ops.
14/07/10 15:04:37 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2617 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6565, waitTime=3113, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:43 PDT 2014, retrying after 10048 ms, replay 2617 ops.
14/07/10 15:04:37 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2691 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6565, waitTime=3113, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:44 PDT 2014, retrying after 10044 ms, replay 2691 ops.
14/07/10 15:04:37 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2720 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6565, waitTime=3113, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:44 PDT 2014, retrying after 10048 ms, replay 2720 ops.
14/07/10 15:04:37 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2610 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6565, waitTime=3113, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:45 PDT 2014, retrying after 10034 ms, replay 2610 ops.
14/07/10 15:04:37 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2610 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6565, waitTime=3113, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:44 PDT 2014, retrying after 10015 ms, replay 2610 ops.
14/07/10 15:04:37 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2843 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6565, waitTime=3113, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:43 PDT 2014, retrying after 10085 ms, replay 2843 ops.
14/07/10 15:04:37 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2704 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6565, waitTime=3113, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:43 PDT 2014, retrying after 10024 ms, replay 2704 ops.
14/07/10 15:04:37 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2690 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6565, waitTime=3113, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:42 PDT 2014, retrying after 10059 ms, replay 2690 ops.
14/07/10 15:04:37 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2658 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6565, waitTime=3113, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:43 PDT 2014, retrying after 10068 ms, replay 2658 ops.
14/07/10 15:04:37 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2696 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6565, waitTime=3113, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:43 PDT 2014, retrying after 10000 ms, replay 2696 ops.
14/07/10 15:04:38 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2644 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6565, waitTime=3113, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:43 PDT 2014, retrying after 10049 ms, replay 2644 ops.
2014-07-10 15:04:43:486 320 sec: 3670532 operations; 4762.72 current ops/sec; [INSERT AverageLatency(us)=6987.42] 
14/07/10 15:04:50 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2696 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6759, waitTime=2010, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:43 PDT 2014, retrying after 10000 ms, replay 2696 ops.
14/07/10 15:04:50 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2617 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6760, waitTime=2131, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:43 PDT 2014, retrying after 10059 ms, replay 2617 ops.
14/07/10 15:04:50 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2704 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6760, waitTime=2131, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:43 PDT 2014, retrying after 10089 ms, replay 2704 ops.
14/07/10 15:04:50 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 2720 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6760, waitTime=2131, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:44 PDT 2014, retrying after 10091 ms, replay 2720 ops.
14/07/10 15:04:50 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2610 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6760, waitTime=2131, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:45 PDT 2014, retrying after 10070 ms, replay 2610 ops.
14/07/10 15:04:50 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 2691 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6760, waitTime=2131, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:44 PDT 2014, retrying after 10056 ms, replay 2691 ops.
14/07/10 15:04:50 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2610 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6760, waitTime=2131, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:44 PDT 2014, retrying after 10089 ms, replay 2610 ops.
14/07/10 15:04:50 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 2843 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6760, waitTime=2131, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:43 PDT 2014, retrying after 10028 ms, replay 2843 ops.
14/07/10 15:04:50 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 2644 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6760, waitTime=2131, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:43 PDT 2014, retrying after 10033 ms, replay 2644 ops.
14/07/10 15:04:50 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 2690 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6760, waitTime=2131, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:42 PDT 2014, retrying after 10059 ms, replay 2690 ops.
14/07/10 15:04:50 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 2658 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6760, waitTime=2131, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:43 PDT 2014, retrying after 10013 ms, replay 2658 ops.
2014-07-10 15:04:53:486 330 sec: 3670532 operations; 0 current ops/sec;  
14/07/10 15:04:56 INFO client.AsyncProcess: #11, table=usertable, attempt=22/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014
14/07/10 15:04:56 INFO client.AsyncProcess: #4, table=usertable, attempt=22/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014
14/07/10 15:04:56 INFO client.AsyncProcess: #2, table=usertable, attempt=22/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014
14/07/10 15:04:56 INFO client.AsyncProcess: #8, table=usertable, attempt=22/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 14:59:52 PDT 2014
14/07/10 15:05:01 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:43 PDT 2014
14/07/10 15:05:01 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:43 PDT 2014
14/07/10 15:05:01 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:44 PDT 2014
14/07/10 15:05:01 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:44 PDT 2014
14/07/10 15:05:02 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:45 PDT 2014
14/07/10 15:05:02 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:43 PDT 2014
14/07/10 15:05:02 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:42 PDT 2014
14/07/10 15:05:02 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:43 PDT 2014
14/07/10 15:05:02 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:44 PDT 2014
14/07/10 15:05:02 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:43 PDT 2014
14/07/10 15:05:02 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 failed 2843 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6961, waitTime=2050, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:43 PDT 2014, retrying after 20056 ms, replay 2843 ops.
2014-07-10 15:05:03:486 340 sec: 3983571 operations; 31303.9 current ops/sec; [INSERT AverageLatency(us)=6139.63] 
2014-07-10 15:05:13:487 350 sec: 4012151 operations; 2857.71 current ops/sec; [INSERT AverageLatency(us)=2573.53] 
2014-07-10 15:05:23:487 360 sec: 4191214 operations; 17906.3 current ops/sec; [INSERT AverageLatency(us)=1414.1] 
14/07/10 15:05:24 INFO client.AsyncProcess: #1, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:03:43 PDT 2014
2014-07-10 15:05:33:488 370 sec: 4448872 operations; 25763.22 current ops/sec; [INSERT AverageLatency(us)=1072.82] 
2014-07-10 15:05:43:488 380 sec: 4455772 operations; 690 current ops/sec; [INSERT AverageLatency(us)=15105.74] 
2014-07-10 15:05:53:489 390 sec: 4574109 operations; 11832.52 current ops/sec; [INSERT AverageLatency(us)=1258.63] 
2014-07-10 15:06:03:489 400 sec: 4731749 operations; 15764 current ops/sec; [INSERT AverageLatency(us)=1180.56] 
2014-07-10 15:06:13:489 410 sec: 4866330 operations; 13458.1 current ops/sec; [INSERT AverageLatency(us)=944.34] 
14/07/10 15:06:17 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2675 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8929, waitTime=2051, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:05:23 PDT 2014, retrying after 10052 ms, replay 2675 ops.
14/07/10 15:06:18 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2637 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8930, waitTime=3003, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:05:24 PDT 2014, retrying after 10009 ms, replay 2637 ops.
14/07/10 15:06:21 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2674 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8996, waitTime=2101, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:05:28 PDT 2014, retrying after 10058 ms, replay 2674 ops.
14/07/10 15:06:21 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 2698 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9006, waitTime=2186, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:05:28 PDT 2014, retrying after 10099 ms, replay 2698 ops.
14/07/10 15:06:21 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2629 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9006, waitTime=2186, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:05:29 PDT 2014, retrying after 10085 ms, replay 2629 ops.
14/07/10 15:06:21 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2533 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9006, waitTime=2186, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:05:28 PDT 2014, retrying after 10071 ms, replay 2533 ops.
2014-07-10 15:06:23:490 420 sec: 4871130 operations; 479.95 current ops/sec; [INSERT AverageLatency(us)=17582.15] 
14/07/10 15:06:28 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:05:24 PDT 2014
14/07/10 15:06:28 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:05:23 PDT 2014
14/07/10 15:06:32 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:05:28 PDT 2014
14/07/10 15:06:32 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:05:28 PDT 2014
14/07/10 15:06:32 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:05:29 PDT 2014
14/07/10 15:06:32 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:05:28 PDT 2014
2014-07-10 15:06:33:552 430 sec: 5037175 operations; 16502.19 current ops/sec; [INSERT AverageLatency(us)=3193.88] 
2014-07-10 15:06:43:552 440 sec: 5237097 operations; 19992.2 current ops/sec; [INSERT AverageLatency(us)=871.4] 
2014-07-10 15:06:53:553 450 sec: 5391105 operations; 15399.26 current ops/sec; [INSERT AverageLatency(us)=1141.21] 
14/07/10 15:06:55 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2700 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56508 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:03 PDT 2014, retrying after 10078 ms, replay 2700 ops.
14/07/10 15:06:55 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2619 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56508 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:04 PDT 2014, retrying after 10092 ms, replay 2619 ops.
2014-07-10 15:07:03:553 460 sec: 5465751 operations; 7464.6 current ops/sec; [INSERT AverageLatency(us)=692.46] 
14/07/10 15:07:08 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2700 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=10235, waitTime=2848, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:03 PDT 2014, retrying after 10070 ms, replay 2700 ops.
14/07/10 15:07:08 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 2619 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=10235, waitTime=2848, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:04 PDT 2014, retrying after 10006 ms, replay 2619 ops.
2014-07-10 15:07:13:554 470 sec: 5487393 operations; 2163.98 current ops/sec; [INSERT AverageLatency(us)=9823.08] 
14/07/10 15:07:20 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 failed 2619 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=10513, waitTime=2267, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:04 PDT 2014, retrying after 20109 ms, replay 2619 ops.
14/07/10 15:07:20 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 failed 2700 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=10513, waitTime=2267, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:03 PDT 2014, retrying after 20069 ms, replay 2700 ops.
2014-07-10 15:07:23:554 480 sec: 5590380 operations; 10298.7 current ops/sec; [INSERT AverageLatency(us)=1617.66] 
2014-07-10 15:07:33:555 490 sec: 5724586 operations; 13419.26 current ops/sec; [INSERT AverageLatency(us)=949.8] 
14/07/10 15:07:41 INFO client.AsyncProcess: #4, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:04 PDT 2014
14/07/10 15:07:41 INFO client.AsyncProcess: #6, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:03 PDT 2014
2014-07-10 15:07:43:555 500 sec: 6052855 operations; 32826.9 current ops/sec; [UPDATE AverageLatency(us)=8792861] [INSERT AverageLatency(us)=894.21] [CLEANUP AverageLatency(us)=8793056] 
14/07/10 15:07:44 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2661 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11181, waitTime=2666, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:51 PDT 2014, retrying after 10035 ms, replay 2661 ops.
14/07/10 15:07:44 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2667 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11181, waitTime=2666, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:51 PDT 2014, retrying after 10081 ms, replay 2667 ops.
14/07/10 15:07:44 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2653 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11181, waitTime=2666, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:53 PDT 2014, retrying after 10083 ms, replay 2653 ops.
14/07/10 15:07:44 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2223 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11181, waitTime=2666, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:52 PDT 2014, retrying after 10034 ms, replay 2223 ops.
14/07/10 15:07:48 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 1109 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11287, waitTime=3205, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:55 PDT 2014, retrying after 10099 ms, replay 1109 ops.
14/07/10 15:07:48 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2243 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11287, waitTime=3205, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 10031 ms, replay 2243 ops.
14/07/10 15:07:48 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2249 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11287, waitTime=3205, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 10082 ms, replay 2249 ops.
14/07/10 15:07:48 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2212 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11287, waitTime=3205, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 10070 ms, replay 2212 ops.
14/07/10 15:07:48 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2280 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11287, waitTime=3205, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:53 PDT 2014, retrying after 10062 ms, replay 2280 ops.
14/07/10 15:07:48 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2635 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11287, waitTime=3205, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:53 PDT 2014, retrying after 10046 ms, replay 2635 ops.
14/07/10 15:07:48 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 1868 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11287, waitTime=3205, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 10063 ms, replay 1868 ops.
14/07/10 15:07:48 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 1901 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11287, waitTime=3205, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 10088 ms, replay 1901 ops.
14/07/10 15:07:48 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2668 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11287, waitTime=3205, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 10004 ms, replay 2668 ops.
2014-07-10 15:07:53:556 510 sec: 6150968 operations; 9810.32 current ops/sec;  [INSERT AverageLatency(us)=883.88]  
14/07/10 15:07:55 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:51 PDT 2014
14/07/10 15:07:55 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:52 PDT 2014
14/07/10 15:07:56 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:53 PDT 2014
14/07/10 15:07:56 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 2667 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11570, waitTime=2169, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:51 PDT 2014, retrying after 10017 ms, replay 2667 ops.
14/07/10 15:08:00 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 1109 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11738, waitTime=2521, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:55 PDT 2014, retrying after 10070 ms, replay 1109 ops.
14/07/10 15:08:00 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2668 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11738, waitTime=2521, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 10096 ms, replay 2668 ops.
14/07/10 15:08:00 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 1901 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11738, waitTime=2521, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 10037 ms, replay 1901 ops.
14/07/10 15:08:00 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 2212 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11738, waitTime=2521, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 10016 ms, replay 2212 ops.
14/07/10 15:08:00 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 2243 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11738, waitTime=2521, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 10098 ms, replay 2243 ops.
14/07/10 15:08:00 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2249 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11738, waitTime=2521, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 10088 ms, replay 2249 ops.
14/07/10 15:08:00 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 1868 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11738, waitTime=2521, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 10045 ms, replay 1868 ops.
14/07/10 15:08:00 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 2635 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11738, waitTime=2521, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:53 PDT 2014, retrying after 10081 ms, replay 2635 ops.
14/07/10 15:08:00 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2280 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11738, waitTime=2521, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:53 PDT 2014, retrying after 10057 ms, replay 2280 ops.
2014-07-10 15:08:03:557 520 sec: 6405603 operations; 25463.5 current ops/sec; [UPDATE AverageLatency(us)=10757357] [INSERT AverageLatency(us)=827.02] [CLEANUP AverageLatency(us)=10758188] 
14/07/10 15:08:10 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 failed 2667 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=11937, waitTime=3450, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:51 PDT 2014, retrying after 20157 ms, replay 2667 ops.
14/07/10 15:08:13 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 failed 2243 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=12020, waitTime=3237, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 20053 ms, replay 2243 ops.
14/07/10 15:08:13 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 2668 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=12020, waitTime=3237, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 20158 ms, replay 2668 ops.
14/07/10 15:08:13 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 failed 2212 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=12020, waitTime=3237, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 20148 ms, replay 2212 ops.
14/07/10 15:08:13 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 failed 2635 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=12020, waitTime=3237, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:53 PDT 2014, retrying after 20035 ms, replay 2635 ops.
14/07/10 15:08:13 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 failed 2280 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=12020, waitTime=3237, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:53 PDT 2014, retrying after 20053 ms, replay 2280 ops.
14/07/10 15:08:13 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 failed 1868 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=12020, waitTime=3237, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 20044 ms, replay 1868 ops.
14/07/10 15:08:13 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 failed 1109 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=12020, waitTime=3237, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:55 PDT 2014, retrying after 20169 ms, replay 1109 ops.
2014-07-10 15:08:13:557 530 sec: 6471671 operations; 6606.14 current ops/sec;  [INSERT AverageLatency(us)=693.27]  
14/07/10 15:08:13 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 failed 2249 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=12020, waitTime=3237, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 20176 ms, replay 2249 ops.
14/07/10 15:08:13 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 failed 1901 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=12020, waitTime=3237, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 20133 ms, replay 1901 ops.
2014-07-10 15:08:23:558 540 sec: 6642263 operations; 17057.49 current ops/sec;  [INSERT AverageLatency(us)=1182.49]  
14/07/10 15:08:32 INFO client.AsyncProcess: #18, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:51 PDT 2014
2014-07-10 15:08:33:558 550 sec: 6948254 operations; 30599.1 current ops/sec;  [INSERT AverageLatency(us)=699.66]  
14/07/10 15:08:36 INFO client.AsyncProcess: #17, table=usertable, attempt=13/35 failed 2280 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=12729, waitTime=3080, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:53 PDT 2014, retrying after 20064 ms, replay 2280 ops.
14/07/10 15:08:36 INFO client.AsyncProcess: #16, table=usertable, attempt=13/35 failed 1868 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=12729, waitTime=3080, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 20198 ms, replay 1868 ops.
14/07/10 15:08:36 INFO client.AsyncProcess: #9, table=usertable, attempt=13/35 failed 2212 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=12729, waitTime=3080, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 20046 ms, replay 2212 ops.
14/07/10 15:08:36 INFO client.AsyncProcess: #17, table=usertable, attempt=13/35 failed 1901 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=12729, waitTime=3080, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 20160 ms, replay 1901 ops.
14/07/10 15:08:36 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 failed 2668 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=12729, waitTime=3080, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 20152 ms, replay 2668 ops.
14/07/10 15:08:36 INFO client.AsyncProcess: #19, table=usertable, attempt=13/35 failed 2249 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=12729, waitTime=3080, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 20060 ms, replay 2249 ops.
14/07/10 15:08:36 INFO client.AsyncProcess: #9, table=usertable, attempt=13/35 failed 1109 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=12729, waitTime=3080, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:55 PDT 2014, retrying after 20167 ms, replay 1109 ops.
14/07/10 15:08:36 INFO client.AsyncProcess: #16, table=usertable, attempt=13/35 failed 2243 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=12729, waitTime=3080, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 20187 ms, replay 2243 ops.
14/07/10 15:08:36 INFO client.AsyncProcess: #16, table=usertable, attempt=13/35 failed 2635 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=12729, waitTime=3080, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:53 PDT 2014, retrying after 20094 ms, replay 2635 ops.
2014-07-10 15:08:43:559 560 sec: 6974998 operations; 2674.13 current ops/sec;  [INSERT AverageLatency(us)=3145.38]  
2014-07-10 15:08:53:559 570 sec: 7222439 operations; 24744.1 current ops/sec; [UPDATE AverageLatency(us)=20138814] [INSERT AverageLatency(us)=457] [CLEANUP AverageLatency(us)=20138824] 
14/07/10 15:08:58 INFO client.AsyncProcess: #17, table=usertable, attempt=14/35 failed 1901 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=13311, waitTime=2173, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 20097 ms, replay 1901 ops.
14/07/10 15:08:58 INFO client.AsyncProcess: #19, table=usertable, attempt=14/35 failed 2249 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=13311, waitTime=2173, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 20187 ms, replay 2249 ops.
14/07/10 15:08:58 INFO client.AsyncProcess: #16, table=usertable, attempt=14/35 failed 2635 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=13311, waitTime=2173, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:53 PDT 2014, retrying after 20084 ms, replay 2635 ops.
14/07/10 15:08:58 INFO client.AsyncProcess: #17, table=usertable, attempt=14/35 failed 2280 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=13311, waitTime=2173, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:53 PDT 2014, retrying after 20169 ms, replay 2280 ops.
14/07/10 15:08:58 INFO client.AsyncProcess: #16, table=usertable, attempt=14/35 failed 2243 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=13311, waitTime=2173, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 20098 ms, replay 2243 ops.
14/07/10 15:08:58 INFO client.AsyncProcess: #9, table=usertable, attempt=14/35 failed 2212 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=13311, waitTime=2173, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 20009 ms, replay 2212 ops.
14/07/10 15:08:58 INFO client.AsyncProcess: #16, table=usertable, attempt=14/35 failed 1868 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=13311, waitTime=2173, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 20159 ms, replay 1868 ops.
14/07/10 15:08:58 INFO client.AsyncProcess: #9, table=usertable, attempt=14/35 failed 1109 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=13311, waitTime=2173, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:55 PDT 2014, retrying after 20120 ms, replay 1109 ops.
14/07/10 15:08:58 INFO client.AsyncProcess: #15, table=usertable, attempt=14/35 failed 2668 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=13311, waitTime=2173, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 20109 ms, replay 2668 ops.
2014-07-10 15:09:03:560 580 sec: 7222449 operations; 1 current ops/sec;  [INSERT AverageLatency(us)=339118.3]  
2014-07-10 15:09:13:621 590 sec: 7361618 operations; 13832.52 current ops/sec; [UPDATE AverageLatency(us)=1167720] [INSERT AverageLatency(us)=1392] [CLEANUP AverageLatency(us)=1167732] 
14/07/10 15:09:21 INFO client.AsyncProcess: #9, table=usertable, attempt=15/35 failed 1109 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56519 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:55 PDT 2014, retrying after 20019 ms, replay 1109 ops.
14/07/10 15:09:21 INFO client.AsyncProcess: #16, table=usertable, attempt=15/35 failed 1868 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56519 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 20126 ms, replay 1868 ops.
14/07/10 15:09:21 INFO client.AsyncProcess: #15, table=usertable, attempt=15/35 failed 2668 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56519 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 20141 ms, replay 2668 ops.
14/07/10 15:09:21 INFO client.AsyncProcess: #17, table=usertable, attempt=15/35 failed 1901 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56519 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 20055 ms, replay 1901 ops.
14/07/10 15:09:21 INFO client.AsyncProcess: #16, table=usertable, attempt=15/35 failed 2635 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56519 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:53 PDT 2014, retrying after 20052 ms, replay 2635 ops.
14/07/10 15:09:21 INFO client.AsyncProcess: #19, table=usertable, attempt=15/35 failed 2249 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56519 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 20092 ms, replay 2249 ops.
14/07/10 15:09:21 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2626 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56519 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:08:29 PDT 2014, retrying after 10094 ms, replay 2626 ops.
14/07/10 15:09:21 INFO client.AsyncProcess: #9, table=usertable, attempt=15/35 failed 2212 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56519 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 20041 ms, replay 2212 ops.
14/07/10 15:09:21 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2654 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56519 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:08:29 PDT 2014, retrying after 10048 ms, replay 2654 ops.
14/07/10 15:09:21 INFO client.AsyncProcess: #16, table=usertable, attempt=15/35 failed 2243 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56519 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014, retrying after 20122 ms, replay 2243 ops.
14/07/10 15:09:21 INFO client.AsyncProcess: #17, table=usertable, attempt=15/35 failed 2280 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56519 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:53 PDT 2014, retrying after 20052 ms, replay 2280 ops.
2014-07-10 15:09:23:622 600 sec: 7715206 operations; 35355.26 current ops/sec; [UPDATE AverageLatency(us)=1780963] [INSERT AverageLatency(us)=206.01] [CLEANUP AverageLatency(us)=1780974] 
14/07/10 15:09:31 INFO client.AsyncProcess: #18, waiting for some tasks to finish. Expected max=0, tasksSent=842, tasksDone=838, currentTasksDone=838, retries=233 hasError=false, tableName=usertable
2014-07-10 15:09:33:622 610 sec: 7716176 operations; 97 current ops/sec;  [INSERT AverageLatency(us)=12434.22]  
14/07/10 15:09:33 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 2654 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=14074, waitTime=2324, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:08:29 PDT 2014, retrying after 10060 ms, replay 2654 ops.
14/07/10 15:09:33 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 2626 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=14074, waitTime=2324, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:08:29 PDT 2014, retrying after 10089 ms, replay 2626 ops.
14/07/10 15:09:42 INFO client.AsyncProcess: #9, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:55 PDT 2014
14/07/10 15:09:42 INFO client.AsyncProcess: #17, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:53 PDT 2014
14/07/10 15:09:42 INFO client.AsyncProcess: #9, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014
14/07/10 15:09:42 INFO client.AsyncProcess: #17, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014
14/07/10 15:09:42 INFO client.AsyncProcess: #16, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014
14/07/10 15:09:42 INFO client.AsyncProcess: #16, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:53 PDT 2014
14/07/10 15:09:43 INFO client.AsyncProcess: #16, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014
14/07/10 15:09:43 INFO client.AsyncProcess: #15, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014
14/07/10 15:09:43 INFO client.AsyncProcess: #19, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:06:54 PDT 2014
2014-07-10 15:09:43:623 620 sec: 7867493 operations; 15130.19 current ops/sec; [UPDATE AverageLatency(us)=21864835] [INSERT AverageLatency(us)=5989.44] [CLEANUP AverageLatency(us)=21864848] 
14/07/10 15:09:45 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 failed 2626 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=14356, waitTime=2678, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:08:29 PDT 2014, retrying after 20134 ms, replay 2626 ops.
14/07/10 15:09:45 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 2654 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=14356, waitTime=2678, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:08:29 PDT 2014, retrying after 20118 ms, replay 2654 ops.
2014-07-10 15:09:53:624 630 sec: 8010873 operations; 14338 current ops/sec;  [INSERT AverageLatency(us)=406.35]  
2014-07-10 15:10:03:624 640 sec: 8361350 operations; 35044.2 current ops/sec; [UPDATE AverageLatency(us)=1509175] [INSERT AverageLatency(us)=422.95] [CLEANUP AverageLatency(us)=1509188] 
14/07/10 15:10:08 INFO client.AsyncProcess: #11, table=usertable, attempt=13/35 failed 2654 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=15261, waitTime=2409, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:08:29 PDT 2014, retrying after 20120 ms, replay 2654 ops.
14/07/10 15:10:08 INFO client.AsyncProcess: #1, table=usertable, attempt=13/35 failed 2626 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=15261, waitTime=2409, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:08:29 PDT 2014, retrying after 20037 ms, replay 2626 ops.
2014-07-10 15:10:13:625 650 sec: 8696908 operations; 33552.44 current ops/sec; [UPDATE AverageLatency(us)=3452198] [INSERT AverageLatency(us)=394.78] [CLEANUP AverageLatency(us)=3452209] 
2014-07-10 15:10:23:625 660 sec: 9089882 operations; 39297.4 current ops/sec; [UPDATE AverageLatency(us)=2126085] [INSERT AverageLatency(us)=241.76] [CLEANUP AverageLatency(us)=2126098] 
14/07/10 15:10:32 INFO client.AsyncProcess: #11, table=usertable, attempt=14/35 failed 2654 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56519 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:08:29 PDT 2014, retrying after 20005 ms, replay 2654 ops.
14/07/10 15:10:32 INFO client.AsyncProcess: #1, table=usertable, attempt=14/35 failed 2626 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56519 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:08:29 PDT 2014, retrying after 20163 ms, replay 2626 ops.
2014-07-10 15:10:33:626 670 sec: 9341690 operations; 25178.28 current ops/sec;  [INSERT AverageLatency(us)=173.46]  
14/07/10 15:10:38 INFO client.AsyncProcess: #14, waiting for some tasks to finish. Expected max=0, tasksSent=768, tasksDone=767, currentTasksDone=767, retries=214 hasError=false, tableName=usertable
14/07/10 15:10:39 INFO client.AsyncProcess: #9, waiting for some tasks to finish. Expected max=0, tasksSent=784, tasksDone=782, currentTasksDone=782, retries=197 hasError=false, tableName=usertable
2014-07-10 15:10:43:626 680 sec: 9413664 operations; 7197.4 current ops/sec; [UPDATE AverageLatency(us)=9078092] [INSERT AverageLatency(us)=1236.84] [CLEANUP AverageLatency(us)=9078102.6] 
14/07/10 15:10:52 INFO client.AsyncProcess: #11, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:08:29 PDT 2014
14/07/10 15:10:53 INFO client.AsyncProcess: #1, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405057622548, tracking started Thu Jul 10 15:08:29 PDT 2014
2014-07-10 15:10:53:635 690 sec: 9619744 operations; 20589.47 current ops/sec; [UPDATE AverageLatency(us)=843180.33] [INSERT AverageLatency(us)=1398.24] [CLEANUP AverageLatency(us)=843191] 
2014-07-10 15:11:03:636 700 sec: 9880752 operations; 26098.19 current ops/sec; [UPDATE AverageLatency(us)=805548] [INSERT AverageLatency(us)=68.85] [CLEANUP AverageLatency(us)=805558] 
2014-07-10 15:11:12:140 708 sec: 10000000 operations; 14024.23 current ops/sec; [UPDATE AverageLatency(us)=988326] [INSERT AverageLatency(us)=62.08] [CLEANUP AverageLatency(us)=988337] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1405030272
1405030272
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ false
+ false
+ false
+ false
+ false
+ false
+ false
+ false
+ let counter=1+1
+ read line
+ set +x
