++ ls caseresult/ -ltr
++ wc -l
+ filename=case66
+ mkdir caseresult/case66
+ ssh hadoop@master mkdir /home/hadoop/git/physical_design/caseresult/case66
+ RESULT_DIR=/home/hadoop/git/physical_design/caseresult/case66
+ TEN=10
+ SIXTY=60
+ SLEEP_TIME=300
+ YCSB_DIR=/home/hadoop/ycsb-0.1.4
+ number_of_operations=10000000
+ number_of_threads=20
+ number_of_records=10000000
+ output_file_suffix=.dat
+ experiment_list_file=/home/hadoop/git/physical_design/case66.list
+ clean=false
+ create=false
+ load=false
+ random_read=false
+ workloada=false
+ workloadb=false
+ workloadc=false
+ scan=false
+ all=false
+ for i in '$@'
+ '[' clean == all ']'
+ '[' clean == clean ']'
+ clean=true
+ for i in '$@'
+ '[' create == all ']'
+ '[' create == clean ']'
+ '[' create == create ']'
+ create=true
+ for i in '$@'
+ '[' load == all ']'
+ '[' load == clean ']'
+ '[' load == create ']'
+ '[' load == load ']'
+ load=true
+ let counter=1
+ cd /home/hadoop/ycsb-0.1.4
++ pwd
+ echo /home/hadoop/ycsb-0.1.4
/home/hadoop/ycsb-0.1.4
+ read line
+ false
+ true
+ echo 'sleeping for 60 ...'
sleeping for 60 ...
+ sleep 60
+ echo 'droping usertable...'
droping usertable...
+ ssh hadoop@master /home/hadoop/hbase/bin/hbase shell /home/hadoop/git/physical_design/delete_table
0 row(s) in 2.3440 seconds

0 row(s) in 0.8370 seconds

0 row(s) in 0.0700 seconds

+ echo 'sleeping for 300 ...'
sleeping for 300 ...
+ sleep 300
+ false
+ true
+ echo 'creating usertable...'
creating usertable...
+ create_statement='create '\''usertable'\'', { NAME=>'\''family'\'', COMPRESSION=>'\''GZ'\'', CONFIGURATION =>  { '\''hbase.hregion.majorcompaction'\'' => '\''0'\'', '\''hbase.hstore.compactionThreshold'\'' => '\''100000000000000'\'', '\''hbase.server.compactchecker.interval.multiplier'\'' => '\''100000000'\'', '\''hbase.hstore.compaction.max.size'\'' => '\''128'\'' } }, SPLITS => ['\''user1'\'', '\''user2'\'', '\''user3'\'', '\''user4'\'', '\''user5'\'', '\''user6'\'', '\''user7'\'', '\''user8'\'', '\''user9'\'']'
+ echo create ''\''usertable'\'',' '{' 'NAME=>'\''family'\'',' 'COMPRESSION=>'\''GZ'\'',' CONFIGURATION '=>' '{' ''\''hbase.hregion.majorcompaction'\''' '=>' ''\''0'\'',' ''\''hbase.hstore.compactionThreshold'\''' '=>' ''\''100000000000000'\'',' ''\''hbase.server.compactchecker.interval.multiplier'\''' '=>' ''\''100000000'\'',' ''\''hbase.hstore.compaction.max.size'\''' '=>' ''\''128'\''' '}' '},' SPLITS '=>' '['\''user1'\'',' ''\''user2'\'',' ''\''user3'\'',' ''\''user4'\'',' ''\''user5'\'',' ''\''user6'\'',' ''\''user7'\'',' ''\''user8'\'',' ''\''user9'\'']'
+ echo 'exit '
+ scp /home/hadoop/git/physical_design/caseresult/case66/create_1.script hadoop@master:/home/hadoop/git/physical_design/caseresult/case66/create_1.script
+ create_table /home/hadoop/git/physical_design/caseresult/case66/create_1.script
+ echo 'creating table...'
creating table...
+ echo /home/hadoop/git/physical_design/caseresult/case66/create_1.script
/home/hadoop/git/physical_design/caseresult/case66/create_1.script
+ ssh hadoop@master /home/hadoop/hbase/bin/hbase shell /home/hadoop/git/physical_design/caseresult/case66/create_1.script
0 row(s) in 1.7170 seconds

+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ false
+ true
+ echo 'loading data...'
loading data...
+ echo 'starting time: '
starting time: 
++ date +%s
+ echo 1405027544
1405027544
++ echo /home/hadoop/git/physical_design/caseresult/case66/load_1.dat
+ ./ld 10000000 20 /home/hadoop/git/physical_design/caseresult/case66/load_1.dat
Loading workload...
Starting test.
2014-07-10 14:25:44:943 0 sec: 0 operations; 
14/07/10 14:25:45 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/10 14:25:45 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm43.almaden.ibm.com
14/07/10 14:25:45 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/10 14:25:45 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/10 14:25:45 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/10 14:25:45 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf
14/07/10 14:25:45 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/10 14:25:45 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/10 14:25:45 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/10 14:25:45 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/10 14:25:45 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/10 14:25:45 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/10 14:25:45 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/10 14:25:45 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/10 14:25:45 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/10 14:25:45 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x62565cf8, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/10 14:25:45 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x62565cf8 connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/10 14:25:45 INFO zookeeper.ClientCnxn: Opening socket connection to server master/9.1.143.58:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/10 14:25:45 INFO zookeeper.ClientCnxn: Socket connection established to master/9.1.143.58:2181, initiating session
14/07/10 14:25:45 INFO zookeeper.ClientCnxn: Session establishment complete on server master/9.1.143.58:2181, sessionid = 0x4723d71c3f000b, negotiated timeout = 90000
2014-07-10 14:25:54:945 10 sec: 300524 operations; 30049.4 current ops/sec; [INSERT AverageLatency(us)=423.68] 
2014-07-10 14:26:04:946 20 sec: 403836 operations; 10329.13 current ops/sec; [INSERT AverageLatency(us)=606.86] 
2014-07-10 14:26:14:946 30 sec: 452315 operations; 4847.9 current ops/sec; [INSERT AverageLatency(us)=2683.09] 
2014-07-10 14:26:24:958 40 sec: 704343 operations; 25172.59 current ops/sec; [INSERT AverageLatency(us)=827.49] 
2014-07-10 14:26:34:958 50 sec: 896916 operations; 19257.3 current ops/sec; [INSERT AverageLatency(us)=839.17] 
2014-07-10 14:26:44:959 60 sec: 943876 operations; 4695.53 current ops/sec; [INSERT AverageLatency(us)=3345.72] 
14/07/10 14:26:46 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 1881 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=797, waitTime=2113, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:25:52 PDT 2014, retrying after 10088 ms, replay 1881 ops.
14/07/10 14:26:46 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 1831 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=797, waitTime=2113, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:25:52 PDT 2014, retrying after 10028 ms, replay 1831 ops.
14/07/10 14:26:46 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 1875 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=797, waitTime=2113, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:25:52 PDT 2014, retrying after 10027 ms, replay 1875 ops.
14/07/10 14:26:46 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 1846 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=797, waitTime=2113, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:25:52 PDT 2014, retrying after 10051 ms, replay 1846 ops.
14/07/10 14:26:46 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 1843 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=797, waitTime=2113, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:25:52 PDT 2014, retrying after 10044 ms, replay 1843 ops.
2014-07-10 14:26:54:959 70 sec: 1080060 operations; 13618.4 current ops/sec; [INSERT AverageLatency(us)=929.12] 
14/07/10 14:26:59 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 1831 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56419 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:25:52 PDT 2014, retrying after 10017 ms, replay 1831 ops.
14/07/10 14:26:59 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 failed 1881 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56419 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:25:52 PDT 2014, retrying after 10090 ms, replay 1881 ops.
14/07/10 14:26:59 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 1843 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56419 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:25:52 PDT 2014, retrying after 10064 ms, replay 1843 ops.
14/07/10 14:26:59 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 1875 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56419 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:25:52 PDT 2014, retrying after 10096 ms, replay 1875 ops.
14/07/10 14:26:59 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 1846 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56419 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:25:52 PDT 2014, retrying after 10024 ms, replay 1846 ops.
2014-07-10 14:27:04:960 80 sec: 1098844 operations; 1878.21 current ops/sec; [INSERT AverageLatency(us)=122.56] 
14/07/10 14:27:11 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 1831 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56419 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:25:52 PDT 2014, retrying after 20062 ms, replay 1831 ops.
14/07/10 14:27:11 INFO client.AsyncProcess: #5, table=usertable, attempt=12/35 failed 1881 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56419 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:25:52 PDT 2014, retrying after 20067 ms, replay 1881 ops.
14/07/10 14:27:11 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 failed 1843 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56419 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:25:52 PDT 2014, retrying after 20084 ms, replay 1843 ops.
14/07/10 14:27:11 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 failed 1846 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56419 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:25:52 PDT 2014, retrying after 20089 ms, replay 1846 ops.
14/07/10 14:27:11 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 failed 1875 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56419 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:25:52 PDT 2014, retrying after 20133 ms, replay 1875 ops.
2014-07-10 14:27:14:961 90 sec: 1098844 operations; 0 current ops/sec;  
2014-07-10 14:27:24:961 100 sec: 1098844 operations; 0 current ops/sec;  
14/07/10 14:27:33 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 failed 1831 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:25:52 PDT 2014, retrying after 20125 ms, replay 1831 ops.
14/07/10 14:27:33 INFO client.AsyncProcess: #10, table=usertable, attempt=13/35 failed 1843 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:25:52 PDT 2014, retrying after 20198 ms, replay 1843 ops.
14/07/10 14:27:34 INFO client.AsyncProcess: #5, table=usertable, attempt=13/35 failed 1881 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1192, waitTime=3054, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:25:52 PDT 2014, retrying after 20072 ms, replay 1881 ops.
14/07/10 14:27:34 INFO client.AsyncProcess: #4, table=usertable, attempt=13/35 failed 1846 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1192, waitTime=3054, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:25:52 PDT 2014, retrying after 20105 ms, replay 1846 ops.
14/07/10 14:27:34 INFO client.AsyncProcess: #13, table=usertable, attempt=13/35 failed 1875 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1192, waitTime=3054, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:25:52 PDT 2014, retrying after 20185 ms, replay 1875 ops.
2014-07-10 14:27:34:961 110 sec: 1098844 operations; 0 current ops/sec;  
14/07/10 14:27:40 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 1873 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1219, waitTime=2564, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:44 PDT 2014, retrying after 10050 ms, replay 1873 ops.
14/07/10 14:27:40 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 1788 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1219, waitTime=2564, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:44 PDT 2014, retrying after 10022 ms, replay 1788 ops.
14/07/10 14:27:40 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 1839 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1219, waitTime=2564, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:44 PDT 2014, retrying after 10025 ms, replay 1839 ops.
14/07/10 14:27:42 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 1877 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:29 PDT 2014, retrying after 10063 ms, replay 1877 ops.
14/07/10 14:27:42 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 1936 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:44 PDT 2014, retrying after 10088 ms, replay 1936 ops.
14/07/10 14:27:42 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 1900 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:44 PDT 2014, retrying after 10037 ms, replay 1900 ops.
14/07/10 14:27:42 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 1759 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:29 PDT 2014, retrying after 10016 ms, replay 1759 ops.
14/07/10 14:27:42 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 1828 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:44 PDT 2014, retrying after 10065 ms, replay 1828 ops.
14/07/10 14:27:42 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 1852 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:44 PDT 2014, retrying after 10012 ms, replay 1852 ops.
14/07/10 14:27:42 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 1853 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:45 PDT 2014, retrying after 10014 ms, replay 1853 ops.
14/07/10 14:27:42 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 1873 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:29 PDT 2014, retrying after 10054 ms, replay 1873 ops.
14/07/10 14:27:42 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 1885 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:45 PDT 2014, retrying after 10057 ms, replay 1885 ops.
2014-07-10 14:27:44:962 120 sec: 1098844 operations; 0 current ops/sec;  
14/07/10 14:27:51 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:44 PDT 2014
14/07/10 14:27:51 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:44 PDT 2014
14/07/10 14:27:51 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:44 PDT 2014
14/07/10 14:27:54 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:44 PDT 2014
14/07/10 14:27:54 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:29 PDT 2014
14/07/10 14:27:54 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:44 PDT 2014
14/07/10 14:27:54 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:45 PDT 2014
14/07/10 14:27:54 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:29 PDT 2014
14/07/10 14:27:54 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:29 PDT 2014
14/07/10 14:27:54 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:45 PDT 2014
14/07/10 14:27:54 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:44 PDT 2014
14/07/10 14:27:54 INFO client.AsyncProcess: #15, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:25:52 PDT 2014
14/07/10 14:27:54 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:44 PDT 2014
14/07/10 14:27:54 INFO client.AsyncProcess: #10, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:25:52 PDT 2014
2014-07-10 14:27:54:962 130 sec: 1145804 operations; 4696 current ops/sec; [INSERT AverageLatency(us)=17238.4] 
14/07/10 14:27:57 INFO client.AsyncProcess: #4, table=usertable, attempt=14/35 failed 1846 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1295, waitTime=2491, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:25:52 PDT 2014, retrying after 20050 ms, replay 1846 ops.
14/07/10 14:27:57 INFO client.AsyncProcess: #5, table=usertable, attempt=14/35 failed 1881 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1295, waitTime=2491, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:25:52 PDT 2014, retrying after 20184 ms, replay 1881 ops.
14/07/10 14:27:57 INFO client.AsyncProcess: #13, table=usertable, attempt=14/35 failed 1875 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1295, waitTime=2491, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:25:52 PDT 2014, retrying after 20052 ms, replay 1875 ops.
14/07/10 14:28:01 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 1879 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:50 PDT 2014, retrying after 10040 ms, replay 1879 ops.
14/07/10 14:28:01 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 1867 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:53 PDT 2014, retrying after 10016 ms, replay 1867 ops.
14/07/10 14:28:01 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 1878 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:52 PDT 2014, retrying after 10043 ms, replay 1878 ops.
14/07/10 14:28:01 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 1891 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:54 PDT 2014, retrying after 10049 ms, replay 1891 ops.
14/07/10 14:28:01 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 1846 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:49 PDT 2014, retrying after 10027 ms, replay 1846 ops.
14/07/10 14:28:01 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 1865 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:50 PDT 2014, retrying after 10042 ms, replay 1865 ops.
14/07/10 14:28:01 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 1855 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:53 PDT 2014, retrying after 10074 ms, replay 1855 ops.
14/07/10 14:28:01 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 1822 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:52 PDT 2014, retrying after 10037 ms, replay 1822 ops.
14/07/10 14:28:01 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 1927 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:53 PDT 2014, retrying after 10060 ms, replay 1927 ops.
14/07/10 14:28:01 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 1859 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:53 PDT 2014, retrying after 10051 ms, replay 1859 ops.
14/07/10 14:28:01 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 1921 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:50 PDT 2014, retrying after 10076 ms, replay 1921 ops.
14/07/10 14:28:01 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 1884 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:53 PDT 2014, retrying after 10043 ms, replay 1884 ops.
14/07/10 14:28:01 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 1904 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:51 PDT 2014, retrying after 10086 ms, replay 1904 ops.
2014-07-10 14:28:04:963 140 sec: 1220940 operations; 7512.85 current ops/sec; [INSERT AverageLatency(us)=1003.13] 
2014-07-10 14:28:14:963 150 sec: 1253812 operations; 3287.2 current ops/sec; [INSERT AverageLatency(us)=418.96] 
14/07/10 14:28:15 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 1878 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:52 PDT 2014, retrying after 10072 ms, replay 1878 ops.
14/07/10 14:28:15 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 1865 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:50 PDT 2014, retrying after 10017 ms, replay 1865 ops.
14/07/10 14:28:15 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 1855 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:53 PDT 2014, retrying after 10029 ms, replay 1855 ops.
14/07/10 14:28:15 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 1904 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:51 PDT 2014, retrying after 10009 ms, replay 1904 ops.
14/07/10 14:28:15 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 1891 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:54 PDT 2014, retrying after 10020 ms, replay 1891 ops.
14/07/10 14:28:15 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 1822 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:52 PDT 2014, retrying after 10070 ms, replay 1822 ops.
14/07/10 14:28:15 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 1879 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:50 PDT 2014, retrying after 10040 ms, replay 1879 ops.
14/07/10 14:28:15 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 1921 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:50 PDT 2014, retrying after 10025 ms, replay 1921 ops.
14/07/10 14:28:15 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 1927 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:53 PDT 2014, retrying after 10047 ms, replay 1927 ops.
14/07/10 14:28:15 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 1859 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:53 PDT 2014, retrying after 10069 ms, replay 1859 ops.
14/07/10 14:28:15 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 1884 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:53 PDT 2014, retrying after 10005 ms, replay 1884 ops.
14/07/10 14:28:15 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 1846 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:49 PDT 2014, retrying after 10003 ms, replay 1846 ops.
14/07/10 14:28:15 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 1867 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56421 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:53 PDT 2014, retrying after 10079 ms, replay 1867 ops.
14/07/10 14:28:18 INFO client.AsyncProcess: #4, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:25:52 PDT 2014
14/07/10 14:28:18 INFO client.AsyncProcess: #5, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:25:52 PDT 2014
14/07/10 14:28:18 INFO client.AsyncProcess: #13, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:25:52 PDT 2014
2014-07-10 14:28:24:964 160 sec: 1389996 operations; 13617.04 current ops/sec; [INSERT AverageLatency(us)=4109.89] 
14/07/10 14:28:27 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:53 PDT 2014
14/07/10 14:28:27 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 failed 1884 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1621, waitTime=2048, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:53 PDT 2014, retrying after 20081 ms, replay 1884 ops.
14/07/10 14:28:27 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 failed 1822 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1621, waitTime=2048, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:52 PDT 2014, retrying after 20168 ms, replay 1822 ops.
14/07/10 14:28:27 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 failed 1855 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1621, waitTime=2048, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:53 PDT 2014, retrying after 20170 ms, replay 1855 ops.
14/07/10 14:28:27 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 1878 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1621, waitTime=2048, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:52 PDT 2014, retrying after 20016 ms, replay 1878 ops.
14/07/10 14:28:27 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 failed 1891 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1621, waitTime=2048, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:54 PDT 2014, retrying after 20046 ms, replay 1891 ops.
14/07/10 14:28:27 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 failed 1865 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1621, waitTime=2048, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:50 PDT 2014, retrying after 20087 ms, replay 1865 ops.
14/07/10 14:28:27 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 failed 1927 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1621, waitTime=2048, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:53 PDT 2014, retrying after 20034 ms, replay 1927 ops.
14/07/10 14:28:27 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 failed 1846 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1621, waitTime=2048, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:49 PDT 2014, retrying after 20150 ms, replay 1846 ops.
14/07/10 14:28:27 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 failed 1879 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1621, waitTime=2048, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:50 PDT 2014, retrying after 20044 ms, replay 1879 ops.
14/07/10 14:28:27 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 failed 1921 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1621, waitTime=2048, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:50 PDT 2014, retrying after 20096 ms, replay 1921 ops.
14/07/10 14:28:27 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 1904 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1621, waitTime=2048, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:51 PDT 2014, retrying after 20088 ms, replay 1904 ops.
14/07/10 14:28:27 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 failed 1867 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1641, waitTime=2052, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:53 PDT 2014, retrying after 20029 ms, replay 1867 ops.
2014-07-10 14:28:34:964 170 sec: 1591924 operations; 20192.8 current ops/sec; [INSERT AverageLatency(us)=779.77] 
2014-07-10 14:28:44:976 180 sec: 1790720 operations; 19857.76 current ops/sec; [INSERT AverageLatency(us)=880.95] 
14/07/10 14:28:47 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:52 PDT 2014
14/07/10 14:28:47 INFO client.AsyncProcess: #17, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:53 PDT 2014
14/07/10 14:28:47 INFO client.AsyncProcess: #6, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:50 PDT 2014
14/07/10 14:28:47 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:51 PDT 2014
14/07/10 14:28:48 INFO client.AsyncProcess: #17, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:50 PDT 2014
14/07/10 14:28:48 INFO client.AsyncProcess: #19, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:53 PDT 2014
14/07/10 14:28:48 INFO client.AsyncProcess: #6, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:54 PDT 2014
14/07/10 14:28:49 INFO client.AsyncProcess: #7, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:50 PDT 2014
14/07/10 14:28:49 INFO client.AsyncProcess: #17, table=usertable, attempt=13/35 failed 1855 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1903, waitTime=2181, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:53 PDT 2014, retrying after 20106 ms, replay 1855 ops.
14/07/10 14:28:49 INFO client.AsyncProcess: #9, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:49 PDT 2014
14/07/10 14:28:49 INFO client.AsyncProcess: #19, table=usertable, attempt=13/35 failed 1822 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1903, waitTime=2181, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:52 PDT 2014, retrying after 20104 ms, replay 1822 ops.
14/07/10 14:28:49 INFO client.AsyncProcess: #6, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:53 PDT 2014
2014-07-10 14:28:54:976 190 sec: 2023956 operations; 23321.27 current ops/sec; [INSERT AverageLatency(us)=3040.8] 
2014-07-10 14:29:04:977 200 sec: 2155444 operations; 13148.8 current ops/sec; [INSERT AverageLatency(us)=867.16] 
14/07/10 14:29:10 INFO client.AsyncProcess: #19, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:52 PDT 2014
14/07/10 14:29:10 INFO client.AsyncProcess: #17, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:26:53 PDT 2014
2014-07-10 14:29:14:977 210 sec: 2324500 operations; 16903.91 current ops/sec; [INSERT AverageLatency(us)=2819.79] 
2014-07-10 14:29:24:978 220 sec: 2517036 operations; 19251.67 current ops/sec; [INSERT AverageLatency(us)=1235.66] 
2014-07-10 14:29:34:978 230 sec: 2695484 operations; 17844.8 current ops/sec; [INSERT AverageLatency(us)=1284.07] 
2014-07-10 14:29:44:979 240 sec: 2789404 operations; 9391.06 current ops/sec; [INSERT AverageLatency(us)=1048.14] 
2014-07-10 14:29:54:979 250 sec: 2897412 operations; 10800.8 current ops/sec; [INSERT AverageLatency(us)=1789.45] 
2014-07-10 14:30:04:980 260 sec: 3094644 operations; 19721.23 current ops/sec; [INSERT AverageLatency(us)=1486.52] 
2014-07-10 14:30:14:980 270 sec: 3310660 operations; 21601.6 current ops/sec; [INSERT AverageLatency(us)=792.01] 
2014-07-10 14:30:24:981 280 sec: 3559548 operations; 24886.31 current ops/sec; [INSERT AverageLatency(us)=888.69] 
2014-07-10 14:30:34:981 290 sec: 3658164 operations; 9861.6 current ops/sec; [INSERT AverageLatency(us)=599.26] 
2014-07-10 14:30:44:982 300 sec: 3658164 operations; 0 current ops/sec;  
2014-07-10 14:30:54:982 310 sec: 3869484 operations; 21132 current ops/sec; [INSERT AverageLatency(us)=2582.79] 
2014-07-10 14:31:04:983 320 sec: 4193508 operations; 32399.16 current ops/sec; [INSERT AverageLatency(us)=515.94] 
2014-07-10 14:31:14:984 330 sec: 4216988 operations; 2348 current ops/sec; [INSERT AverageLatency(us)=238.17] 
2014-07-10 14:31:24:984 340 sec: 4216988 operations; 0 current ops/sec;  
2014-07-10 14:31:34:985 350 sec: 4216988 operations; 0 current ops/sec;  
2014-07-10 14:31:44:985 360 sec: 4371956 operations; 15495.25 current ops/sec; [INSERT AverageLatency(us)=1443.7] 
14/07/10 14:31:53 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 1879 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3632, waitTime=2247, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:31:00 PDT 2014, retrying after 10057 ms, replay 1879 ops.
14/07/10 14:31:53 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 1823 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3632, waitTime=2247, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:31:02 PDT 2014, retrying after 10007 ms, replay 1823 ops.
14/07/10 14:31:53 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 1852 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3632, waitTime=2247, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:31:02 PDT 2014, retrying after 10019 ms, replay 1852 ops.
14/07/10 14:31:53 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 1874 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3632, waitTime=2247, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:31:02 PDT 2014, retrying after 10061 ms, replay 1874 ops.
2014-07-10 14:31:54:986 370 sec: 4789900 operations; 41794.4 current ops/sec; [INSERT AverageLatency(us)=1451.94] 
2014-07-10 14:32:04:986 380 sec: 4808684 operations; 1878.21 current ops/sec; [INSERT AverageLatency(us)=201.32] 
14/07/10 14:32:05 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 1852 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3817, waitTime=2607, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:31:02 PDT 2014, retrying after 10032 ms, replay 1852 ops.
14/07/10 14:32:05 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 1823 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3817, waitTime=2607, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:31:02 PDT 2014, retrying after 10091 ms, replay 1823 ops.
14/07/10 14:32:06 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 1879 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3841, waitTime=2331, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:31:00 PDT 2014, retrying after 10099 ms, replay 1879 ops.
14/07/10 14:32:06 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 1874 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3841, waitTime=2331, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:31:02 PDT 2014, retrying after 10044 ms, replay 1874 ops.
2014-07-10 14:32:14:987 390 sec: 4808684 operations; 0 current ops/sec;  
14/07/10 14:32:17 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 failed 1879 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:31:00 PDT 2014, retrying after 20050 ms, replay 1879 ops.
14/07/10 14:32:17 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 failed 1874 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:31:02 PDT 2014, retrying after 20075 ms, replay 1874 ops.
14/07/10 14:32:17 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 failed 1823 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:31:02 PDT 2014, retrying after 20018 ms, replay 1823 ops.
14/07/10 14:32:17 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 1852 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:31:02 PDT 2014, retrying after 20025 ms, replay 1852 ops.
2014-07-10 14:32:24:987 400 sec: 4808684 operations; 0 current ops/sec;  
2014-07-10 14:32:34:987 410 sec: 5024700 operations; 21601.6 current ops/sec; [INSERT AverageLatency(us)=1138.51] 
14/07/10 14:32:38 INFO client.AsyncProcess: #16, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:31:02 PDT 2014
14/07/10 14:32:38 INFO client.AsyncProcess: #1, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:31:00 PDT 2014
14/07/10 14:32:38 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:31:02 PDT 2014
14/07/10 14:32:38 INFO client.AsyncProcess: #17, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405055604969, tracking started Thu Jul 10 14:31:02 PDT 2014
2014-07-10 14:32:44:988 420 sec: 5456732 operations; 43198.88 current ops/sec; [INSERT AverageLatency(us)=2181.18] 
2014-07-10 14:32:54:988 430 sec: 5797073 operations; 34034.1 current ops/sec; [INSERT AverageLatency(us)=561.23] 
2014-07-10 14:33:04:998 440 sec: 5993755 operations; 19648.55 current ops/sec; [INSERT AverageLatency(us)=544.33] 
2014-07-10 14:33:14:999 450 sec: 6289625 operations; 29584.04 current ops/sec; [INSERT AverageLatency(us)=905.52] 
2014-07-10 14:33:24:999 460 sec: 6827964 operations; 53833.9 current ops/sec; [INSERT AverageLatency(us)=447.62] 
2014-07-10 14:33:35:000 470 sec: 7350225 operations; 52220.88 current ops/sec; [UPDATE AverageLatency(us)=1887062] [INSERT AverageLatency(us)=350.37] [CLEANUP AverageLatency(us)=1887210] 
2014-07-10 14:33:45:119 480 sec: 7909814 operations; 55300.82 current ops/sec;  [INSERT AverageLatency(us)=353.94]  
2014-07-10 14:33:55:119 490 sec: 8365289 operations; 45547.5 current ops/sec; [UPDATE AverageLatency(us)=3438730] [INSERT AverageLatency(us)=421.56] [CLEANUP AverageLatency(us)=3439138] 
2014-07-10 14:34:05:120 500 sec: 8874928 operations; 50958.8 current ops/sec;  [INSERT AverageLatency(us)=343.63]  
2014-07-10 14:34:15:121 510 sec: 8874928 operations; 0 current ops/sec;    
14/07/10 14:34:17 INFO client.AsyncProcess: #3, waiting for some tasks to finish. Expected max=0, tasksSent=313, tasksDone=312, currentTasksDone=312, retries=99 hasError=false, tableName=usertable
2014-07-10 14:34:25:121 520 sec: 9210323 operations; 33539.5 current ops/sec; [UPDATE AverageLatency(us)=9718563.8] [INSERT AverageLatency(us)=1012.37] [CLEANUP AverageLatency(us)=9718575.8] 
2014-07-10 14:34:35:122 530 sec: 9690802 operations; 48043.1 current ops/sec; [UPDATE AverageLatency(us)=2206684.67] [INSERT AverageLatency(us)=216.9] [CLEANUP AverageLatency(us)=2206696.33] 
2014-07-10 14:34:45:122 540 sec: 9690802 operations; 0 current ops/sec;    
14/07/10 14:34:51 INFO client.AsyncProcess: #8, waiting for some tasks to finish. Expected max=0, tasksSent=301, tasksDone=299, currentTasksDone=299, retries=87 hasError=false, tableName=usertable
2014-07-10 14:34:55:144 550 sec: 9883393 operations; 19216.82 current ops/sec; [UPDATE AverageLatency(us)=17790981.75] [INSERT AverageLatency(us)=645.96] [CLEANUP AverageLatency(us)=17790991.5] 
2014-07-10 14:34:59:140 554 sec: 10000000 operations; 29188.24 current ops/sec; [UPDATE AverageLatency(us)=672656.5] [INSERT AverageLatency(us)=80.97] [CLEANUP AverageLatency(us)=672669.17] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1405028099
1405028099
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ false
+ false
+ false
+ false
+ false
+ false
+ false
+ false
+ let counter=1+1
+ read line
+ set +x
