++ ls caseresult/ -ltr
++ wc -l
+ filename=case77
+ mkdir caseresult/case77
+ ssh hadoop@master mkdir /home/hadoop/git/physical_design/caseresult/case77
+ RESULT_DIR=/home/hadoop/git/physical_design/caseresult/case77
+ TEN=10
+ SIXTY=60
+ SLEEP_TIME=300
+ YCSB_DIR=/home/hadoop/ycsb-0.1.4
+ number_of_operations=10000000
+ number_of_threads=20
+ number_of_records=10000000
+ output_file_suffix=.dat
+ experiment_list_file=/home/hadoop/git/physical_design/case77.list
+ clean=false
+ create=false
+ load=false
+ random_read=false
+ workloada=false
+ workloadb=false
+ workloadc=false
+ scan=false
+ all=false
+ for i in '$@'
+ '[' clean == all ']'
+ '[' clean == clean ']'
+ clean=true
+ for i in '$@'
+ '[' create == all ']'
+ '[' create == clean ']'
+ '[' create == create ']'
+ create=true
+ for i in '$@'
+ '[' load == all ']'
+ '[' load == clean ']'
+ '[' load == create ']'
+ '[' load == load ']'
+ load=true
+ let counter=1
+ cd /home/hadoop/ycsb-0.1.4
++ pwd
+ echo /home/hadoop/ycsb-0.1.4
/home/hadoop/ycsb-0.1.4
+ read line
+ false
+ true
+ echo 'sleeping for 60 ...'
sleeping for 60 ...
+ sleep 60
+ echo 'droping usertable...'
droping usertable...
+ ssh hadoop@master /home/hadoop/hbase/bin/hbase shell /home/hadoop/git/physical_design/delete_table
0 row(s) in 2.7840 seconds

0 row(s) in 0.8020 seconds

0 row(s) in 0.0740 seconds

+ echo 'sleeping for 300 ...'
sleeping for 300 ...
+ sleep 300
+ false
+ true
+ echo 'creating usertable...'
creating usertable...
+ create_statement='create '\''usertable'\'', { NAME=>'\''family'\'', CONFIGURATION => { '\''hbase.hregion.majorcompaction'\'' => '\''0'\'' } ,  COMPRESSION=>'\''GZ'\''}, SPLITS => ['\''user1'\'', '\''user2'\'', '\''user3'\'', '\''user4'\'', '\''user5'\'', '\''user6'\'', '\''user7'\'', '\''user8'\'', '\''user9'\'']'
+ echo create ''\''usertable'\'',' '{' 'NAME=>'\''family'\'',' CONFIGURATION '=>' '{' ''\''hbase.hregion.majorcompaction'\''' '=>' ''\''0'\''' '}' , 'COMPRESSION=>'\''GZ'\''},' SPLITS '=>' '['\''user1'\'',' ''\''user2'\'',' ''\''user3'\'',' ''\''user4'\'',' ''\''user5'\'',' ''\''user6'\'',' ''\''user7'\'',' ''\''user8'\'',' ''\''user9'\'']'
+ echo 'exit '
+ scp /home/hadoop/git/physical_design/caseresult/case77/create_1.script hadoop@master:/home/hadoop/git/physical_design/caseresult/case77/create_1.script
+ create_table /home/hadoop/git/physical_design/caseresult/case77/create_1.script
+ echo 'creating table...'
creating table...
+ echo /home/hadoop/git/physical_design/caseresult/case77/create_1.script
/home/hadoop/git/physical_design/caseresult/case77/create_1.script
+ ssh hadoop@master /home/hadoop/hbase/bin/hbase shell /home/hadoop/git/physical_design/caseresult/case77/create_1.script
0 row(s) in 1.7210 seconds

+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ false
+ true
+ echo 'loading data...'
loading data...
+ echo 'starting time: '
starting time: 
++ date +%s
+ echo 1405039196
1405039196
++ echo /home/hadoop/git/physical_design/caseresult/case77/load_1.dat
+ ./ld 10000000 20 /home/hadoop/git/physical_design/caseresult/case77/load_1.dat
Loading workload...
Starting test.
2014-07-10 17:39:56:979 0 sec: 0 operations; 
14/07/10 17:39:57 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/10 17:39:57 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm43.almaden.ibm.com
14/07/10 17:39:57 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/10 17:39:57 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/10 17:39:57 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/10 17:39:57 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf
14/07/10 17:39:57 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/10 17:39:57 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/10 17:39:57 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/10 17:39:57 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/10 17:39:57 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/10 17:39:57 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/10 17:39:57 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/10 17:39:57 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/10 17:39:57 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/10 17:39:57 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x62565cf8, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/10 17:39:57 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x62565cf8 connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/10 17:39:57 INFO zookeeper.ClientCnxn: Opening socket connection to server slave1/9.1.143.59:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/10 17:39:57 INFO zookeeper.ClientCnxn: Socket connection established to slave1/9.1.143.59:2181, initiating session
14/07/10 17:39:57 INFO zookeeper.ClientCnxn: Session establishment complete on server slave1/9.1.143.59:2181, sessionid = 0x1472488e849000e, negotiated timeout = 90000
2014-07-10 17:40:06:980 10 sec: 262066 operations; 26203.98 current ops/sec; [INSERT AverageLatency(us)=451.46] 
2014-07-10 17:40:16:981 20 sec: 344423 operations; 8234.88 current ops/sec; [INSERT AverageLatency(us)=644.89] 
2014-07-10 17:40:26:982 30 sec: 516169 operations; 17174.6 current ops/sec; [INSERT AverageLatency(us)=1093.02] 
2014-07-10 17:40:36:982 40 sec: 632243 operations; 11606.24 current ops/sec; [INSERT AverageLatency(us)=1190.95] 
2014-07-10 17:40:46:982 50 sec: 869481 operations; 23723.8 current ops/sec; [INSERT AverageLatency(us)=789] 
14/07/10 17:40:53 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2401 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1306, waitTime=2478, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:39:59 PDT 2014, retrying after 10059 ms, replay 2401 ops.
14/07/10 17:40:53 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2397 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1306, waitTime=2478, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:39:59 PDT 2014, retrying after 10036 ms, replay 2397 ops.
14/07/10 17:40:53 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2429 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1306, waitTime=2478, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:39:59 PDT 2014, retrying after 10031 ms, replay 2429 ops.
14/07/10 17:40:53 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2423 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1306, waitTime=2478, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:39:59 PDT 2014, retrying after 10040 ms, replay 2423 ops.
14/07/10 17:40:53 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2416 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1306, waitTime=2478, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:39:59 PDT 2014, retrying after 10052 ms, replay 2416 ops.
2014-07-10 17:40:56:983 60 sec: 869481 operations; 0 current ops/sec;  
2014-07-10 17:41:06:983 70 sec: 869481 operations; 0 current ops/sec;  
14/07/10 17:41:15 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 2423 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56897 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:39:59 PDT 2014, retrying after 10022 ms, replay 2423 ops.
2014-07-10 17:41:16:984 80 sec: 869481 operations; 0 current ops/sec;  
14/07/10 17:41:17 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2397 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56897 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:39:59 PDT 2014, retrying after 10042 ms, replay 2397 ops.
14/07/10 17:41:17 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 2416 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56897 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:39:59 PDT 2014, retrying after 10068 ms, replay 2416 ops.
14/07/10 17:41:17 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2401 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56897 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:39:59 PDT 2014, retrying after 10064 ms, replay 2401 ops.
14/07/10 17:41:17 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 2429 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56897 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:39:59 PDT 2014, retrying after 10060 ms, replay 2429 ops.
2014-07-10 17:41:26:984 90 sec: 869481 operations; 0 current ops/sec;  
14/07/10 17:41:28 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 failed 2423 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1504, waitTime=2262, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:39:59 PDT 2014, retrying after 20171 ms, replay 2423 ops.
14/07/10 17:41:29 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 2397 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1522, waitTime=2092, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:39:59 PDT 2014, retrying after 20047 ms, replay 2397 ops.
14/07/10 17:41:29 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 failed 2401 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1522, waitTime=2092, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:39:59 PDT 2014, retrying after 20162 ms, replay 2401 ops.
14/07/10 17:41:29 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 2416 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1522, waitTime=2092, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:39:59 PDT 2014, retrying after 20117 ms, replay 2416 ops.
14/07/10 17:41:29 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 failed 2429 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1522, waitTime=2092, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:39:59 PDT 2014, retrying after 20174 ms, replay 2429 ops.
2014-07-10 17:41:36:985 100 sec: 1072761 operations; 20328 current ops/sec; [INSERT AverageLatency(us)=2874.97] 
14/07/10 17:41:41 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 3026 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56897 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:40:36 PDT 2014, retrying after 10030 ms, replay 3026 ops.
14/07/10 17:41:41 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 1873 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56897 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:40:39 PDT 2014, retrying after 10093 ms, replay 1873 ops.
14/07/10 17:41:41 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2411 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56897 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:40:38 PDT 2014, retrying after 10016 ms, replay 2411 ops.
2014-07-10 17:41:46:985 110 sec: 1095678 operations; 2291.47 current ops/sec; [INSERT AverageLatency(us)=418.46] 
14/07/10 17:41:54 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 1873 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56901 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:40:39 PDT 2014, retrying after 10004 ms, replay 1873 ops.
14/07/10 17:41:56 INFO client.AsyncProcess: #11, table=usertable, attempt=13/35 failed 2416 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56901 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:39:59 PDT 2014, retrying after 20004 ms, replay 2416 ops.
14/07/10 17:41:56 INFO client.AsyncProcess: #9, table=usertable, attempt=13/35 failed 2423 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56901 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:39:59 PDT 2014, retrying after 20186 ms, replay 2423 ops.
14/07/10 17:41:56 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2569 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56901 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:40:37 PDT 2014, retrying after 10051 ms, replay 2569 ops.
14/07/10 17:41:56 INFO client.AsyncProcess: #6, table=usertable, attempt=13/35 failed 2401 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56901 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:39:59 PDT 2014, retrying after 20021 ms, replay 2401 ops.
14/07/10 17:41:56 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 2411 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56901 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:40:38 PDT 2014, retrying after 10053 ms, replay 2411 ops.
14/07/10 17:41:56 INFO client.AsyncProcess: #1, table=usertable, attempt=13/35 failed 2429 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56901 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:39:59 PDT 2014, retrying after 20172 ms, replay 2429 ops.
14/07/10 17:41:56 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2183 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56901 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:40:40 PDT 2014, retrying after 10046 ms, replay 2183 ops.
14/07/10 17:41:56 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 3026 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56901 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:40:36 PDT 2014, retrying after 10019 ms, replay 3026 ops.
14/07/10 17:41:56 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 failed 2397 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56901 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:39:59 PDT 2014, retrying after 20016 ms, replay 2397 ops.
2014-07-10 17:41:56:985 120 sec: 1120934 operations; 2525.6 current ops/sec; [INSERT AverageLatency(us)=5249.03] 
2014-07-10 17:42:06:986 130 sec: 1120934 operations; 0 current ops/sec;  
2014-07-10 17:42:16:986 140 sec: 1120934 operations; 0 current ops/sec;  
14/07/10 17:42:19 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 failed 1873 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56903 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:40:39 PDT 2014, retrying after 20153 ms, replay 1873 ops.
14/07/10 17:42:19 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 3026 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56903 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:40:36 PDT 2014, retrying after 20065 ms, replay 3026 ops.
14/07/10 17:42:19 INFO client.AsyncProcess: #6, table=usertable, attempt=14/35 failed 2401 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56903 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:39:59 PDT 2014, retrying after 20144 ms, replay 2401 ops.
14/07/10 17:42:19 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2569 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56903 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:40:37 PDT 2014, retrying after 10082 ms, replay 2569 ops.
14/07/10 17:42:19 INFO client.AsyncProcess: #15, table=usertable, attempt=14/35 failed 2397 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56903 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:39:59 PDT 2014, retrying after 20032 ms, replay 2397 ops.
14/07/10 17:42:19 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2183 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56903 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:40:40 PDT 2014, retrying after 10089 ms, replay 2183 ops.
14/07/10 17:42:19 INFO client.AsyncProcess: #9, table=usertable, attempt=14/35 failed 2423 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56903 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:39:59 PDT 2014, retrying after 20151 ms, replay 2423 ops.
14/07/10 17:42:19 INFO client.AsyncProcess: #1, table=usertable, attempt=14/35 failed 2429 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56903 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:39:59 PDT 2014, retrying after 20015 ms, replay 2429 ops.
14/07/10 17:42:19 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 failed 2411 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56903 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:40:38 PDT 2014, retrying after 20044 ms, replay 2411 ops.
14/07/10 17:42:19 INFO client.AsyncProcess: #11, table=usertable, attempt=14/35 failed 2416 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56903 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:39:59 PDT 2014, retrying after 20138 ms, replay 2416 ops.
2014-07-10 17:42:26:987 150 sec: 1120934 operations; 0 current ops/sec;  
14/07/10 17:42:31 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 2183 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56903 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:40:40 PDT 2014, retrying after 20159 ms, replay 2183 ops.
14/07/10 17:42:31 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 failed 2569 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56903 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:40:37 PDT 2014, retrying after 20177 ms, replay 2569 ops.
2014-07-10 17:42:36:987 160 sec: 1120934 operations; 0 current ops/sec;  
14/07/10 17:42:39 INFO client.AsyncProcess: #15, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:39:59 PDT 2014
14/07/10 17:42:39 INFO client.AsyncProcess: #4, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:40:39 PDT 2014
14/07/10 17:42:39 INFO client.AsyncProcess: #1, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:39:59 PDT 2014
14/07/10 17:42:40 INFO client.AsyncProcess: #9, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:39:59 PDT 2014
14/07/10 17:42:40 INFO client.AsyncProcess: #13, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:40:38 PDT 2014
14/07/10 17:42:40 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:40:36 PDT 2014
14/07/10 17:42:40 INFO client.AsyncProcess: #6, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:39:59 PDT 2014
14/07/10 17:42:40 INFO client.AsyncProcess: #11, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:39:59 PDT 2014
2014-07-10 17:42:46:988 170 sec: 1245134 operations; 12418.76 current ops/sec; [INSERT AverageLatency(us)=11167.97] 
14/07/10 17:42:54 INFO client.AsyncProcess: #17, table=usertable, attempt=13/35 failed 2569 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2425, waitTime=2857, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:40:37 PDT 2014, retrying after 20194 ms, replay 2569 ops.
14/07/10 17:42:54 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 failed 2183 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2425, waitTime=2857, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:40:40 PDT 2014, retrying after 20188 ms, replay 2183 ops.
2014-07-10 17:42:56:988 180 sec: 1309370 operations; 6423.6 current ops/sec; [INSERT AverageLatency(us)=1510.08] 
14/07/10 17:42:59 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 1204 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2516, waitTime=2697, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:37 PDT 2014, retrying after 10044 ms, replay 1204 ops.
14/07/10 17:42:59 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 1466 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2516, waitTime=2697, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:35 PDT 2014, retrying after 10001 ms, replay 1466 ops.
14/07/10 17:42:59 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 1808 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2516, waitTime=2697, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:37 PDT 2014, retrying after 10058 ms, replay 1808 ops.
14/07/10 17:42:59 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 1914 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2516, waitTime=2697, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:37 PDT 2014, retrying after 10080 ms, replay 1914 ops.
14/07/10 17:42:59 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 1912 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2516, waitTime=2697, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:35 PDT 2014, retrying after 10093 ms, replay 1912 ops.
14/07/10 17:42:59 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2020 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2516, waitTime=2697, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:37 PDT 2014, retrying after 10006 ms, replay 2020 ops.
14/07/10 17:42:59 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2409 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2516, waitTime=2697, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:35 PDT 2014, retrying after 10004 ms, replay 2409 ops.
14/07/10 17:42:59 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 1345 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2516, waitTime=2697, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:35 PDT 2014, retrying after 10077 ms, replay 1345 ops.
14/07/10 17:42:59 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 146 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2516, waitTime=2697, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:37 PDT 2014, retrying after 10099 ms, replay 146 ops.
14/07/10 17:42:59 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 1998 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2516, waitTime=2697, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:35 PDT 2014, retrying after 10062 ms, replay 1998 ops.
14/07/10 17:42:59 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 1642 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2516, waitTime=2697, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:37 PDT 2014, retrying after 10077 ms, replay 1642 ops.
2014-07-10 17:43:06:989 190 sec: 1309370 operations; 0 current ops/sec;  
14/07/10 17:43:09 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:35 PDT 2014
14/07/10 17:43:09 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:37 PDT 2014
14/07/10 17:43:10 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:37 PDT 2014
14/07/10 17:43:10 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:37 PDT 2014
14/07/10 17:43:12 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 1642 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2656, waitTime=3268, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:37 PDT 2014, retrying after 10011 ms, replay 1642 ops.
14/07/10 17:43:12 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 1808 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2656, waitTime=3268, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:37 PDT 2014, retrying after 10026 ms, replay 1808 ops.
14/07/10 17:43:12 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:35 PDT 2014
14/07/10 17:43:12 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2409 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2656, waitTime=3268, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:35 PDT 2014, retrying after 10005 ms, replay 2409 ops.
14/07/10 17:43:12 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 1998 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2656, waitTime=3268, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:35 PDT 2014, retrying after 10049 ms, replay 1998 ops.
14/07/10 17:43:12 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 1345 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2656, waitTime=3268, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:35 PDT 2014, retrying after 10001 ms, replay 1345 ops.
14/07/10 17:43:12 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 failed 1914 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2656, waitTime=3268, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:37 PDT 2014, retrying after 10070 ms, replay 1914 ops.
14/07/10 17:43:16 INFO client.AsyncProcess: #17, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:40:37 PDT 2014
14/07/10 17:43:16 INFO client.AsyncProcess: #20, table=usertable, attempt=14/35 failed 2183 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2735, waitTime=2001, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:40:40 PDT 2014, retrying after 20069 ms, replay 2183 ops.
2014-07-10 17:43:16:989 200 sec: 1374751 operations; 6538.1 current ops/sec; [INSERT AverageLatency(us)=6191.11] 
14/07/10 17:43:24 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:35 PDT 2014
14/07/10 17:43:24 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 failed 1808 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2918, waitTime=2466, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:37 PDT 2014, retrying after 20055 ms, replay 1808 ops.
14/07/10 17:43:24 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 failed 2409 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2918, waitTime=2466, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:35 PDT 2014, retrying after 20099 ms, replay 2409 ops.
14/07/10 17:43:24 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 failed 1642 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2918, waitTime=2466, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:37 PDT 2014, retrying after 20189 ms, replay 1642 ops.
14/07/10 17:43:24 INFO client.AsyncProcess: #5, table=usertable, attempt=12/35 failed 1914 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2918, waitTime=2466, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:37 PDT 2014, retrying after 20021 ms, replay 1914 ops.
14/07/10 17:43:24 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 failed 1998 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2918, waitTime=2466, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:35 PDT 2014, retrying after 20124 ms, replay 1998 ops.
2014-07-10 17:43:26:990 210 sec: 1509560 operations; 13479.55 current ops/sec; [INSERT AverageLatency(us)=1440.75] 
2014-07-10 17:43:36:990 220 sec: 1564304 operations; 5474.4 current ops/sec; [INSERT AverageLatency(us)=4496.58] 
14/07/10 17:43:36 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 1582 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3167, waitTime=2038, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:43 PDT 2014, retrying after 10025 ms, replay 1582 ops.
14/07/10 17:43:36 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2006 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3172, waitTime=2000, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:44 PDT 2014, retrying after 10022 ms, replay 2006 ops.
14/07/10 17:43:37 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2077 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3179, waitTime=2368, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:43 PDT 2014, retrying after 10011 ms, replay 2077 ops.
14/07/10 17:43:38 INFO client.AsyncProcess: #20, table=usertable, attempt=15/35 failed 2183 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3188, waitTime=2020, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:40:40 PDT 2014, retrying after 20165 ms, replay 2183 ops.
14/07/10 17:43:39 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2111 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3206, waitTime=2202, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:47 PDT 2014, retrying after 10026 ms, replay 2111 ops.
14/07/10 17:43:39 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 1828 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3206, waitTime=2202, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:48 PDT 2014, retrying after 10020 ms, replay 1828 ops.
14/07/10 17:43:39 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 2527 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3206, waitTime=2202, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:47 PDT 2014, retrying after 10019 ms, replay 2527 ops.
14/07/10 17:43:39 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 1969 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3206, waitTime=2202, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:48 PDT 2014, retrying after 10068 ms, replay 1969 ops.
14/07/10 17:43:39 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2442 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3206, waitTime=2202, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:48 PDT 2014, retrying after 10047 ms, replay 2442 ops.
14/07/10 17:43:39 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 1944 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3206, waitTime=2202, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:48 PDT 2014, retrying after 10044 ms, replay 1944 ops.
14/07/10 17:43:45 INFO client.AsyncProcess: #8, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:37 PDT 2014
14/07/10 17:43:45 INFO client.AsyncProcess: #5, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:37 PDT 2014
14/07/10 17:43:46 INFO client.AsyncProcess: #8, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:37 PDT 2014
14/07/10 17:43:46 INFO client.AsyncProcess: #10, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:35 PDT 2014
2014-07-10 17:43:46:991 230 sec: 1693571 operations; 12925.41 current ops/sec; [INSERT AverageLatency(us)=2561.35] 
14/07/10 17:43:47 INFO client.AsyncProcess: #19, table=usertable, attempt=13/35 failed 2409 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3401, waitTime=2465, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:35 PDT 2014, retrying after 20131 ms, replay 2409 ops.
14/07/10 17:43:49 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2077 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3470, waitTime=2484, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:43 PDT 2014, retrying after 10020 ms, replay 2077 ops.
14/07/10 17:43:49 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 2006 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3470, waitTime=2484, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:44 PDT 2014, retrying after 10090 ms, replay 2006 ops.
14/07/10 17:43:49 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 1582 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3470, waitTime=2484, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:43 PDT 2014, retrying after 10047 ms, replay 1582 ops.
14/07/10 17:43:51 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 2527 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3492, waitTime=2370, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:47 PDT 2014, retrying after 10027 ms, replay 2527 ops.
14/07/10 17:43:51 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2111 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3492, waitTime=2370, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:47 PDT 2014, retrying after 10088 ms, replay 2111 ops.
14/07/10 17:43:51 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 1944 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3492, waitTime=2370, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:48 PDT 2014, retrying after 10086 ms, replay 1944 ops.
14/07/10 17:43:51 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 1828 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3492, waitTime=2370, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:48 PDT 2014, retrying after 10090 ms, replay 1828 ops.
14/07/10 17:43:51 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2442 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3492, waitTime=2370, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:48 PDT 2014, retrying after 10056 ms, replay 2442 ops.
14/07/10 17:43:51 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 1969 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3492, waitTime=2370, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:48 PDT 2014, retrying after 10042 ms, replay 1969 ops.
2014-07-10 17:43:56:991 240 sec: 1729859 operations; 3628.8 current ops/sec; [INSERT AverageLatency(us)=704.19] 
14/07/10 17:44:01 INFO client.AsyncProcess: #20, table=usertable, attempt=16/35 failed 2183 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3654, waitTime=2713, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:40:40 PDT 2014, retrying after 20178 ms, replay 2183 ops.
14/07/10 17:44:01 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 2077 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3676, waitTime=2066, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:43 PDT 2014, retrying after 20111 ms, replay 2077 ops.
14/07/10 17:44:01 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:43 PDT 2014
14/07/10 17:44:01 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 failed 2006 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3679, waitTime=2290, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:44 PDT 2014, retrying after 20008 ms, replay 2006 ops.
14/07/10 17:44:03 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:47 PDT 2014
14/07/10 17:44:03 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:48 PDT 2014
14/07/10 17:44:03 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:48 PDT 2014
14/07/10 17:44:03 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:48 PDT 2014
14/07/10 17:44:03 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 2442 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3719, waitTime=2050, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:48 PDT 2014, retrying after 20019 ms, replay 2442 ops.
14/07/10 17:44:03 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 failed 2111 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3719, waitTime=2050, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:47 PDT 2014, retrying after 20091 ms, replay 2111 ops.
2014-07-10 17:44:06:992 250 sec: 1843206 operations; 11334.7 current ops/sec; [INSERT AverageLatency(us)=1465.04] 
14/07/10 17:44:10 INFO client.AsyncProcess: #19, table=usertable, attempt=14/35 failed 2409 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3901, waitTime=3263, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:35 PDT 2014, retrying after 20190 ms, replay 2409 ops.
14/07/10 17:44:13 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2440 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3988, waitTime=2066, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:22 PDT 2014, retrying after 10088 ms, replay 2440 ops.
14/07/10 17:44:13 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2084 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3988, waitTime=2066, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:22 PDT 2014, retrying after 10081 ms, replay 2084 ops.
14/07/10 17:44:14 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2489 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4026, waitTime=2094, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:23 PDT 2014, retrying after 10004 ms, replay 2489 ops.
14/07/10 17:44:14 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2422 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4026, waitTime=2094, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:24 PDT 2014, retrying after 10037 ms, replay 2422 ops.
14/07/10 17:44:14 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2108 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4026, waitTime=2094, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:23 PDT 2014, retrying after 10022 ms, replay 2108 ops.
2014-07-10 17:44:16:992 260 sec: 2003075 operations; 15985.3 current ops/sec; [INSERT AverageLatency(us)=388.64] 
14/07/10 17:44:22 INFO client.AsyncProcess: #9, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:44 PDT 2014
14/07/10 17:44:23 INFO client.AsyncProcess: #20, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:40:40 PDT 2014
14/07/10 17:44:23 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 failed 2077 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4241, waitTime=2054, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:43 PDT 2014, retrying after 20181 ms, replay 2077 ops.
14/07/10 17:44:25 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2440 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4256, waitTime=2470, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:22 PDT 2014, retrying after 10095 ms, replay 2440 ops.
14/07/10 17:44:25 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2084 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4256, waitTime=2470, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:22 PDT 2014, retrying after 10088 ms, replay 2084 ops.
14/07/10 17:44:26 INFO client.AsyncProcess: #6, table=usertable, attempt=13/35 failed 2111 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4275, waitTime=2467, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:47 PDT 2014, retrying after 20066 ms, replay 2111 ops.
14/07/10 17:44:26 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 failed 2442 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4275, waitTime=2467, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:48 PDT 2014, retrying after 20065 ms, replay 2442 ops.
14/07/10 17:44:26 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 2108 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4297, waitTime=2601, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:23 PDT 2014, retrying after 10074 ms, replay 2108 ops.
14/07/10 17:44:26 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 2422 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4297, waitTime=2601, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:24 PDT 2014, retrying after 10003 ms, replay 2422 ops.
14/07/10 17:44:26 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2489 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4297, waitTime=2601, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:23 PDT 2014, retrying after 10069 ms, replay 2489 ops.
2014-07-10 17:44:26:992 270 sec: 2199829 operations; 19675.4 current ops/sec; [INSERT AverageLatency(us)=1732.78] 
14/07/10 17:44:33 INFO client.AsyncProcess: #19, table=usertable, attempt=15/35 failed 2409 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4444, waitTime=2030, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:35 PDT 2014, retrying after 20185 ms, replay 2409 ops.
2014-07-10 17:44:36:993 280 sec: 2492466 operations; 29260.77 current ops/sec; [INSERT AverageLatency(us)=307.95] 
14/07/10 17:44:37 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2037 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4570, waitTime=2255, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:46 PDT 2014, retrying after 10020 ms, replay 2037 ops.
14/07/10 17:44:37 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 2055 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4570, waitTime=2255, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:45 PDT 2014, retrying after 10088 ms, replay 2055 ops.
14/07/10 17:44:37 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2705 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4580, waitTime=2252, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:46 PDT 2014, retrying after 10072 ms, replay 2705 ops.
14/07/10 17:44:37 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 2440 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4580, waitTime=2252, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:22 PDT 2014, retrying after 20009 ms, replay 2440 ops.
14/07/10 17:44:37 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 failed 2084 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4580, waitTime=2252, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:22 PDT 2014, retrying after 20012 ms, replay 2084 ops.
14/07/10 17:44:38 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 2422 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4623, waitTime=2254, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:24 PDT 2014, retrying after 20179 ms, replay 2422 ops.
14/07/10 17:44:39 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2179 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4634, waitTime=2069, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:47 PDT 2014, retrying after 10005 ms, replay 2179 ops.
14/07/10 17:44:39 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 2108 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4634, waitTime=2069, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:23 PDT 2014, retrying after 20050 ms, replay 2108 ops.
14/07/10 17:44:39 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 2489 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4634, waitTime=2069, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:23 PDT 2014, retrying after 20026 ms, replay 2489 ops.
14/07/10 17:44:46 INFO client.AsyncProcess: #15, table=usertable, attempt=14/35 failed 2077 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4758, waitTime=2175, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:43 PDT 2014, retrying after 20089 ms, replay 2077 ops.
2014-07-10 17:44:46:993 290 sec: 2500563 operations; 809.7 current ops/sec; [INSERT AverageLatency(us)=424.53] 
14/07/10 17:44:48 INFO client.AsyncProcess: #6, table=usertable, attempt=14/35 failed 2111 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4778, waitTime=2196, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:47 PDT 2014, retrying after 20100 ms, replay 2111 ops.
14/07/10 17:44:48 INFO client.AsyncProcess: #15, table=usertable, attempt=14/35 failed 2442 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4778, waitTime=2196, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:48 PDT 2014, retrying after 20178 ms, replay 2442 ops.
14/07/10 17:44:48 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:46 PDT 2014
14/07/10 17:44:48 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:45 PDT 2014
14/07/10 17:44:49 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:46 PDT 2014
14/07/10 17:44:49 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:47 PDT 2014
14/07/10 17:44:55 INFO client.AsyncProcess: #19, table=usertable, attempt=16/35 failed 2409 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4923, waitTime=2238, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:35 PDT 2014, retrying after 20110 ms, replay 2409 ops.
2014-07-10 17:44:56:994 300 sec: 2612195 operations; 11162.08 current ops/sec; [INSERT AverageLatency(us)=3416.59] 
14/07/10 17:44:58 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2414 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4994, waitTime=2011, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:44:07 PDT 2014, retrying after 10024 ms, replay 2414 ops.
14/07/10 17:44:59 INFO client.AsyncProcess: #17, table=usertable, attempt=13/35 failed 2084 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5024, waitTime=2078, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:22 PDT 2014, retrying after 20030 ms, replay 2084 ops.
14/07/10 17:44:59 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 failed 2440 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5024, waitTime=2078, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:22 PDT 2014, retrying after 20190 ms, replay 2440 ops.
14/07/10 17:45:01 INFO client.AsyncProcess: #11, table=usertable, attempt=13/35 failed 2422 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5088, waitTime=2262, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:24 PDT 2014, retrying after 20100 ms, replay 2422 ops.
14/07/10 17:45:01 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 failed 2489 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5088, waitTime=2262, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:23 PDT 2014, retrying after 20092 ms, replay 2489 ops.
14/07/10 17:45:01 INFO client.AsyncProcess: #11, table=usertable, attempt=13/35 failed 2108 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5088, waitTime=2262, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:23 PDT 2014, retrying after 20181 ms, replay 2108 ops.
2014-07-10 17:45:06:995 310 sec: 2740295 operations; 12810 current ops/sec; [INSERT AverageLatency(us)=515.6] 
14/07/10 17:45:07 INFO client.AsyncProcess: #15, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:43 PDT 2014
14/07/10 17:45:11 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 2414 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5363, waitTime=3114, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:44:07 PDT 2014, retrying after 10011 ms, replay 2414 ops.
14/07/10 17:45:11 INFO client.AsyncProcess: #6, table=usertable, attempt=15/35 failed 2111 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5363, waitTime=3114, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:47 PDT 2014, retrying after 20083 ms, replay 2111 ops.
14/07/10 17:45:11 INFO client.AsyncProcess: #15, table=usertable, attempt=15/35 failed 2442 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5363, waitTime=3114, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:48 PDT 2014, retrying after 20145 ms, replay 2442 ops.
2014-07-10 17:45:16:995 320 sec: 2867369 operations; 12706.13 current ops/sec; [INSERT AverageLatency(us)=348.65] 
14/07/10 17:45:18 INFO client.AsyncProcess: #19, table=usertable, attempt=17/35 failed 2409 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5538, waitTime=2468, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:35 PDT 2014, retrying after 20040 ms, replay 2409 ops.
14/07/10 17:45:21 INFO client.AsyncProcess: #2, table=usertable, attempt=14/35 failed 2440 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5617, waitTime=2170, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:22 PDT 2014, retrying after 20083 ms, replay 2440 ops.
14/07/10 17:45:21 INFO client.AsyncProcess: #17, table=usertable, attempt=14/35 failed 2084 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5617, waitTime=2170, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:22 PDT 2014, retrying after 20165 ms, replay 2084 ops.
14/07/10 17:45:23 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 failed 2414 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5641, waitTime=2108, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:44:07 PDT 2014, retrying after 20116 ms, replay 2414 ops.
14/07/10 17:45:23 INFO client.AsyncProcess: #2, table=usertable, attempt=14/35 failed 2489 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5642, waitTime=2004, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:23 PDT 2014, retrying after 20003 ms, replay 2489 ops.
14/07/10 17:45:23 INFO client.AsyncProcess: #11, table=usertable, attempt=14/35 failed 2422 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5642, waitTime=2004, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:24 PDT 2014, retrying after 20099 ms, replay 2422 ops.
14/07/10 17:45:23 INFO client.AsyncProcess: #11, table=usertable, attempt=14/35 failed 2108 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5648, waitTime=2117, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:23 PDT 2014, retrying after 20066 ms, replay 2108 ops.
2014-07-10 17:45:27:083 330 sec: 2890398 operations; 2282.81 current ops/sec; [INSERT AverageLatency(us)=4529.51] 
14/07/10 17:45:32 INFO client.AsyncProcess: #15, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:48 PDT 2014
14/07/10 17:45:32 INFO client.AsyncProcess: #6, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:42:47 PDT 2014
2014-07-10 17:45:37:155 340 sec: 3070424 operations; 17873.91 current ops/sec; [INSERT AverageLatency(us)=2413.64] 
14/07/10 17:45:39 INFO client.AsyncProcess: #19, table=usertable, attempt=18/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:41:35 PDT 2014
14/07/10 17:45:41 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2459 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6073, waitTime=2003, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:44:50 PDT 2014, retrying after 10066 ms, replay 2459 ops.
14/07/10 17:45:42 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2445 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6087, waitTime=2166, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:44:50 PDT 2014, retrying after 10069 ms, replay 2445 ops.
14/07/10 17:45:44 INFO client.AsyncProcess: #17, table=usertable, attempt=15/35 failed 2084 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6126, waitTime=2256, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:22 PDT 2014, retrying after 20049 ms, replay 2084 ops.
14/07/10 17:45:44 INFO client.AsyncProcess: #2, table=usertable, attempt=15/35 failed 2440 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6126, waitTime=2256, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:22 PDT 2014, retrying after 20167 ms, replay 2440 ops.
14/07/10 17:45:45 INFO client.AsyncProcess: #11, table=usertable, attempt=15/35 failed 2422 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6169, waitTime=2173, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:24 PDT 2014, retrying after 20083 ms, replay 2422 ops.
14/07/10 17:45:45 INFO client.AsyncProcess: #2, table=usertable, attempt=15/35 failed 2489 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6169, waitTime=2173, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:23 PDT 2014, retrying after 20125 ms, replay 2489 ops.
14/07/10 17:45:45 INFO client.AsyncProcess: #8, table=usertable, attempt=13/35 failed 2414 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6169, waitTime=2173, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:44:07 PDT 2014, retrying after 20062 ms, replay 2414 ops.
14/07/10 17:45:45 INFO client.AsyncProcess: #11, table=usertable, attempt=15/35 failed 2108 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6174, waitTime=2292, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:23 PDT 2014, retrying after 20067 ms, replay 2108 ops.
2014-07-10 17:45:47:155 350 sec: 3338494 operations; 26807 current ops/sec; [INSERT AverageLatency(us)=1522.29] 
14/07/10 17:45:54 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2459 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6355, waitTime=2350, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:44:50 PDT 2014, retrying after 10051 ms, replay 2459 ops.
14/07/10 17:45:54 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2445 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6373, waitTime=2206, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:44:50 PDT 2014, retrying after 10020 ms, replay 2445 ops.
2014-07-10 17:45:57:155 360 sec: 3530329 operations; 19183.5 current ops/sec; [INSERT AverageLatency(us)=655.58] 
14/07/10 17:45:59 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2440 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6491, waitTime=2268, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:08 PDT 2014, retrying after 10086 ms, replay 2440 ops.
14/07/10 17:45:59 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 1975 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6491, waitTime=2268, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:10 PDT 2014, retrying after 10054 ms, replay 1975 ops.
14/07/10 17:45:59 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2190 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6491, waitTime=2268, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:08 PDT 2014, retrying after 10059 ms, replay 2190 ops.
14/07/10 17:46:01 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 1896 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6524, waitTime=3197, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:10 PDT 2014, retrying after 10045 ms, replay 1896 ops.
14/07/10 17:46:01 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 1265 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6524, waitTime=3197, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:10 PDT 2014, retrying after 10097 ms, replay 1265 ops.
14/07/10 17:46:06 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 2445 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6662, waitTime=2539, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:44:50 PDT 2014, retrying after 20119 ms, replay 2445 ops.
14/07/10 17:46:06 INFO client.AsyncProcess: #2, table=usertable, attempt=16/35 failed 2440 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6662, waitTime=2539, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:22 PDT 2014, retrying after 20160 ms, replay 2440 ops.
14/07/10 17:46:06 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 2459 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6662, waitTime=2539, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:44:50 PDT 2014, retrying after 20179 ms, replay 2459 ops.
14/07/10 17:46:06 INFO client.AsyncProcess: #17, table=usertable, attempt=16/35 failed 2084 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6662, waitTime=2539, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:22 PDT 2014, retrying after 20019 ms, replay 2084 ops.
2014-07-10 17:46:07:156 370 sec: 3691195 operations; 16084.99 current ops/sec; [INSERT AverageLatency(us)=879.82] 
14/07/10 17:46:08 INFO client.AsyncProcess: #11, table=usertable, attempt=16/35 failed 2422 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6691, waitTime=2490, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:24 PDT 2014, retrying after 20129 ms, replay 2422 ops.
14/07/10 17:46:08 INFO client.AsyncProcess: #8, table=usertable, attempt=14/35 failed 2414 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6691, waitTime=2490, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:44:07 PDT 2014, retrying after 20095 ms, replay 2414 ops.
14/07/10 17:46:08 INFO client.AsyncProcess: #11, table=usertable, attempt=16/35 failed 2108 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6691, waitTime=2490, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:23 PDT 2014, retrying after 20065 ms, replay 2108 ops.
14/07/10 17:46:08 INFO client.AsyncProcess: #2, table=usertable, attempt=16/35 failed 2489 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6691, waitTime=2490, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:23 PDT 2014, retrying after 20018 ms, replay 2489 ops.
14/07/10 17:46:12 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 1975 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6797, waitTime=2006, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:10 PDT 2014, retrying after 10042 ms, replay 1975 ops.
14/07/10 17:46:12 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 2190 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6797, waitTime=2006, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:08 PDT 2014, retrying after 10059 ms, replay 2190 ops.
14/07/10 17:46:12 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2440 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6799, waitTime=2358, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:08 PDT 2014, retrying after 10095 ms, replay 2440 ops.
14/07/10 17:46:13 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 1896 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6808, waitTime=2347, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:10 PDT 2014, retrying after 10043 ms, replay 1896 ops.
14/07/10 17:46:13 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 1265 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6808, waitTime=2347, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:10 PDT 2014, retrying after 10079 ms, replay 1265 ops.
2014-07-10 17:46:17:157 380 sec: 3691195 operations; 0 current ops/sec;  
14/07/10 17:46:22 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:10 PDT 2014
14/07/10 17:46:22 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:08 PDT 2014
14/07/10 17:46:23 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:08 PDT 2014
14/07/10 17:46:26 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 failed 1896 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6980, waitTime=3292, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:10 PDT 2014, retrying after 20143 ms, replay 1896 ops.
14/07/10 17:46:26 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 failed 1265 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6980, waitTime=3292, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:10 PDT 2014, retrying after 20028 ms, replay 1265 ops.
2014-07-10 17:46:27:167 390 sec: 3738074 operations; 4682.75 current ops/sec; [INSERT AverageLatency(us)=5702.5] 
14/07/10 17:46:28 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 failed 2445 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7037, waitTime=2118, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:44:50 PDT 2014, retrying after 20086 ms, replay 2445 ops.
14/07/10 17:46:28 INFO client.AsyncProcess: #17, table=usertable, attempt=17/35 failed 2084 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7037, waitTime=2118, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:22 PDT 2014, retrying after 20174 ms, replay 2084 ops.
14/07/10 17:46:28 INFO client.AsyncProcess: #2, table=usertable, attempt=17/35 failed 2440 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7045, waitTime=2130, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:22 PDT 2014, retrying after 20123 ms, replay 2440 ops.
14/07/10 17:46:28 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 failed 2459 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7045, waitTime=2130, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:44:50 PDT 2014, retrying after 20039 ms, replay 2459 ops.
14/07/10 17:46:29 INFO client.AsyncProcess: #2, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:23 PDT 2014
14/07/10 17:46:29 INFO client.AsyncProcess: #8, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:44:07 PDT 2014
14/07/10 17:46:29 INFO client.AsyncProcess: #11, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:23 PDT 2014
14/07/10 17:46:29 INFO client.AsyncProcess: #11, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:24 PDT 2014
2014-07-10 17:46:37:167 400 sec: 4009787 operations; 27171.3 current ops/sec; [INSERT AverageLatency(us)=1492.74] 
14/07/10 17:46:46 INFO client.AsyncProcess: #1, table=usertable, attempt=13/35 failed 1265 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: java.io.IOException: The stream is closed on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:10 PDT 2014, retrying after 20004 ms, replay 1265 ops.
14/07/10 17:46:46 INFO client.AsyncProcess: #14, table=usertable, attempt=13/35 failed 1896 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: java.io.IOException: The stream is closed on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:10 PDT 2014, retrying after 20128 ms, replay 1896 ops.
2014-07-10 17:46:47:168 410 sec: 4009787 operations; 0 current ops/sec;  
14/07/10 17:46:47 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2669 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: java.io.IOException: The stream is closed on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:57 PDT 2014, retrying after 10053 ms, replay 2669 ops.
14/07/10 17:46:47 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2430 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: java.io.IOException: The stream is closed on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:58 PDT 2014, retrying after 10092 ms, replay 2430 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 1623 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56906 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014, retrying after 10083 ms, replay 1623 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #2, table=usertable, attempt=18/35 failed 2440 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:22 PDT 2014, retrying after 20155 ms, replay 2440 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #20, table=usertable, attempt=14/35 failed 2459 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:44:50 PDT 2014, retrying after 20067 ms, replay 2459 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #17, table=usertable, attempt=18/35 failed 2084 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:22 PDT 2014, retrying after 20179 ms, replay 2084 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #20, table=usertable, attempt=14/35 failed 2445 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:44:50 PDT 2014, retrying after 20104 ms, replay 2445 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 2399 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:58 PDT 2014, retrying after 10007 ms, replay 2399 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 1707 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:58 PDT 2014, retrying after 10068 ms, replay 1707 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2058 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:59 PDT 2014, retrying after 10004 ms, replay 2058 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 978 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014, retrying after 10029 ms, replay 978 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 1175 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:59 PDT 2014, retrying after 10074 ms, replay 1175 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 1308 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:58 PDT 2014, retrying after 10027 ms, replay 1308 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 1154 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:01 PDT 2014, retrying after 10024 ms, replay 1154 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 457 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:01 PDT 2014, retrying after 10090 ms, replay 457 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 1660 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:59 PDT 2014, retrying after 10037 ms, replay 1660 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 1108 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014, retrying after 10026 ms, replay 1108 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2047 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:59 PDT 2014, retrying after 10022 ms, replay 2047 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 1568 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014, retrying after 10000 ms, replay 1568 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 1304 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:58 PDT 2014, retrying after 10056 ms, replay 1304 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 1295 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:59 PDT 2014, retrying after 10039 ms, replay 1295 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 1503 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:59 PDT 2014, retrying after 10079 ms, replay 1503 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 2071 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014, retrying after 10017 ms, replay 2071 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2034 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:59 PDT 2014, retrying after 10049 ms, replay 2034 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 401 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014, retrying after 10052 ms, replay 401 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 988 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:01 PDT 2014, retrying after 10092 ms, replay 988 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 1775 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:01 PDT 2014, retrying after 10046 ms, replay 1775 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 702 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:02 PDT 2014, retrying after 10040 ms, replay 702 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 1196 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014, retrying after 10018 ms, replay 1196 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 1934 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014, retrying after 10072 ms, replay 1934 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 1118 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:59 PDT 2014, retrying after 10029 ms, replay 1118 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 198 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014, retrying after 10087 ms, replay 198 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 1162 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014, retrying after 10043 ms, replay 1162 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 791 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56906 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014, retrying after 10027 ms, replay 791 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 525 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56906 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014, retrying after 10045 ms, replay 525 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 150 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56906 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:01 PDT 2014, retrying after 10098 ms, replay 150 ops.
14/07/10 17:46:50 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 285 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56906 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014, retrying after 10092 ms, replay 285 ops.
2014-07-10 17:46:57:168 420 sec: 4009787 operations; 0 current ops/sec;  
14/07/10 17:46:58 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:57 PDT 2014
14/07/10 17:46:58 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:58 PDT 2014
14/07/10 17:47:01 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014
14/07/10 17:47:01 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:59 PDT 2014
14/07/10 17:47:01 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:59 PDT 2014
14/07/10 17:47:01 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014
14/07/10 17:47:01 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:59 PDT 2014
14/07/10 17:47:01 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014
14/07/10 17:47:01 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014
14/07/10 17:47:01 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014
14/07/10 17:47:01 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014
14/07/10 17:47:01 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:58 PDT 2014
14/07/10 17:47:02 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:59 PDT 2014
14/07/10 17:47:02 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:01 PDT 2014
14/07/10 17:47:02 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014
14/07/10 17:47:02 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:59 PDT 2014
14/07/10 17:47:02 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 2399 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7721, waitTime=2007, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:58 PDT 2014, retrying after 10034 ms, replay 2399 ops.
14/07/10 17:47:03 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 525 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7748, waitTime=2487, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014, retrying after 10065 ms, replay 525 ops.
14/07/10 17:47:03 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 198 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7748, waitTime=2487, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014, retrying after 10080 ms, replay 198 ops.
14/07/10 17:47:03 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 457 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7748, waitTime=2487, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:01 PDT 2014, retrying after 10022 ms, replay 457 ops.
14/07/10 17:47:03 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 702 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7748, waitTime=2487, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:02 PDT 2014, retrying after 10062 ms, replay 702 ops.
14/07/10 17:47:03 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 150 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7748, waitTime=2487, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:01 PDT 2014, retrying after 10091 ms, replay 150 ops.
14/07/10 17:47:03 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 988 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7748, waitTime=2487, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:01 PDT 2014, retrying after 10081 ms, replay 988 ops.
14/07/10 17:47:03 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 1175 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7748, waitTime=2487, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:59 PDT 2014, retrying after 10041 ms, replay 1175 ops.
14/07/10 17:47:03 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 401 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7748, waitTime=2487, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014, retrying after 10068 ms, replay 401 ops.
14/07/10 17:47:03 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 1304 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7748, waitTime=2487, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:58 PDT 2014, retrying after 10046 ms, replay 1304 ops.
14/07/10 17:47:03 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 1707 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7748, waitTime=2487, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:58 PDT 2014, retrying after 10022 ms, replay 1707 ops.
14/07/10 17:47:03 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 2034 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7748, waitTime=2487, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:59 PDT 2014, retrying after 10060 ms, replay 2034 ops.
14/07/10 17:47:03 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 1934 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7748, waitTime=2487, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014, retrying after 10003 ms, replay 1934 ops.
14/07/10 17:47:03 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 1162 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7748, waitTime=2487, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014, retrying after 10054 ms, replay 1162 ops.
14/07/10 17:47:03 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 285 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7748, waitTime=2487, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014, retrying after 10074 ms, replay 285 ops.
14/07/10 17:47:03 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 failed 1503 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7748, waitTime=2487, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:59 PDT 2014, retrying after 10055 ms, replay 1503 ops.
14/07/10 17:47:03 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 1775 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7748, waitTime=2487, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:01 PDT 2014, retrying after 10076 ms, replay 1775 ops.
14/07/10 17:47:07 INFO client.AsyncProcess: #1, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:10 PDT 2014
2014-07-10 17:47:07:169 430 sec: 4214377 operations; 20456.95 current ops/sec; [INSERT AverageLatency(us)=3296.03] 
14/07/10 17:47:08 INFO client.AsyncProcess: #14, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:10 PDT 2014
14/07/10 17:47:12 INFO client.AsyncProcess: #20, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:44:50 PDT 2014
14/07/10 17:47:12 INFO client.AsyncProcess: #20, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:44:50 PDT 2014
14/07/10 17:47:13 INFO client.AsyncProcess: #17, table=usertable, attempt=19/35 failed 2084 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8192, waitTime=2699, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:22 PDT 2014, retrying after 20024 ms, replay 2084 ops.
14/07/10 17:47:13 INFO client.AsyncProcess: #2, table=usertable, attempt=19/35 failed 2440 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8192, waitTime=2699, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:22 PDT 2014, retrying after 20164 ms, replay 2440 ops.
14/07/10 17:47:13 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:01 PDT 2014
14/07/10 17:47:14 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014
14/07/10 17:47:14 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014
14/07/10 17:47:14 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014
14/07/10 17:47:14 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:01 PDT 2014
14/07/10 17:47:14 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014
14/07/10 17:47:14 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:01 PDT 2014
14/07/10 17:47:14 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014
14/07/10 17:47:14 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:01 PDT 2014
14/07/10 17:47:14 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:59 PDT 2014
14/07/10 17:47:14 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:58 PDT 2014
14/07/10 17:47:14 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:02 PDT 2014
14/07/10 17:47:15 INFO client.AsyncProcess: #5, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:59 PDT 2014
14/07/10 17:47:15 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 failed 2399 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8273, waitTime=3168, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:58 PDT 2014, retrying after 20113 ms, replay 2399 ops.
14/07/10 17:47:15 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 failed 1707 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8273, waitTime=3168, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:58 PDT 2014, retrying after 20118 ms, replay 1707 ops.
14/07/10 17:47:15 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 failed 2034 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8273, waitTime=3168, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:59 PDT 2014, retrying after 20190 ms, replay 2034 ops.
14/07/10 17:47:15 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 failed 1934 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8273, waitTime=3168, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014, retrying after 20193 ms, replay 1934 ops.
2014-07-10 17:47:17:169 440 sec: 4592477 operations; 37810 current ops/sec; [UPDATE AverageLatency(us)=1733991] [INSERT AverageLatency(us)=1017.06] [CLEANUP AverageLatency(us)=1734147] 
2014-07-10 17:47:27:170 450 sec: 4676788 operations; 8430.26 current ops/sec;  [INSERT AverageLatency(us)=468.1]  
14/07/10 17:47:35 INFO client.AsyncProcess: #17, table=usertable, attempt=20/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:22 PDT 2014
14/07/10 17:47:35 INFO client.AsyncProcess: #2, table=usertable, attempt=20/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:43:22 PDT 2014
2014-07-10 17:47:37:170 460 sec: 4797562 operations; 12077.4 current ops/sec;  [INSERT AverageLatency(us)=5914.44]  
14/07/10 17:47:38 INFO client.AsyncProcess: #9, table=usertable, attempt=13/35 failed 2034 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8899, waitTime=2228, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:59 PDT 2014, retrying after 20107 ms, replay 2034 ops.
14/07/10 17:47:38 INFO client.AsyncProcess: #7, table=usertable, attempt=13/35 failed 1707 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8899, waitTime=2228, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:58 PDT 2014, retrying after 20094 ms, replay 1707 ops.
14/07/10 17:47:38 INFO client.AsyncProcess: #9, table=usertable, attempt=13/35 failed 1934 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8899, waitTime=2228, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014, retrying after 20087 ms, replay 1934 ops.
14/07/10 17:47:38 INFO client.AsyncProcess: #12, table=usertable, attempt=13/35 failed 2399 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8899, waitTime=2228, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:58 PDT 2014, retrying after 20002 ms, replay 2399 ops.
2014-07-10 17:47:47:171 470 sec: 5217354 operations; 41979.2 current ops/sec;  [INSERT AverageLatency(us)=478.71]  
2014-07-10 17:47:57:171 480 sec: 5271374 operations; 5401.46 current ops/sec;  [INSERT AverageLatency(us)=2007.86]  
14/07/10 17:47:59 INFO client.AsyncProcess: #9, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:46:00 PDT 2014
14/07/10 17:47:59 INFO client.AsyncProcess: #7, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:58 PDT 2014
14/07/10 17:48:00 INFO client.AsyncProcess: #12, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:58 PDT 2014
14/07/10 17:48:01 INFO client.AsyncProcess: #9, table=usertable, attempt=14/35 failed 2034 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=9711, waitTime=2765, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:59 PDT 2014, retrying after 20014 ms, replay 2034 ops.
2014-07-10 17:48:07:172 490 sec: 5460957 operations; 18956.4 current ops/sec;  [INSERT AverageLatency(us)=1949.44]  
2014-07-10 17:48:17:172 500 sec: 5508224 operations; 4726.7 current ops/sec;  [INSERT AverageLatency(us)=916.97]  
14/07/10 17:48:23 INFO client.AsyncProcess: #9, table=usertable, attempt=15/35 failed 2034 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=10295, waitTime=2153, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:59 PDT 2014, retrying after 20049 ms, replay 2034 ops.
2014-07-10 17:48:27:173 510 sec: 5560453 operations; 5222.38 current ops/sec;  [INSERT AverageLatency(us)=3564.37]  
14/07/10 17:48:33 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 1915 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56907 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:47:41 PDT 2014, retrying after 10044 ms, replay 1915 ops.
2014-07-10 17:48:37:173 520 sec: 5560453 operations; 0 current ops/sec;    
14/07/10 17:48:44 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:47:41 PDT 2014
14/07/10 17:48:44 INFO client.AsyncProcess: #9, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:45:59 PDT 2014
2014-07-10 17:48:47:174 530 sec: 5716734 operations; 15628.1 current ops/sec;  [INSERT AverageLatency(us)=2453.02]  
14/07/10 17:48:51 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2038 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=10779, waitTime=2024, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:47:59 PDT 2014, retrying after 10030 ms, replay 2038 ops.
2014-07-10 17:48:57:174 540 sec: 5939038 operations; 22228.18 current ops/sec;  [INSERT AverageLatency(us)=960.55]  
14/07/10 17:49:04 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:47:59 PDT 2014
2014-07-10 17:49:07:175 550 sec: 6279789 operations; 34075.1 current ops/sec;  [INSERT AverageLatency(us)=992.99]  
2014-07-10 17:49:17:175 560 sec: 6389946 operations; 11014.6 current ops/sec;  [INSERT AverageLatency(us)=794.71]  
2014-07-10 17:49:27:176 570 sec: 6663836 operations; 27386.26 current ops/sec;  [INSERT AverageLatency(us)=612.14]  
2014-07-10 17:49:37:176 580 sec: 7027464 operations; 36362.8 current ops/sec;  [INSERT AverageLatency(us)=349.15]  
2014-07-10 17:49:47:177 590 sec: 7380938 operations; 35343.87 current ops/sec; [UPDATE AverageLatency(us)=3867173] [INSERT AverageLatency(us)=891.83] [CLEANUP AverageLatency(us)=3867828] 
14/07/10 17:49:55 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 2474 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=12585, waitTime=2093, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:49:03 PDT 2014, retrying after 10010 ms, replay 2474 ops.
14/07/10 17:49:55 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2428 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=12585, waitTime=2093, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:49:04 PDT 2014, retrying after 10050 ms, replay 2428 ops.
2014-07-10 17:49:57:177 600 sec: 7470566 operations; 8962.8 current ops/sec;  [INSERT AverageLatency(us)=1227.55]  
14/07/10 17:50:06 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:49:04 PDT 2014
14/07/10 17:50:06 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405067256624, tracking started Thu Jul 10 17:49:03 PDT 2014
2014-07-10 17:50:07:178 610 sec: 7933666 operations; 46305.37 current ops/sec; [UPDATE AverageLatency(us)=2496308.5] [INSERT AverageLatency(us)=707.56] [CLEANUP AverageLatency(us)=2496320] 
2014-07-10 17:50:17:178 620 sec: 8297179 operations; 36351.3 current ops/sec; [UPDATE AverageLatency(us)=5063103] [INSERT AverageLatency(us)=359.98] [CLEANUP AverageLatency(us)=5063115] 
2014-07-10 17:50:27:179 630 sec: 8565790 operations; 26858.41 current ops/sec; [UPDATE AverageLatency(us)=5348116] [INSERT AverageLatency(us)=443.24] [CLEANUP AverageLatency(us)=5348128.5] 
2014-07-10 17:50:37:180 640 sec: 8679811 operations; 11400.96 current ops/sec;  [INSERT AverageLatency(us)=560.23]  
2014-07-10 17:50:47:180 650 sec: 8919932 operations; 24012.1 current ops/sec;  [INSERT AverageLatency(us)=565.04]  
2014-07-10 17:50:57:181 660 sec: 9352027 operations; 43205.18 current ops/sec; [UPDATE AverageLatency(us)=2870362] [INSERT AverageLatency(us)=209.34] [CLEANUP AverageLatency(us)=2870373] 
2014-07-10 17:51:07:181 670 sec: 9724255 operations; 37222.8 current ops/sec; [UPDATE AverageLatency(us)=2580319.5] [INSERT AverageLatency(us)=195.21] [CLEANUP AverageLatency(us)=2580332] 
2014-07-10 17:51:17:204 680 sec: 9987776 operations; 26291.63 current ops/sec; [UPDATE AverageLatency(us)=1598428.5] [INSERT AverageLatency(us)=153.33] [CLEANUP AverageLatency(us)=1598439.67] 
2014-07-10 17:51:18:240 681 sec: 10000000 operations; 11810.63 current ops/sec; [UPDATE AverageLatency(us)=391993] [INSERT AverageLatency(us)=50.84] [CLEANUP AverageLatency(us)=392004] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1405039878
1405039878
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ false
+ false
+ false
+ false
+ false
+ false
+ false
+ false
+ let counter=1+1
+ read line
+ set +x
