++ ls caseresult/ -ltr
++ wc -l
+ filename=case65
+ mkdir caseresult/case65
+ RESULT_DIR=/home/hadoop/git/physical_design/caseresult/case65
+ TEN=10
+ SIXTY=60
+ SLEEP_TIME=300
+ YCSB_DIR=/home/hadoop/ycsb-0.1.4
+ number_of_operations=10000000
+ number_of_threads=20
+ number_of_records=50000000
+ output_file_suffix=.dat
+ experiment_list_file=/home/hadoop/git/physical_design/case65.list
+ clean=false
+ create=false
+ load=false
+ random_read=false
+ workloada=false
+ workloadb=false
+ workloadc=false
+ scan=false
+ all=false
+ for i in '$@'
+ '[' clean == all ']'
+ '[' clean == clean ']'
+ clean=true
+ for i in '$@'
+ '[' create == all ']'
+ '[' create == clean ']'
+ '[' create == create ']'
+ create=true
+ for i in '$@'
+ '[' load == all ']'
+ '[' load == clean ']'
+ '[' load == create ']'
+ '[' load == load ']'
+ load=true
+ let counter=1
+ cd /home/hadoop/ycsb-0.1.4
++ pwd
+ echo /home/hadoop/ycsb-0.1.4
/home/hadoop/ycsb-0.1.4
+ read line
+ false
+ true
+ echo 'sleeping for 60 ...'
sleeping for 60 ...
+ sleep 60
+ echo 'droping usertable...'
droping usertable...
+ hbase shell /home/hadoop/git/physical_design/delete_table
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/hadoop/hbase-0.98.3-hadoop1/lib/slf4j-log4j12-1.6.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/hadoop/hadoop-1.2.1/lib/slf4j-log4j12-1.4.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
0 row(s) in 2.7180 seconds

0 row(s) in 2.4850 seconds

0 row(s) in 0.0990 seconds

+ echo 'sleeping for 300 ...'
sleeping for 300 ...
+ sleep 300
+ false
+ true
+ echo 'creating usertable...'
creating usertable...
+ create_statement='create '\''usertable'\'', { NAME=>'\''family'\'', CONFIGURATION => { '\''hbase.hregion.majorcompaction'\'' => '\''0'\'' } ,  COMPRESSION=>'\''GZ'\''}, SPLITS => ['\''user1'\'', '\''user2'\'', '\''user3'\'', '\''user4'\'', '\''user5'\'', '\''user6'\'', '\''user7'\'', '\''user8'\'', '\''user9'\'']'
+ echo create ''\''usertable'\'',' '{' 'NAME=>'\''family'\'',' CONFIGURATION '=>' '{' ''\''hbase.hregion.majorcompaction'\''' '=>' ''\''0'\''' '}' , 'COMPRESSION=>'\''GZ'\''},' SPLITS '=>' '['\''user1'\'',' ''\''user2'\'',' ''\''user3'\'',' ''\''user4'\'',' ''\''user5'\'',' ''\''user6'\'',' ''\''user7'\'',' ''\''user8'\'',' ''\''user9'\'']'
+ echo 'exit '
+ create_table /home/hadoop/git/physical_design/caseresult/case65/create_1.script
+ echo 'creating table...'
creating table...
+ echo /home/hadoop/git/physical_design/caseresult/case65/create_1.script
/home/hadoop/git/physical_design/caseresult/case65/create_1.script
+ hbase shell /home/hadoop/git/physical_design/caseresult/case65/create_1.script
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/hadoop/hbase-0.98.3-hadoop1/lib/slf4j-log4j12-1.6.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/hadoop/hadoop-1.2.1/lib/slf4j-log4j12-1.4.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
0 row(s) in 1.6580 seconds

+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ false
+ true
+ echo 'loading data...'
loading data...
+ echo 'starting time: '
starting time: 
++ date +%s
+ echo 1405035752
1405035752
++ echo /home/hadoop/git/physical_design/caseresult/case65/load_1.dat
+ ./ld 50000000 20 /home/hadoop/git/physical_design/caseresult/case65/load_1.dat
Loading workload...
Starting test.
2014-07-10 16:42:32:786 0 sec: 0 operations; 
14/07/10 16:42:33 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/10 16:42:33 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm48.almaden.ibm.com
14/07/10 16:42:33 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/10 16:42:33 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/10 16:42:33 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/10 16:42:33 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar
14/07/10 16:42:33 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/10 16:42:33 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/10 16:42:33 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/10 16:42:33 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/10 16:42:33 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/10 16:42:33 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/10 16:42:33 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/10 16:42:33 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/10 16:42:33 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/10 16:42:33 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x46f91a48, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/10 16:42:33 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x46f91a48 connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/10 16:42:33 INFO zookeeper.ClientCnxn: Opening socket connection to server slave1/9.1.143.59:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/10 16:42:33 INFO zookeeper.ClientCnxn: Socket connection established to slave1/9.1.143.59:2181, initiating session
14/07/10 16:42:33 INFO zookeeper.ClientCnxn: Session establishment complete on server slave1/9.1.143.59:2181, sessionid = 0x14722a23c300008, negotiated timeout = 90000
2014-07-10 16:42:42:789 10 sec: 250736 operations; 25066.08 current ops/sec; [INSERT AverageLatency(us)=463.44] 
2014-07-10 16:42:52:790 20 sec: 250736 operations; 0 current ops/sec;  
2014-07-10 16:43:02:791 30 sec: 250736 operations; 0 current ops/sec;  
2014-07-10 16:43:12:792 40 sec: 250736 operations; 0 current ops/sec;  
2014-07-10 16:43:22:793 50 sec: 509105 operations; 25834.32 current ops/sec; [INSERT AverageLatency(us)=997.06] 
14/07/10 16:43:27 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2842 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=878, waitTime=2293, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 10078 ms, replay 2842 ops.
14/07/10 16:43:27 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2821 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=878, waitTime=2293, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 10000 ms, replay 2821 ops.
14/07/10 16:43:27 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2795 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=878, waitTime=2293, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 10043 ms, replay 2795 ops.
14/07/10 16:43:27 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2866 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=878, waitTime=2293, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 10050 ms, replay 2866 ops.
14/07/10 16:43:27 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 2846 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=878, waitTime=2293, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 10023 ms, replay 2846 ops.
14/07/10 16:43:27 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2841 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=878, waitTime=2293, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 10037 ms, replay 2841 ops.
14/07/10 16:43:27 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2823 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=878, waitTime=2293, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 10078 ms, replay 2823 ops.
14/07/10 16:43:27 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2818 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=878, waitTime=2293, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 10059 ms, replay 2818 ops.
14/07/10 16:43:27 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2786 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=878, waitTime=2293, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 10007 ms, replay 2786 ops.
14/07/10 16:43:27 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2863 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=878, waitTime=2293, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 10025 ms, replay 2863 ops.
14/07/10 16:43:27 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 2803 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=878, waitTime=2293, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 10040 ms, replay 2803 ops.
14/07/10 16:43:27 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2862 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=878, waitTime=2293, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 10090 ms, replay 2862 ops.
14/07/10 16:43:27 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 2859 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=878, waitTime=2293, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 10073 ms, replay 2859 ops.
14/07/10 16:43:27 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2830 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=878, waitTime=2293, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 10077 ms, replay 2830 ops.
14/07/10 16:43:31 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2856 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1033, waitTime=2005, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:40 PDT 2014, retrying after 10064 ms, replay 2856 ops.
2014-07-10 16:43:32:793 60 sec: 779019 operations; 26991.4 current ops/sec; [INSERT AverageLatency(us)=231.81] 
14/07/10 16:43:39 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2863 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1283, waitTime=2357, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 10004 ms, replay 2863 ops.
14/07/10 16:43:39 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 2862 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1283, waitTime=2357, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 10034 ms, replay 2862 ops.
14/07/10 16:43:39 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2823 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1283, waitTime=2357, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 10000 ms, replay 2823 ops.
14/07/10 16:43:39 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 2803 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1283, waitTime=2357, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 10074 ms, replay 2803 ops.
14/07/10 16:43:39 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 2841 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1283, waitTime=2357, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 10095 ms, replay 2841 ops.
14/07/10 16:43:39 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2866 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1283, waitTime=2357, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 10086 ms, replay 2866 ops.
14/07/10 16:43:39 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 2786 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1283, waitTime=2357, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 10014 ms, replay 2786 ops.
14/07/10 16:43:39 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 2821 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1283, waitTime=2357, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 10057 ms, replay 2821 ops.
14/07/10 16:43:39 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2830 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1283, waitTime=2357, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 10045 ms, replay 2830 ops.
14/07/10 16:43:39 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 failed 2846 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1283, waitTime=2357, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 10001 ms, replay 2846 ops.
14/07/10 16:43:39 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2842 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1283, waitTime=2357, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 10090 ms, replay 2842 ops.
14/07/10 16:43:39 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2795 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1283, waitTime=2357, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 10019 ms, replay 2795 ops.
14/07/10 16:43:39 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 2818 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1283, waitTime=2357, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 10012 ms, replay 2818 ops.
14/07/10 16:43:39 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 2859 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1283, waitTime=2357, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 10082 ms, replay 2859 ops.
2014-07-10 16:43:42:794 70 sec: 940650 operations; 16161.48 current ops/sec; [INSERT AverageLatency(us)=280.33] 
14/07/10 16:43:43 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:40 PDT 2014
14/07/10 16:43:51 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 2863 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1582, waitTime=2687, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 20102 ms, replay 2863 ops.
14/07/10 16:43:51 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 failed 2818 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1582, waitTime=2687, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 20112 ms, replay 2818 ops.
14/07/10 16:43:51 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 failed 2786 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1582, waitTime=2687, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 20090 ms, replay 2786 ops.
14/07/10 16:43:51 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 failed 2859 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1582, waitTime=2687, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 20044 ms, replay 2859 ops.
14/07/10 16:43:51 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 failed 2795 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1582, waitTime=2687, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 20014 ms, replay 2795 ops.
14/07/10 16:43:51 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 failed 2866 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1582, waitTime=2687, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 20015 ms, replay 2866 ops.
14/07/10 16:43:51 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 2842 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1582, waitTime=2687, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 20136 ms, replay 2842 ops.
14/07/10 16:43:51 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 failed 2830 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1582, waitTime=2687, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 20000 ms, replay 2830 ops.
14/07/10 16:43:51 INFO client.AsyncProcess: #5, table=usertable, attempt=12/35 failed 2846 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1582, waitTime=2687, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 20183 ms, replay 2846 ops.
14/07/10 16:43:51 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 failed 2862 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1582, waitTime=2687, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 20060 ms, replay 2862 ops.
14/07/10 16:43:51 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 failed 2841 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1582, waitTime=2687, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 20149 ms, replay 2841 ops.
14/07/10 16:43:51 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 2823 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1582, waitTime=2687, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 20046 ms, replay 2823 ops.
14/07/10 16:43:51 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 failed 2821 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1582, waitTime=2687, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 20036 ms, replay 2821 ops.
14/07/10 16:43:51 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 failed 2803 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1582, waitTime=2687, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014, retrying after 20000 ms, replay 2803 ops.
2014-07-10 16:43:52:794 80 sec: 1203865 operations; 26321.5 current ops/sec; [INSERT AverageLatency(us)=245.33] 
2014-07-10 16:44:02:795 90 sec: 1204882 operations; 101.69 current ops/sec; [INSERT AverageLatency(us)=103.63] 
2014-07-10 16:44:12:796 100 sec: 1204882 operations; 0 current ops/sec;  
14/07/10 16:44:12 INFO client.AsyncProcess: #6, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014
14/07/10 16:44:12 INFO client.AsyncProcess: #10, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014
14/07/10 16:44:12 INFO client.AsyncProcess: #19, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014
14/07/10 16:44:13 INFO client.AsyncProcess: #7, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014
14/07/10 16:44:13 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014
14/07/10 16:44:13 INFO client.AsyncProcess: #8, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014
14/07/10 16:44:13 INFO client.AsyncProcess: #12, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014
14/07/10 16:44:13 INFO client.AsyncProcess: #4, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014
14/07/10 16:44:13 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014
14/07/10 16:44:13 INFO client.AsyncProcess: #13, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014
14/07/10 16:44:13 INFO client.AsyncProcess: #14, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014
14/07/10 16:44:13 INFO client.AsyncProcess: #3, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014
14/07/10 16:44:13 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014
14/07/10 16:44:13 INFO client.AsyncProcess: #5, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:42:35 PDT 2014
2014-07-10 16:44:22:796 110 sec: 1387626 operations; 18274.4 current ops/sec; [INSERT AverageLatency(us)=7861.74] 
2014-07-10 16:44:32:797 120 sec: 1621279 operations; 23362.96 current ops/sec; [INSERT AverageLatency(us)=391.04] 
14/07/10 16:44:33 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2792 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2359, waitTime=2313, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014, retrying after 10005 ms, replay 2792 ops.
14/07/10 16:44:33 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 3318 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2359, waitTime=2313, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:48 PDT 2014, retrying after 10033 ms, replay 3318 ops.
14/07/10 16:44:33 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 3160 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2359, waitTime=2313, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014, retrying after 10070 ms, replay 3160 ops.
14/07/10 16:44:33 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2941 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2359, waitTime=2313, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:51 PDT 2014, retrying after 10065 ms, replay 2941 ops.
14/07/10 16:44:33 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2789 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2359, waitTime=2313, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014, retrying after 10099 ms, replay 2789 ops.
14/07/10 16:44:33 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 1683 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2359, waitTime=2313, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014, retrying after 10012 ms, replay 1683 ops.
14/07/10 16:44:33 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2595 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2359, waitTime=2313, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014, retrying after 10058 ms, replay 2595 ops.
14/07/10 16:44:33 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2867 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2359, waitTime=2313, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014, retrying after 10040 ms, replay 2867 ops.
14/07/10 16:44:33 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 3402 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2359, waitTime=2313, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:48 PDT 2014, retrying after 10099 ms, replay 3402 ops.
2014-07-10 16:44:42:798 130 sec: 1891713 operations; 27040.7 current ops/sec; [INSERT AverageLatency(us)=238.99] 
14/07/10 16:44:46 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 1683 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2704, waitTime=3713, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014, retrying after 10083 ms, replay 1683 ops.
14/07/10 16:44:46 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 2792 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2704, waitTime=3713, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014, retrying after 10087 ms, replay 2792 ops.
14/07/10 16:44:46 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 2789 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2704, waitTime=3713, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014, retrying after 10083 ms, replay 2789 ops.
14/07/10 16:44:46 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 2595 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2704, waitTime=3713, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014, retrying after 10033 ms, replay 2595 ops.
14/07/10 16:44:46 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2941 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2704, waitTime=3713, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:51 PDT 2014, retrying after 10021 ms, replay 2941 ops.
14/07/10 16:44:46 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 3318 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2704, waitTime=3713, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:48 PDT 2014, retrying after 10042 ms, replay 3318 ops.
14/07/10 16:44:46 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 3402 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2704, waitTime=3713, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:48 PDT 2014, retrying after 10000 ms, replay 3402 ops.
14/07/10 16:44:46 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 2867 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2704, waitTime=3713, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014, retrying after 10099 ms, replay 2867 ops.
14/07/10 16:44:46 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 3160 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2704, waitTime=3713, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014, retrying after 10099 ms, replay 3160 ops.
2014-07-10 16:44:52:798 140 sec: 1891713 operations; 0 current ops/sec;  
14/07/10 16:44:59 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 1683 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2845, waitTime=3154, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014, retrying after 20064 ms, replay 1683 ops.
14/07/10 16:44:59 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 failed 3402 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2845, waitTime=3154, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:48 PDT 2014, retrying after 20189 ms, replay 3402 ops.
14/07/10 16:44:59 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 failed 2792 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2845, waitTime=3154, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014, retrying after 20031 ms, replay 2792 ops.
14/07/10 16:44:59 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 failed 2789 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2845, waitTime=3154, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014, retrying after 20045 ms, replay 2789 ops.
14/07/10 16:44:59 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 failed 2941 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2845, waitTime=3154, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:51 PDT 2014, retrying after 20116 ms, replay 2941 ops.
14/07/10 16:44:59 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 3160 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2845, waitTime=3154, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014, retrying after 20197 ms, replay 3160 ops.
14/07/10 16:44:59 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 failed 3318 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2845, waitTime=3154, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:48 PDT 2014, retrying after 20028 ms, replay 3318 ops.
14/07/10 16:44:59 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 2867 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2845, waitTime=3154, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014, retrying after 20175 ms, replay 2867 ops.
14/07/10 16:44:59 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 failed 2595 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2845, waitTime=3154, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014, retrying after 20025 ms, replay 2595 ops.
2014-07-10 16:45:02:805 150 sec: 1912183 operations; 2045.57 current ops/sec; [INSERT AverageLatency(us)=4394.89] 
14/07/10 16:45:08 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 3445 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2987, waitTime=2103, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014, retrying after 10071 ms, replay 3445 ops.
14/07/10 16:45:08 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 3384 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2987, waitTime=2103, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014, retrying after 10033 ms, replay 3384 ops.
14/07/10 16:45:08 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 3117 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2987, waitTime=2103, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014, retrying after 10054 ms, replay 3117 ops.
14/07/10 16:45:08 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 3344 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2987, waitTime=2103, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014, retrying after 10091 ms, replay 3344 ops.
14/07/10 16:45:08 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2816 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2987, waitTime=2103, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:15 PDT 2014, retrying after 10094 ms, replay 2816 ops.
14/07/10 16:45:08 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 3397 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2987, waitTime=2103, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014, retrying after 10082 ms, replay 3397 ops.
2014-07-10 16:45:12:808 160 sec: 2160053 operations; 24779.57 current ops/sec; [INSERT AverageLatency(us)=635.05] 
14/07/10 16:45:21 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 3344 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3393, waitTime=2649, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014, retrying after 10013 ms, replay 3344 ops.
14/07/10 16:45:21 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 3384 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3393, waitTime=2649, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014, retrying after 10006 ms, replay 3384 ops.
14/07/10 16:45:21 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 failed 3117 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3393, waitTime=2649, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014, retrying after 10052 ms, replay 3117 ops.
14/07/10 16:45:21 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 3445 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3393, waitTime=2649, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014, retrying after 10029 ms, replay 3445 ops.
14/07/10 16:45:21 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 3397 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3393, waitTime=2649, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014, retrying after 10035 ms, replay 3397 ops.
14/07/10 16:45:21 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2816 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3393, waitTime=2649, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:15 PDT 2014, retrying after 10011 ms, replay 2816 ops.
14/07/10 16:45:21 INFO client.AsyncProcess: #1, table=usertable, attempt=13/35 failed 2792 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3427, waitTime=2170, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014, retrying after 20095 ms, replay 2792 ops.
14/07/10 16:45:22 INFO client.AsyncProcess: #9, table=usertable, attempt=13/35 failed 3318 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3435, waitTime=2288, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:48 PDT 2014, retrying after 20193 ms, replay 3318 ops.
14/07/10 16:45:22 INFO client.AsyncProcess: #17, table=usertable, attempt=13/35 failed 2941 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3435, waitTime=2288, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:51 PDT 2014, retrying after 20039 ms, replay 2941 ops.
14/07/10 16:45:22 INFO client.AsyncProcess: #18, table=usertable, attempt=13/35 failed 2595 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3435, waitTime=2288, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014, retrying after 20159 ms, replay 2595 ops.
14/07/10 16:45:22 INFO client.AsyncProcess: #16, table=usertable, attempt=13/35 failed 2789 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3435, waitTime=2288, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014, retrying after 20112 ms, replay 2789 ops.
14/07/10 16:45:22 INFO client.AsyncProcess: #18, table=usertable, attempt=13/35 failed 3402 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3435, waitTime=2288, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:48 PDT 2014, retrying after 20060 ms, replay 3402 ops.
14/07/10 16:45:22 INFO client.AsyncProcess: #11, table=usertable, attempt=13/35 failed 2867 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3435, waitTime=2288, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014, retrying after 20151 ms, replay 2867 ops.
14/07/10 16:45:22 INFO client.AsyncProcess: #11, table=usertable, attempt=13/35 failed 3160 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3435, waitTime=2288, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014, retrying after 20037 ms, replay 3160 ops.
14/07/10 16:45:22 INFO client.AsyncProcess: #11, table=usertable, attempt=13/35 failed 1683 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3435, waitTime=2288, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014, retrying after 20195 ms, replay 1683 ops.
2014-07-10 16:45:22:810 170 sec: 2477710 operations; 31759.35 current ops/sec; [INSERT AverageLatency(us)=175.9] 
2014-07-10 16:45:32:811 180 sec: 2491210 operations; 1349.87 current ops/sec; [INSERT AverageLatency(us)=5037.79] 
14/07/10 16:45:33 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 3445 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3567, waitTime=2144, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014, retrying after 20045 ms, replay 3445 ops.
14/07/10 16:45:33 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 failed 3384 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3567, waitTime=2144, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014, retrying after 20004 ms, replay 3384 ops.
14/07/10 16:45:33 INFO client.AsyncProcess: #5, table=usertable, attempt=12/35 failed 3117 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3567, waitTime=2144, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014, retrying after 20083 ms, replay 3117 ops.
14/07/10 16:45:33 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 failed 3344 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3567, waitTime=2144, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014, retrying after 20124 ms, replay 3344 ops.
14/07/10 16:45:33 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 3397 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3567, waitTime=2144, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014, retrying after 20102 ms, replay 3397 ops.
14/07/10 16:45:33 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 2816 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3567, waitTime=2144, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:15 PDT 2014, retrying after 20134 ms, replay 2816 ops.
14/07/10 16:45:42 INFO client.AsyncProcess: #1, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014
2014-07-10 16:45:42:814 190 sec: 2852377 operations; 36105.87 current ops/sec; [INSERT AverageLatency(us)=621.22] 
14/07/10 16:45:43 INFO client.AsyncProcess: #17, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:51 PDT 2014
14/07/10 16:45:44 INFO client.AsyncProcess: #18, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:48 PDT 2014
14/07/10 16:45:44 INFO client.AsyncProcess: #18, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014
14/07/10 16:45:45 INFO client.AsyncProcess: #11, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014
14/07/10 16:45:45 INFO client.AsyncProcess: #9, table=usertable, attempt=14/35 failed 3318 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3994, waitTime=3196, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:48 PDT 2014, retrying after 20088 ms, replay 3318 ops.
14/07/10 16:45:45 INFO client.AsyncProcess: #16, table=usertable, attempt=14/35 failed 2789 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3994, waitTime=3196, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014, retrying after 20000 ms, replay 2789 ops.
14/07/10 16:45:45 INFO client.AsyncProcess: #11, table=usertable, attempt=14/35 failed 2867 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3994, waitTime=3196, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014, retrying after 20127 ms, replay 2867 ops.
14/07/10 16:45:45 INFO client.AsyncProcess: #11, table=usertable, attempt=14/35 failed 3160 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3994, waitTime=3196, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014, retrying after 20135 ms, replay 3160 ops.
2014-07-10 16:45:52:816 200 sec: 3076985 operations; 22456.31 current ops/sec; [INSERT AverageLatency(us)=1149.01] 
14/07/10 16:45:56 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 failed 3397 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:36295 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014, retrying after 20080 ms, replay 3397 ops.
14/07/10 16:45:56 INFO client.AsyncProcess: #5, table=usertable, attempt=13/35 failed 3117 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:36295 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014, retrying after 20041 ms, replay 3117 ops.
14/07/10 16:45:56 INFO client.AsyncProcess: #14, table=usertable, attempt=13/35 failed 3344 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:36295 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014, retrying after 20080 ms, replay 3344 ops.
14/07/10 16:45:56 INFO client.AsyncProcess: #3, table=usertable, attempt=13/35 failed 3384 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:36295 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014, retrying after 20167 ms, replay 3384 ops.
14/07/10 16:45:56 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 failed 3445 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:36295 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014, retrying after 20045 ms, replay 3445 ops.
14/07/10 16:45:56 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 failed 2816 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:36295 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:15 PDT 2014, retrying after 20100 ms, replay 2816 ops.
2014-07-10 16:46:02:817 210 sec: 3146488 operations; 6949.61 current ops/sec; [INSERT AverageLatency(us)=315.82] 
14/07/10 16:46:06 INFO client.AsyncProcess: #16, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014
14/07/10 16:46:06 INFO client.AsyncProcess: #11, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014
14/07/10 16:46:06 INFO client.AsyncProcess: #9, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:48 PDT 2014
14/07/10 16:46:06 INFO client.AsyncProcess: #11, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:43:49 PDT 2014
2014-07-10 16:46:12:817 220 sec: 3324901 operations; 17841.3 current ops/sec; [INSERT AverageLatency(us)=3300.05] 
14/07/10 16:46:18 INFO client.AsyncProcess: #5, table=usertable, attempt=14/35 failed 3117 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5000, waitTime=2083, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014, retrying after 20011 ms, replay 3117 ops.
14/07/10 16:46:18 INFO client.AsyncProcess: #20, table=usertable, attempt=14/35 failed 3445 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5000, waitTime=2083, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014, retrying after 20140 ms, replay 3445 ops.
14/07/10 16:46:18 INFO client.AsyncProcess: #14, table=usertable, attempt=14/35 failed 3344 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5000, waitTime=2083, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014, retrying after 20052 ms, replay 3344 ops.
14/07/10 16:46:19 INFO client.AsyncProcess: #3, table=usertable, attempt=14/35 failed 3384 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5003, waitTime=2130, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014, retrying after 20080 ms, replay 3384 ops.
14/07/10 16:46:19 INFO client.AsyncProcess: #2, table=usertable, attempt=14/35 failed 3397 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5003, waitTime=2130, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014, retrying after 20089 ms, replay 3397 ops.
14/07/10 16:46:19 INFO client.AsyncProcess: #15, table=usertable, attempt=14/35 failed 2816 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5003, waitTime=2130, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:15 PDT 2014, retrying after 20110 ms, replay 2816 ops.
2014-07-10 16:46:22:818 230 sec: 3427765 operations; 10285.37 current ops/sec; [INSERT AverageLatency(us)=577.05] 
2014-07-10 16:46:32:819 240 sec: 3427765 operations; 0 current ops/sec;  
14/07/10 16:46:40 INFO client.AsyncProcess: #3, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014
14/07/10 16:46:40 INFO client.AsyncProcess: #20, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014
14/07/10 16:46:40 INFO client.AsyncProcess: #5, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014
14/07/10 16:46:41 INFO client.AsyncProcess: #14, table=usertable, attempt=15/35 failed 3344 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5306, waitTime=2015, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014, retrying after 20078 ms, replay 3344 ops.
14/07/10 16:46:41 INFO client.AsyncProcess: #2, table=usertable, attempt=15/35 failed 3397 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5320, waitTime=2056, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014, retrying after 20044 ms, replay 3397 ops.
14/07/10 16:46:41 INFO client.AsyncProcess: #15, table=usertable, attempt=15/35 failed 2816 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5320, waitTime=2056, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:15 PDT 2014, retrying after 20118 ms, replay 2816 ops.
2014-07-10 16:46:42:935 250 sec: 3601119 operations; 17136.62 current ops/sec; [INSERT AverageLatency(us)=3364.11] 
2014-07-10 16:46:52:935 260 sec: 3839836 operations; 23871.7 current ops/sec; [INSERT AverageLatency(us)=406.23] 
14/07/10 16:47:00 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2486 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5874, waitTime=2068, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:46:06 PDT 2014, retrying after 10062 ms, replay 2486 ops.
14/07/10 16:47:00 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2804 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5874, waitTime=2068, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:46:07 PDT 2014, retrying after 10073 ms, replay 2804 ops.
14/07/10 16:47:00 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 3431 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5874, waitTime=2068, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:46:06 PDT 2014, retrying after 10057 ms, replay 3431 ops.
14/07/10 16:47:01 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2839 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5881, waitTime=3227, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:46:06 PDT 2014, retrying after 10088 ms, replay 2839 ops.
2014-07-10 16:47:02:936 270 sec: 3996492 operations; 15664.03 current ops/sec; [INSERT AverageLatency(us)=1487.78] 
14/07/10 16:47:04 INFO client.AsyncProcess: #14, table=usertable, attempt=16/35 failed 3344 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:36295 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014, retrying after 20048 ms, replay 3344 ops.
14/07/10 16:47:04 INFO client.AsyncProcess: #2, table=usertable, attempt=16/35 failed 3397 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:36295 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014, retrying after 20071 ms, replay 3397 ops.
14/07/10 16:47:04 INFO client.AsyncProcess: #15, table=usertable, attempt=16/35 failed 2816 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:36295 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:15 PDT 2014, retrying after 20164 ms, replay 2816 ops.
2014-07-10 16:47:12:937 280 sec: 4000830 operations; 433.76 current ops/sec; [INSERT AverageLatency(us)=8334.02] 
14/07/10 16:47:12 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2486 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:36295 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:46:06 PDT 2014, retrying after 10074 ms, replay 2486 ops.
14/07/10 16:47:12 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 2804 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:36295 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:46:07 PDT 2014, retrying after 10088 ms, replay 2804 ops.
14/07/10 16:47:12 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 3431 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:36295 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:46:06 PDT 2014, retrying after 10093 ms, replay 3431 ops.
14/07/10 16:47:14 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 2839 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.58:36295 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:46:06 PDT 2014, retrying after 10096 ms, replay 2839 ops.
2014-07-10 16:47:22:938 290 sec: 4047528 operations; 4669.33 current ops/sec; [INSERT AverageLatency(us)=3164.1] 
14/07/10 16:47:25 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 failed 2486 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6298, waitTime=2323, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:46:06 PDT 2014, retrying after 20165 ms, replay 2486 ops.
14/07/10 16:47:25 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 2804 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6298, waitTime=2323, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:46:07 PDT 2014, retrying after 20131 ms, replay 2804 ops.
14/07/10 16:47:25 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 failed 3431 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6298, waitTime=2323, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:46:06 PDT 2014, retrying after 20041 ms, replay 3431 ops.
14/07/10 16:47:26 INFO client.AsyncProcess: #2, table=usertable, attempt=17/35 failed 3397 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6364, waitTime=2120, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014, retrying after 20118 ms, replay 3397 ops.
14/07/10 16:47:26 INFO client.AsyncProcess: #14, table=usertable, attempt=17/35 failed 3344 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6364, waitTime=2120, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:13 PDT 2014, retrying after 20038 ms, replay 3344 ops.
14/07/10 16:47:26 INFO client.AsyncProcess: #15, table=usertable, attempt=17/35 failed 2816 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6374, waitTime=2005, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:44:15 PDT 2014, retrying after 20020 ms, replay 2816 ops.
14/07/10 16:47:27 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 failed 2839 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6389, waitTime=2341, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405035364686, tracking started Thu Jul 10 16:46:06 PDT 2014, retrying after 20001 ms, replay 2839 ops.
2014-07-10 16:47:32:939 300 sec: 4425927 operations; 37836.12 current ops/sec; [INSERT AverageLatency(us)=562.38] 
2014-07-10 16:47:43:015 310 sec: 4754874 operations; 32649.83 current ops/sec; [INSERT AverageLatency(us)=344.66] 
Traceback (most recent call last):
  File "./bin/ycsb", line 116, in <module>
    subprocess.call(ycsb_command)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 1376, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
+ echo 'end time:'
end time:
++ date +%s
+ echo 1405039158
1405039158
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
