++ ls caseresult/ -ltr
++ wc -l
+ filename=case69
+ mkdir caseresult/case69
+ ssh hadoop@master mkdir /home/hadoop/git/physical_design/caseresult/case69
+ RESULT_DIR=/home/hadoop/git/physical_design/caseresult/case69
+ TEN=10
+ SIXTY=60
+ SLEEP_TIME=300
+ YCSB_DIR=/home/hadoop/ycsb-0.1.4
+ number_of_operations=10000000
+ number_of_threads=20
+ number_of_records=10000000
+ output_file_suffix=.dat
+ experiment_list_file=/home/hadoop/git/physical_design/case69.list
+ clean=false
+ create=false
+ load=false
+ random_read=false
+ workloada=false
+ workloadb=false
+ workloadc=false
+ scan=false
+ all=false
+ for i in '$@'
+ '[' clean == all ']'
+ '[' clean == clean ']'
+ clean=true
+ for i in '$@'
+ '[' create == all ']'
+ '[' create == clean ']'
+ '[' create == create ']'
+ create=true
+ for i in '$@'
+ '[' load == all ']'
+ '[' load == clean ']'
+ '[' load == create ']'
+ '[' load == load ']'
+ load=true
+ let counter=1
+ cd /home/hadoop/ycsb-0.1.4
++ pwd
+ echo /home/hadoop/ycsb-0.1.4
/home/hadoop/ycsb-0.1.4
+ read line
+ false
+ true
+ echo 'sleeping for 60 ...'
sleeping for 60 ...
+ sleep 60
+ echo 'droping usertable...'
droping usertable...
+ ssh hadoop@master /home/hadoop/hbase/bin/hbase shell /home/hadoop/git/physical_design/delete_table
0 row(s) in 4.2180 seconds

0 row(s) in 0.7630 seconds

0 row(s) in 0.0700 seconds

+ echo 'sleeping for 300 ...'
sleeping for 300 ...
+ sleep 300
+ false
+ true
+ echo 'creating usertable...'
creating usertable...
+ create_statement='create '\''usertable'\'', { NAME=>'\''family'\'', COMPRESSION=>'\''GZ'\'', CONFIGURATION =>  { '\''hbase.hregion.majorcompaction'\'' => '\''0'\'', '\''hbase.hstore.compactionThreshold'\'' => '\''100000000000000'\'', '\''hbase.server.compactchecker.interval.multiplier'\'' => '\''100000000'\'', '\''hbase.hstore.compaction.max.size'\'' => '\''128'\'' } }, SPLITS => ['\''user1'\'', '\''user2'\'', '\''user3'\'', '\''user4'\'', '\''user5'\'', '\''user6'\'', '\''user7'\'', '\''user8'\'', '\''user9'\'']'
+ echo create ''\''usertable'\'',' '{' 'NAME=>'\''family'\'',' 'COMPRESSION=>'\''GZ'\'',' CONFIGURATION '=>' '{' ''\''hbase.hregion.majorcompaction'\''' '=>' ''\''0'\'',' ''\''hbase.hstore.compactionThreshold'\''' '=>' ''\''100000000000000'\'',' ''\''hbase.server.compactchecker.interval.multiplier'\''' '=>' ''\''100000000'\'',' ''\''hbase.hstore.compaction.max.size'\''' '=>' ''\''128'\''' '}' '},' SPLITS '=>' '['\''user1'\'',' ''\''user2'\'',' ''\''user3'\'',' ''\''user4'\'',' ''\''user5'\'',' ''\''user6'\'',' ''\''user7'\'',' ''\''user8'\'',' ''\''user9'\'']'
+ echo 'exit '
+ scp /home/hadoop/git/physical_design/caseresult/case69/create_1.script hadoop@master:/home/hadoop/git/physical_design/caseresult/case69/create_1.script
+ create_table /home/hadoop/git/physical_design/caseresult/case69/create_1.script
+ echo 'creating table...'
creating table...
+ echo /home/hadoop/git/physical_design/caseresult/case69/create_1.script
/home/hadoop/git/physical_design/caseresult/case69/create_1.script
+ ssh hadoop@master /home/hadoop/hbase/bin/hbase shell /home/hadoop/git/physical_design/caseresult/case69/create_1.script
0 row(s) in 1.7740 seconds

+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ false
+ true
+ echo 'loading data...'
loading data...
+ echo 'starting time: '
starting time: 
++ date +%s
+ echo 1405030745
1405030745
++ echo /home/hadoop/git/physical_design/caseresult/case69/load_1.dat
+ ./ld 10000000 20 /home/hadoop/git/physical_design/caseresult/case69/load_1.dat
Loading workload...
Starting test.
2014-07-10 15:19:05:594 0 sec: 0 operations; 
14/07/10 15:19:05 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/10 15:19:05 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm43.almaden.ibm.com
14/07/10 15:19:05 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/10 15:19:05 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/10 15:19:05 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/10 15:19:05 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf
14/07/10 15:19:05 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/10 15:19:05 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/10 15:19:05 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/10 15:19:05 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/10 15:19:05 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/10 15:19:05 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/10 15:19:05 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/10 15:19:05 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/10 15:19:05 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/10 15:19:05 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x29ee65b1, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/10 15:19:05 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x29ee65b1 connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/10 15:19:05 INFO zookeeper.ClientCnxn: Opening socket connection to server master/9.1.143.58:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/10 15:19:06 INFO zookeeper.ClientCnxn: Socket connection established to master/9.1.143.58:2181, initiating session
14/07/10 15:19:06 INFO zookeeper.ClientCnxn: Session establishment complete on server master/9.1.143.58:2181, sessionid = 0x472407e55b000a, negotiated timeout = 90000
2014-07-10 15:19:15:595 10 sec: 239917 operations; 23989.3 current ops/sec; [INSERT AverageLatency(us)=400.31] 
2014-07-10 15:19:25:596 20 sec: 239917 operations; 0 current ops/sec;  
2014-07-10 15:19:35:597 30 sec: 310166 operations; 7024.9 current ops/sec; [INSERT AverageLatency(us)=2083.24] 
2014-07-10 15:19:45:597 40 sec: 600275 operations; 29008 current ops/sec; [INSERT AverageLatency(us)=200.23] 
2014-07-10 15:19:55:597 50 sec: 825006 operations; 22473.1 current ops/sec; [INSERT AverageLatency(us)=262] 
14/07/10 15:19:59 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2844 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1004, waitTime=2082, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 10067 ms, replay 2844 ops.
14/07/10 15:20:00 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2841 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1012, waitTime=2166, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 10043 ms, replay 2841 ops.
14/07/10 15:20:00 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2822 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1012, waitTime=2166, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 10079 ms, replay 2822 ops.
14/07/10 15:20:00 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2793 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1012, waitTime=2166, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 10097 ms, replay 2793 ops.
14/07/10 15:20:00 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2823 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1012, waitTime=2166, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 10075 ms, replay 2823 ops.
14/07/10 15:20:00 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2872 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1012, waitTime=2166, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 10000 ms, replay 2872 ops.
14/07/10 15:20:00 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2838 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1012, waitTime=2166, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 10084 ms, replay 2838 ops.
14/07/10 15:20:00 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 2784 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1012, waitTime=2166, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 10022 ms, replay 2784 ops.
14/07/10 15:20:01 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2837 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1043, waitTime=2026, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 10009 ms, replay 2837 ops.
14/07/10 15:20:01 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2809 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1043, waitTime=2026, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 10093 ms, replay 2809 ops.
14/07/10 15:20:01 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2832 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1045, waitTime=2094, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 10051 ms, replay 2832 ops.
14/07/10 15:20:01 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2855 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1045, waitTime=2094, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 10073 ms, replay 2855 ops.
14/07/10 15:20:01 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2860 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1045, waitTime=2094, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 10011 ms, replay 2860 ops.
14/07/10 15:20:01 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2798 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1048, waitTime=2000, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 10023 ms, replay 2798 ops.
2014-07-10 15:20:05:598 60 sec: 1007297 operations; 18227.28 current ops/sec; [INSERT AverageLatency(us)=334.75] 
14/07/10 15:20:11 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014
14/07/10 15:20:11 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014
14/07/10 15:20:11 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014
14/07/10 15:20:11 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014
14/07/10 15:20:12 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 2823 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1377, waitTime=2160, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 10075 ms, replay 2823 ops.
14/07/10 15:20:12 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2793 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1377, waitTime=2160, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 10078 ms, replay 2793 ops.
14/07/10 15:20:12 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2838 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1377, waitTime=2160, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 10042 ms, replay 2838 ops.
14/07/10 15:20:12 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 2822 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1377, waitTime=2160, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 10024 ms, replay 2822 ops.
14/07/10 15:20:13 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 2837 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1411, waitTime=2101, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 10089 ms, replay 2837 ops.
14/07/10 15:20:13 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 2809 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1411, waitTime=2101, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 10051 ms, replay 2809 ops.
14/07/10 15:20:13 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2798 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1413, waitTime=2130, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 10007 ms, replay 2798 ops.
14/07/10 15:20:13 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2860 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1413, waitTime=2130, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 10011 ms, replay 2860 ops.
14/07/10 15:20:13 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 2855 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1413, waitTime=2130, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 10005 ms, replay 2855 ops.
14/07/10 15:20:13 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 2832 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1413, waitTime=2130, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 10010 ms, replay 2832 ops.
2014-07-10 15:20:15:598 70 sec: 1228704 operations; 22140.7 current ops/sec; [INSERT AverageLatency(us)=1311.43] 
14/07/10 15:20:24 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 2823 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56559 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 20058 ms, replay 2823 ops.
14/07/10 15:20:24 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 failed 2822 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56559 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 20079 ms, replay 2822 ops.
14/07/10 15:20:24 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 failed 2838 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56559 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 20014 ms, replay 2838 ops.
14/07/10 15:20:24 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 failed 2793 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56559 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 20131 ms, replay 2793 ops.
2014-07-10 15:20:25:599 80 sec: 1293002 operations; 6429.16 current ops/sec; [INSERT AverageLatency(us)=1070.51] 
2014-07-10 15:20:35:599 90 sec: 1312051 operations; 1904.9 current ops/sec; [INSERT AverageLatency(us)=5254.43] 
14/07/10 15:20:37 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 failed 2860 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1616, waitTime=3477, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 20134 ms, replay 2860 ops.
14/07/10 15:20:37 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 failed 2855 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1616, waitTime=3477, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 20101 ms, replay 2855 ops.
14/07/10 15:20:37 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 failed 2837 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1616, waitTime=3477, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 20004 ms, replay 2837 ops.
14/07/10 15:20:37 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 failed 2809 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1616, waitTime=3477, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 20125 ms, replay 2809 ops.
14/07/10 15:20:37 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 2798 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1616, waitTime=3477, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 20037 ms, replay 2798 ops.
14/07/10 15:20:37 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 failed 2832 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1616, waitTime=3477, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 20136 ms, replay 2832 ops.
2014-07-10 15:20:45:600 100 sec: 1326453 operations; 1440.06 current ops/sec; [INSERT AverageLatency(us)=3375.97] 
14/07/10 15:20:45 INFO client.AsyncProcess: #19, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014
14/07/10 15:20:45 INFO client.AsyncProcess: #17, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014
14/07/10 15:20:45 INFO client.AsyncProcess: #1, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014
14/07/10 15:20:45 INFO client.AsyncProcess: #11, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014
2014-07-10 15:20:55:600 110 sec: 1435830 operations; 10937.7 current ops/sec; [INSERT AverageLatency(us)=3904.54] 
14/07/10 15:20:59 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 failed 2798 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1954, waitTime=2410, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 20143 ms, replay 2798 ops.
14/07/10 15:20:59 INFO client.AsyncProcess: #9, table=usertable, attempt=13/35 failed 2837 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1954, waitTime=2410, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 20169 ms, replay 2837 ops.
14/07/10 15:21:00 INFO client.AsyncProcess: #6, table=usertable, attempt=13/35 failed 2860 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1970, waitTime=2350, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 20002 ms, replay 2860 ops.
14/07/10 15:21:00 INFO client.AsyncProcess: #16, table=usertable, attempt=13/35 failed 2855 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1970, waitTime=2350, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 20057 ms, replay 2855 ops.
14/07/10 15:21:00 INFO client.AsyncProcess: #8, table=usertable, attempt=13/35 failed 2832 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1970, waitTime=2350, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 20110 ms, replay 2832 ops.
14/07/10 15:21:00 INFO client.AsyncProcess: #14, table=usertable, attempt=13/35 failed 2809 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1970, waitTime=2350, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 20091 ms, replay 2809 ops.
2014-07-10 15:21:05:600 120 sec: 1603578 operations; 16774.8 current ops/sec; [INSERT AverageLatency(us)=303.6] 
14/07/10 15:21:13 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 4673 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2221, waitTime=2004, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:10 PDT 2014, retrying after 10022 ms, replay 4673 ops.
2014-07-10 15:21:15:601 130 sec: 1841252 operations; 23765.02 current ops/sec; [INSERT AverageLatency(us)=210.93] 
14/07/10 15:21:21 INFO client.AsyncProcess: #9, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014
14/07/10 15:21:21 INFO client.AsyncProcess: #2, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014
14/07/10 15:21:22 INFO client.AsyncProcess: #6, table=usertable, attempt=14/35 failed 2860 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2459, waitTime=2027, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 20025 ms, replay 2860 ops.
14/07/10 15:21:22 INFO client.AsyncProcess: #16, table=usertable, attempt=14/35 failed 2855 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2465, waitTime=2692, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 20097 ms, replay 2855 ops.
14/07/10 15:21:22 INFO client.AsyncProcess: #14, table=usertable, attempt=14/35 failed 2809 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2465, waitTime=2692, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 20064 ms, replay 2809 ops.
14/07/10 15:21:22 INFO client.AsyncProcess: #8, table=usertable, attempt=14/35 failed 2832 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2465, waitTime=2692, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 20090 ms, replay 2832 ops.
14/07/10 15:21:24 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 3942 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2492, waitTime=2703, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:20 PDT 2014, retrying after 10082 ms, replay 3942 ops.
14/07/10 15:21:24 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2806 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2492, waitTime=2703, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 10075 ms, replay 2806 ops.
14/07/10 15:21:24 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 3541 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2509, waitTime=2440, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:20 PDT 2014, retrying after 10017 ms, replay 3541 ops.
14/07/10 15:21:24 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 4695 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2509, waitTime=2440, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 10064 ms, replay 4695 ops.
14/07/10 15:21:24 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2862 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2509, waitTime=2440, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:20 PDT 2014, retrying after 10044 ms, replay 2862 ops.
14/07/10 15:21:24 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 3515 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2509, waitTime=2440, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 10067 ms, replay 3515 ops.
14/07/10 15:21:24 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 4673 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2509, waitTime=2440, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 10062 ms, replay 4673 ops.
14/07/10 15:21:24 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 4236 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2509, waitTime=2440, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 10061 ms, replay 4236 ops.
14/07/10 15:21:25 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 4673 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2520, waitTime=2521, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:10 PDT 2014, retrying after 10049 ms, replay 4673 ops.
2014-07-10 15:21:25:601 140 sec: 2063951 operations; 22269.9 current ops/sec; [INSERT AverageLatency(us)=1284.82] 
2014-07-10 15:21:35:602 150 sec: 2136406 operations; 7244.78 current ops/sec; [INSERT AverageLatency(us)=1086.41] 
14/07/10 15:21:36 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 3942 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2733, waitTime=2031, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:20 PDT 2014, retrying after 10042 ms, replay 3942 ops.
14/07/10 15:21:36 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2806 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2733, waitTime=2031, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 10027 ms, replay 2806 ops.
14/07/10 15:21:36 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 2862 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2736, waitTime=2472, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:20 PDT 2014, retrying after 10008 ms, replay 2862 ops.
14/07/10 15:21:36 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 3541 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2736, waitTime=2472, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:20 PDT 2014, retrying after 10072 ms, replay 3541 ops.
14/07/10 15:21:36 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 failed 4236 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2736, waitTime=2472, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 10083 ms, replay 4236 ops.
14/07/10 15:21:36 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 failed 3515 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2736, waitTime=2472, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 10041 ms, replay 3515 ops.
14/07/10 15:21:36 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 failed 4695 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2736, waitTime=2472, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 10092 ms, replay 4695 ops.
14/07/10 15:21:36 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 4673 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2736, waitTime=2472, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 10048 ms, replay 4673 ops.
14/07/10 15:21:39 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 4673 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56560 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:10 PDT 2014, retrying after 20032 ms, replay 4673 ops.
14/07/10 15:21:42 INFO client.AsyncProcess: #6, table=usertable, attempt=15/35 failed 2860 ops, last exception: java.io.IOException: Unexpected closed connection on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 20130 ms, replay 2860 ops.
14/07/10 15:21:42 INFO client.AsyncProcess: #14, table=usertable, attempt=15/35 failed 2809 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56560 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 20031 ms, replay 2809 ops.
14/07/10 15:21:42 INFO client.AsyncProcess: #16, table=usertable, attempt=15/35 failed 2855 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56560 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 20137 ms, replay 2855 ops.
14/07/10 15:21:42 INFO client.AsyncProcess: #8, table=usertable, attempt=15/35 failed 2832 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56560 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014, retrying after 20132 ms, replay 2832 ops.
2014-07-10 15:21:45:602 160 sec: 2143064 operations; 665.8 current ops/sec; [INSERT AverageLatency(us)=433.57] 
14/07/10 15:21:46 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 2806 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56561 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20174 ms, replay 2806 ops.
14/07/10 15:21:46 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 failed 3942 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56561 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:20 PDT 2014, retrying after 20010 ms, replay 3942 ops.
14/07/10 15:21:46 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 failed 2862 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56561 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:20 PDT 2014, retrying after 20066 ms, replay 2862 ops.
14/07/10 15:21:46 INFO client.AsyncProcess: #12, table=usertable, attempt=12/35 failed 3515 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56561 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20057 ms, replay 3515 ops.
14/07/10 15:21:46 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 failed 4673 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56561 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20126 ms, replay 4673 ops.
14/07/10 15:21:46 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 failed 3541 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56561 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:20 PDT 2014, retrying after 20004 ms, replay 3541 ops.
14/07/10 15:21:46 INFO client.AsyncProcess: #5, table=usertable, attempt=12/35 failed 4236 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56561 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20144 ms, replay 4236 ops.
14/07/10 15:21:46 INFO client.AsyncProcess: #18, table=usertable, attempt=12/35 failed 4695 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for write. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56561 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20059 ms, replay 4695 ops.
2014-07-10 15:21:55:603 170 sec: 2143064 operations; 0 current ops/sec;  
14/07/10 15:22:00 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:10 PDT 2014
14/07/10 15:22:03 INFO client.AsyncProcess: #6, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014
14/07/10 15:22:03 INFO client.AsyncProcess: #14, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014
14/07/10 15:22:03 INFO client.AsyncProcess: #16, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014
14/07/10 15:22:03 INFO client.AsyncProcess: #8, table=usertable, attempt=16/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:19:07 PDT 2014
2014-07-10 15:22:05:603 180 sec: 2249949 operations; 10688.5 current ops/sec; [INSERT AverageLatency(us)=7575.51] 
14/07/10 15:22:08 INFO client.AsyncProcess: #10, table=usertable, attempt=13/35 failed 3942 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2990, waitTime=2387, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:20 PDT 2014, retrying after 20116 ms, replay 3942 ops.
14/07/10 15:22:08 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 3390 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3005, waitTime=2214, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:21:20 PDT 2014, retrying after 10027 ms, replay 3390 ops.
14/07/10 15:22:08 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 failed 2806 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3005, waitTime=2214, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20147 ms, replay 2806 ops.
14/07/10 15:22:08 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 3530 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3005, waitTime=2214, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:21:20 PDT 2014, retrying after 10030 ms, replay 3530 ops.
14/07/10 15:22:09 INFO client.AsyncProcess: #5, table=usertable, attempt=13/35 failed 4236 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3024, waitTime=2186, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20190 ms, replay 4236 ops.
14/07/10 15:22:09 INFO client.AsyncProcess: #7, table=usertable, attempt=13/35 failed 4673 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3024, waitTime=2186, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20051 ms, replay 4673 ops.
14/07/10 15:22:09 INFO client.AsyncProcess: #18, table=usertable, attempt=13/35 failed 4695 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3020, waitTime=2094, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20001 ms, replay 4695 ops.
14/07/10 15:22:09 INFO client.AsyncProcess: #12, table=usertable, attempt=13/35 failed 3515 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3020, waitTime=2094, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20100 ms, replay 3515 ops.
14/07/10 15:22:10 INFO client.AsyncProcess: #4, table=usertable, attempt=13/35 failed 3541 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3020, waitTime=2094, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:20 PDT 2014, retrying after 20194 ms, replay 3541 ops.
14/07/10 15:22:10 INFO client.AsyncProcess: #3, table=usertable, attempt=13/35 failed 2862 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3020, waitTime=2094, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:20 PDT 2014, retrying after 20196 ms, replay 2862 ops.
2014-07-10 15:22:15:603 190 sec: 2396904 operations; 14695.5 current ops/sec; [INSERT AverageLatency(us)=587.76] 
14/07/10 15:22:19 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:21:20 PDT 2014
14/07/10 15:22:19 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:21:20 PDT 2014
14/07/10 15:22:20 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 4250 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3339, waitTime=2092, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:21:34 PDT 2014, retrying after 10059 ms, replay 4250 ops.
14/07/10 15:22:20 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 4204 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3339, waitTime=2092, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:21:35 PDT 2014, retrying after 10067 ms, replay 4204 ops.
14/07/10 15:22:20 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 4169 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3339, waitTime=2092, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:21:35 PDT 2014, retrying after 10068 ms, replay 4169 ops.
14/07/10 15:22:20 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2863 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3339, waitTime=2092, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:21:33 PDT 2014, retrying after 10041 ms, replay 2863 ops.
2014-07-10 15:22:25:604 200 sec: 2823678 operations; 42673.13 current ops/sec; [INSERT AverageLatency(us)=640.92] 
14/07/10 15:22:31 INFO client.AsyncProcess: #10, table=usertable, attempt=14/35 failed 3942 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3706, waitTime=3030, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:20 PDT 2014, retrying after 20030 ms, replay 3942 ops.
14/07/10 15:22:31 INFO client.AsyncProcess: #7, table=usertable, attempt=14/35 failed 4673 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3706, waitTime=3030, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20152 ms, replay 4673 ops.
14/07/10 15:22:31 INFO client.AsyncProcess: #18, table=usertable, attempt=14/35 failed 4695 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3706, waitTime=3030, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20180 ms, replay 4695 ops.
14/07/10 15:22:31 INFO client.AsyncProcess: #5, table=usertable, attempt=14/35 failed 4236 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3706, waitTime=3030, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20097 ms, replay 4236 ops.
14/07/10 15:22:31 INFO client.AsyncProcess: #20, table=usertable, attempt=14/35 failed 2806 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3706, waitTime=3030, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20140 ms, replay 2806 ops.
14/07/10 15:22:31 INFO client.AsyncProcess: #12, table=usertable, attempt=14/35 failed 3515 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3731, waitTime=2121, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20022 ms, replay 3515 ops.
14/07/10 15:22:33 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 4250 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3741, waitTime=2537, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:21:34 PDT 2014, retrying after 10073 ms, replay 4250 ops.
14/07/10 15:22:33 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 4169 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3741, waitTime=2537, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:21:35 PDT 2014, retrying after 10041 ms, replay 4169 ops.
14/07/10 15:22:33 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 2863 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3741, waitTime=2537, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:21:33 PDT 2014, retrying after 10042 ms, replay 2863 ops.
14/07/10 15:22:33 INFO client.AsyncProcess: #4, table=usertable, attempt=14/35 failed 3541 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3741, waitTime=2537, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:20 PDT 2014, retrying after 20021 ms, replay 3541 ops.
14/07/10 15:22:33 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 failed 4204 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3741, waitTime=2537, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:21:35 PDT 2014, retrying after 10095 ms, replay 4204 ops.
14/07/10 15:22:33 INFO client.AsyncProcess: #3, table=usertable, attempt=14/35 failed 2862 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3741, waitTime=2537, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:20 PDT 2014, retrying after 20053 ms, replay 2862 ops.
2014-07-10 15:22:35:604 210 sec: 3064109 operations; 24043.1 current ops/sec; [INSERT AverageLatency(us)=346.44] 
14/07/10 15:22:45 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 failed 2863 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4069, waitTime=2087, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:21:33 PDT 2014, retrying after 20124 ms, replay 2863 ops.
14/07/10 15:22:45 INFO client.AsyncProcess: #11, table=usertable, attempt=12/35 failed 4204 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4069, waitTime=2087, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:21:35 PDT 2014, retrying after 20028 ms, replay 4204 ops.
14/07/10 15:22:45 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 failed 4169 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4069, waitTime=2087, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:21:35 PDT 2014, retrying after 20118 ms, replay 4169 ops.
14/07/10 15:22:45 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 4250 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4069, waitTime=2087, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:21:34 PDT 2014, retrying after 20028 ms, replay 4250 ops.
2014-07-10 15:22:45:605 220 sec: 3389857 operations; 32571.54 current ops/sec; [INSERT AverageLatency(us)=225.99] 
14/07/10 15:22:54 INFO client.AsyncProcess: #12, table=usertable, attempt=15/35 failed 3515 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4277, waitTime=2825, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20105 ms, replay 3515 ops.
14/07/10 15:22:54 INFO client.AsyncProcess: #10, table=usertable, attempt=15/35 failed 3942 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4277, waitTime=2825, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:20 PDT 2014, retrying after 20072 ms, replay 3942 ops.
14/07/10 15:22:54 INFO client.AsyncProcess: #7, table=usertable, attempt=15/35 failed 4673 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4277, waitTime=2825, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20122 ms, replay 4673 ops.
14/07/10 15:22:54 INFO client.AsyncProcess: #18, table=usertable, attempt=15/35 failed 4695 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4277, waitTime=2825, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20017 ms, replay 4695 ops.
14/07/10 15:22:54 INFO client.AsyncProcess: #20, table=usertable, attempt=15/35 failed 2806 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4277, waitTime=2825, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20195 ms, replay 2806 ops.
14/07/10 15:22:54 INFO client.AsyncProcess: #5, table=usertable, attempt=15/35 failed 4236 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4277, waitTime=2825, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20133 ms, replay 4236 ops.
14/07/10 15:22:55 INFO client.AsyncProcess: #4, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:20 PDT 2014
14/07/10 15:22:55 INFO client.AsyncProcess: #3, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:20 PDT 2014
2014-07-10 15:22:55:605 230 sec: 3780910 operations; 39105.3 current ops/sec; [INSERT AverageLatency(us)=962.4] 
2014-07-10 15:23:05:654 240 sec: 3983581 operations; 20168.28 current ops/sec; [UPDATE AverageLatency(us)=6656302] [INSERT AverageLatency(us)=379.64] [CLEANUP AverageLatency(us)=6656481] 
14/07/10 15:23:07 INFO client.AsyncProcess: #9, table=usertable, attempt=13/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:21:33 PDT 2014
14/07/10 15:23:07 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 failed 4250 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4677, waitTime=2704, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:21:34 PDT 2014, retrying after 20114 ms, replay 4250 ops.
14/07/10 15:23:07 INFO client.AsyncProcess: #19, table=usertable, attempt=13/35 failed 4169 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4677, waitTime=2704, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:21:35 PDT 2014, retrying after 20159 ms, replay 4169 ops.
14/07/10 15:23:07 INFO client.AsyncProcess: #11, table=usertable, attempt=13/35 failed 4204 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4677, waitTime=2704, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:21:35 PDT 2014, retrying after 20032 ms, replay 4204 ops.
2014-07-10 15:23:15:655 250 sec: 4185682 operations; 20210.1 current ops/sec;  [INSERT AverageLatency(us)=802.73]  
14/07/10 15:23:18 INFO client.AsyncProcess: #10, table=usertable, attempt=16/35 failed 3942 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56564 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:20 PDT 2014, retrying after 20111 ms, replay 3942 ops.
14/07/10 15:23:18 INFO client.AsyncProcess: #5, table=usertable, attempt=16/35 failed 4236 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56564 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20080 ms, replay 4236 ops.
14/07/10 15:23:18 INFO client.AsyncProcess: #18, table=usertable, attempt=16/35 failed 4695 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56564 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20052 ms, replay 4695 ops.
14/07/10 15:23:18 INFO client.AsyncProcess: #12, table=usertable, attempt=16/35 failed 3515 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56564 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20163 ms, replay 3515 ops.
14/07/10 15:23:18 INFO client.AsyncProcess: #20, table=usertable, attempt=16/35 failed 2806 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56564 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20069 ms, replay 2806 ops.
14/07/10 15:23:18 INFO client.AsyncProcess: #7, table=usertable, attempt=16/35 failed 4673 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56564 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20026 ms, replay 4673 ops.
2014-07-10 15:23:25:655 260 sec: 4198054 operations; 1237.08 current ops/sec;  [INSERT AverageLatency(us)=5155.53]  
14/07/10 15:23:29 INFO client.AsyncProcess: #11, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:21:35 PDT 2014
14/07/10 15:23:29 INFO client.AsyncProcess: #2, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:21:34 PDT 2014
14/07/10 15:23:30 INFO client.AsyncProcess: #19, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:21:35 PDT 2014
2014-07-10 15:23:35:656 270 sec: 4542825 operations; 34477.1 current ops/sec; [UPDATE AverageLatency(us)=16603923] [INSERT AverageLatency(us)=1060.9] [CLEANUP AverageLatency(us)=16604779] 
14/07/10 15:23:40 INFO client.AsyncProcess: #10, table=usertable, attempt=17/35 failed 3942 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56564 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:20 PDT 2014, retrying after 20113 ms, replay 3942 ops.
14/07/10 15:23:40 INFO client.AsyncProcess: #20, table=usertable, attempt=17/35 failed 2806 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56564 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20063 ms, replay 2806 ops.
14/07/10 15:23:40 INFO client.AsyncProcess: #18, table=usertable, attempt=17/35 failed 4695 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56564 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20001 ms, replay 4695 ops.
14/07/10 15:23:40 INFO client.AsyncProcess: #12, table=usertable, attempt=17/35 failed 3515 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56564 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20194 ms, replay 3515 ops.
14/07/10 15:23:40 INFO client.AsyncProcess: #7, table=usertable, attempt=17/35 failed 4673 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56564 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20099 ms, replay 4673 ops.
14/07/10 15:23:40 INFO client.AsyncProcess: #5, table=usertable, attempt=17/35 failed 4236 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56564 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20079 ms, replay 4236 ops.
2014-07-10 15:23:45:656 280 sec: 4620759 operations; 7792.62 current ops/sec;  [INSERT AverageLatency(us)=387.56]  
14/07/10 15:23:46 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 3490 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56564 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:22:55 PDT 2014, retrying after 10066 ms, replay 3490 ops.
2014-07-10 15:23:55:657 290 sec: 4620759 operations; 0 current ops/sec;    
14/07/10 15:23:59 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 3490 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5763, waitTime=3141, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:22:55 PDT 2014, retrying after 10094 ms, replay 3490 ops.
14/07/10 15:24:02 INFO client.AsyncProcess: #10, table=usertable, attempt=18/35 failed 3942 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5778, waitTime=2917, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:20 PDT 2014, retrying after 20012 ms, replay 3942 ops.
14/07/10 15:24:02 INFO client.AsyncProcess: #5, table=usertable, attempt=18/35 failed 4236 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5778, waitTime=2917, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20184 ms, replay 4236 ops.
14/07/10 15:24:02 INFO client.AsyncProcess: #20, table=usertable, attempt=18/35 failed 2806 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5778, waitTime=2917, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20126 ms, replay 2806 ops.
14/07/10 15:24:02 INFO client.AsyncProcess: #7, table=usertable, attempt=18/35 failed 4673 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5778, waitTime=2917, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20168 ms, replay 4673 ops.
14/07/10 15:24:02 INFO client.AsyncProcess: #18, table=usertable, attempt=18/35 failed 4695 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5778, waitTime=2917, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20150 ms, replay 4695 ops.
14/07/10 15:24:03 INFO client.AsyncProcess: #12, table=usertable, attempt=18/35 failed 3515 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5802, waitTime=2892, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20109 ms, replay 3515 ops.
2014-07-10 15:24:05:657 300 sec: 4620759 operations; 0 current ops/sec;    
14/07/10 15:24:12 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 failed 3490 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=5935, waitTime=3072, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:22:55 PDT 2014, retrying after 20051 ms, replay 3490 ops.
2014-07-10 15:24:15:658 310 sec: 4900781 operations; 27999.4 current ops/sec;  [INSERT AverageLatency(us)=1336.85]  
14/07/10 15:24:25 INFO client.AsyncProcess: #10, table=usertable, attempt=19/35 failed 3942 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6392, waitTime=2663, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:20 PDT 2014, retrying after 20070 ms, replay 3942 ops.
14/07/10 15:24:25 INFO client.AsyncProcess: #20, table=usertable, attempt=19/35 failed 2806 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6392, waitTime=2663, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20199 ms, replay 2806 ops.
14/07/10 15:24:25 INFO client.AsyncProcess: #7, table=usertable, attempt=19/35 failed 4673 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6392, waitTime=2663, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20190 ms, replay 4673 ops.
14/07/10 15:24:25 INFO client.AsyncProcess: #18, table=usertable, attempt=19/35 failed 4695 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6392, waitTime=2663, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20191 ms, replay 4695 ops.
14/07/10 15:24:25 INFO client.AsyncProcess: #5, table=usertable, attempt=19/35 failed 4236 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6392, waitTime=2663, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20172 ms, replay 4236 ops.
2014-07-10 15:24:25:658 320 sec: 5108134 operations; 20735.3 current ops/sec;  [INSERT AverageLatency(us)=231.27]  
14/07/10 15:24:25 INFO client.AsyncProcess: #12, table=usertable, attempt=19/35 failed 3515 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6425, waitTime=2174, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20085 ms, replay 3515 ops.
14/07/10 15:24:28 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2809 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6492, waitTime=2207, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:23:35 PDT 2014, retrying after 10034 ms, replay 2809 ops.
14/07/10 15:24:28 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 4669 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6492, waitTime=2207, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:23:35 PDT 2014, retrying after 10028 ms, replay 4669 ops.
2014-07-10 15:24:35:659 330 sec: 5374265 operations; 26610.44 current ops/sec;  [INSERT AverageLatency(us)=383.7]  
14/07/10 15:24:35 INFO client.AsyncProcess: #4, table=usertable, attempt=13/35 failed 3490 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56564 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:22:55 PDT 2014, retrying after 20116 ms, replay 3490 ops.
14/07/10 15:24:40 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:23:35 PDT 2014
14/07/10 15:24:41 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 4669 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=6816, waitTime=2575, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:23:35 PDT 2014, retrying after 10059 ms, replay 4669 ops.
14/07/10 15:24:44 INFO client.AsyncProcess: #17, waiting for some tasks to finish. Expected max=0, tasksSent=665, tasksDone=664, currentTasksDone=664, retries=122 hasError=false, tableName=usertable
2014-07-10 15:24:45:659 340 sec: 5538079 operations; 16381.4 current ops/sec;  [INSERT AverageLatency(us)=1011.73]  
14/07/10 15:24:49 INFO client.AsyncProcess: #10, table=usertable, attempt=20/35 failed 3942 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56564 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:20 PDT 2014, retrying after 20086 ms, replay 3942 ops.
14/07/10 15:24:49 INFO client.AsyncProcess: #12, table=usertable, attempt=20/35 failed 3515 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56564 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20094 ms, replay 3515 ops.
14/07/10 15:24:49 INFO client.AsyncProcess: #5, table=usertable, attempt=20/35 failed 4236 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56564 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20061 ms, replay 4236 ops.
14/07/10 15:24:49 INFO client.AsyncProcess: #20, table=usertable, attempt=20/35 failed 2806 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56564 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20056 ms, replay 2806 ops.
14/07/10 15:24:49 INFO client.AsyncProcess: #18, table=usertable, attempt=20/35 failed 4695 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56564 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20008 ms, replay 4695 ops.
14/07/10 15:24:49 INFO client.AsyncProcess: #7, table=usertable, attempt=20/35 failed 4673 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56564 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20004 ms, replay 4673 ops.
14/07/10 15:24:53 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 4669 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7144, waitTime=2001, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:23:35 PDT 2014, retrying after 20171 ms, replay 4669 ops.
2014-07-10 15:24:55:660 350 sec: 5613132 operations; 7504.55 current ops/sec; [UPDATE AverageLatency(us)=9555355] [INSERT AverageLatency(us)=685.34] [CLEANUP AverageLatency(us)=9555366] 
14/07/10 15:24:56 INFO client.AsyncProcess: #4, table=usertable, attempt=14/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:22:55 PDT 2014
14/07/10 15:24:58 INFO client.AsyncProcess: #17, waiting for some tasks to finish. Expected max=0, tasksSent=668, tasksDone=667, currentTasksDone=667, retries=125 hasError=false, tableName=usertable
2014-07-10 15:25:05:660 360 sec: 6142412 operations; 52928 current ops/sec; [UPDATE AverageLatency(us)=26914617] [INSERT AverageLatency(us)=458.66] [CLEANUP AverageLatency(us)=26914628] 
14/07/10 15:25:12 INFO client.AsyncProcess: #5, table=usertable, attempt=21/35 failed 4236 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7631, waitTime=3455, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20109 ms, replay 4236 ops.
14/07/10 15:25:12 INFO client.AsyncProcess: #12, table=usertable, attempt=21/35 failed 3515 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7631, waitTime=3455, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20199 ms, replay 3515 ops.
14/07/10 15:25:12 INFO client.AsyncProcess: #10, table=usertable, attempt=21/35 failed 3942 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7631, waitTime=3455, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:20 PDT 2014, retrying after 20131 ms, replay 3942 ops.
14/07/10 15:25:12 INFO client.AsyncProcess: #18, table=usertable, attempt=21/35 failed 4695 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7631, waitTime=3455, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20141 ms, replay 4695 ops.
14/07/10 15:25:12 INFO client.AsyncProcess: #20, table=usertable, attempt=21/35 failed 2806 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7631, waitTime=3455, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20018 ms, replay 2806 ops.
14/07/10 15:25:12 INFO client.AsyncProcess: #7, table=usertable, attempt=21/35 failed 4673 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7631, waitTime=3455, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014, retrying after 20044 ms, replay 4673 ops.
2014-07-10 15:25:15:661 370 sec: 6150528 operations; 811.52 current ops/sec;  [INSERT AverageLatency(us)=301.5]  
14/07/10 15:25:16 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 failed 4669 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=7703, waitTime=2514, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:23:35 PDT 2014, retrying after 20082 ms, replay 4669 ops.
2014-07-10 15:25:25:661 380 sec: 6459617 operations; 30908.9 current ops/sec; [UPDATE AverageLatency(us)=9265731] [INSERT AverageLatency(us)=500.93] [CLEANUP AverageLatency(us)=9265742.5] 
14/07/10 15:25:32 INFO client.AsyncProcess: #20, table=usertable, attempt=22/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014
14/07/10 15:25:33 INFO client.AsyncProcess: #7, table=usertable, attempt=22/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014
14/07/10 15:25:33 INFO client.AsyncProcess: #12, table=usertable, attempt=22/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014
14/07/10 15:25:33 INFO client.AsyncProcess: #18, table=usertable, attempt=22/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014
14/07/10 15:25:34 INFO client.AsyncProcess: #5, table=usertable, attempt=22/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:19 PDT 2014
14/07/10 15:25:34 INFO client.AsyncProcess: #10, table=usertable, attempt=22/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:20:20 PDT 2014
2014-07-10 15:25:35:762 390 sec: 6901923 operations; 43788.34 current ops/sec; [UPDATE AverageLatency(us)=4183174] [INSERT AverageLatency(us)=4162.96] [CLEANUP AverageLatency(us)=4183184] 
14/07/10 15:25:39 INFO client.AsyncProcess: #2, table=usertable, attempt=14/35 failed 4669 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=8443, waitTime=3181, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:23:35 PDT 2014, retrying after 20087 ms, replay 4669 ops.
2014-07-10 15:25:45:762 400 sec: 7172401 operations; 27047.8 current ops/sec; [UPDATE AverageLatency(us)=4212240] [INSERT AverageLatency(us)=287.57] [CLEANUP AverageLatency(us)=4212250.5] 
2014-07-10 15:25:55:807 410 sec: 7375462 operations; 20215.13 current ops/sec; [UPDATE AverageLatency(us)=10876094] [INSERT AverageLatency(us)=529.61] [CLEANUP AverageLatency(us)=10876108] 
14/07/10 15:26:01 INFO client.AsyncProcess: #2, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405058803712, tracking started Thu Jul 10 15:23:35 PDT 2014
2014-07-10 15:26:05:808 420 sec: 7794873 operations; 41936.91 current ops/sec; [UPDATE AverageLatency(us)=1201749] [INSERT AverageLatency(us)=446.88] [CLEANUP AverageLatency(us)=1201761] 
2014-07-10 15:26:15:808 430 sec: 7794873 operations; 0 current ops/sec;    
2014-07-10 15:26:26:208 440 sec: 8111455 operations; 30440.58 current ops/sec;  [INSERT AverageLatency(us)=589.97]  
2014-07-10 15:26:36:208 450 sec: 8506367 operations; 39491.2 current ops/sec; [UPDATE AverageLatency(us)=1948243] [INSERT AverageLatency(us)=159.22] [CLEANUP AverageLatency(us)=1948255] 
2014-07-10 15:26:46:209 460 sec: 8667529 operations; 16114.59 current ops/sec;  [INSERT AverageLatency(us)=623.82]  
2014-07-10 15:26:56:209 470 sec: 8777358 operations; 10982.9 current ops/sec;  [INSERT AverageLatency(us)=739.8]  
2014-07-10 15:27:06:210 480 sec: 9041570 operations; 26418.56 current ops/sec;  [INSERT AverageLatency(us)=149.16]  
2014-07-10 15:27:16:210 490 sec: 9303783 operations; 26221.3 current ops/sec; [UPDATE AverageLatency(us)=6462309] [INSERT AverageLatency(us)=361.05] [CLEANUP AverageLatency(us)=6462320] 
2014-07-10 15:27:26:211 500 sec: 9713633 operations; 40980.9 current ops/sec; [UPDATE AverageLatency(us)=1068054.67] [INSERT AverageLatency(us)=115.79] [CLEANUP AverageLatency(us)=1068066] 
2014-07-10 15:27:36:212 510 sec: 9885759 operations; 17210.88 current ops/sec; [UPDATE AverageLatency(us)=713904] [INSERT AverageLatency(us)=170.3] [CLEANUP AverageLatency(us)=713916] 
2014-07-10 15:27:40:203 514 sec: 10000000 operations; 28624.66 current ops/sec; [UPDATE AverageLatency(us)=474033.5] [INSERT AverageLatency(us)=53.8] [CLEANUP AverageLatency(us)=474044.5] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1405031260
1405031260
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ false
+ false
+ false
+ false
+ false
+ false
+ false
+ false
+ let counter=1+1
+ read line
+ set +x
