++ ls caseresult/ -ltr
++ wc -l
+ filename=case65
+ mkdir caseresult/case65
+ ssh hadoop@master mkdir /home/hadoop/git/physical_design/caseresult/case65
+ RESULT_DIR=/home/hadoop/git/physical_design/caseresult/case65
+ TEN=10
+ SIXTY=60
+ SLEEP_TIME=300
+ YCSB_DIR=/home/hadoop/ycsb-0.1.4
+ number_of_operations=10000000
+ number_of_threads=20
+ number_of_records=10000000
+ output_file_suffix=.dat
+ experiment_list_file=/home/hadoop/git/physical_design/case65.list
+ clean=false
+ create=false
+ load=false
+ random_read=false
+ workloada=false
+ workloadb=false
+ workloadc=false
+ scan=false
+ all=false
+ for i in '$@'
+ '[' clean == all ']'
+ '[' clean == clean ']'
+ clean=true
+ for i in '$@'
+ '[' create == all ']'
+ '[' create == clean ']'
+ '[' create == create ']'
+ create=true
+ for i in '$@'
+ '[' load == all ']'
+ '[' load == clean ']'
+ '[' load == create ']'
+ '[' load == load ']'
+ load=true
+ let counter=1
+ cd /home/hadoop/ycsb-0.1.4
++ pwd
+ echo /home/hadoop/ycsb-0.1.4
/home/hadoop/ycsb-0.1.4
+ read line
+ false
+ true
+ echo 'sleeping for 60 ...'
sleeping for 60 ...
+ sleep 60
+ echo 'droping usertable...'
droping usertable...
+ ssh hadoop@master /home/hadoop/hbase/bin/hbase shell /home/hadoop/git/physical_design/delete_table
0 row(s) in 2.7190 seconds

0 row(s) in 0.7650 seconds

0 row(s) in 0.0780 seconds

+ echo 'sleeping for 300 ...'
sleeping for 300 ...
+ sleep 300
+ false
+ true
+ echo 'creating usertable...'
creating usertable...
+ create_statement='create '\''usertable'\'', { NAME=>'\''family'\'', CONFIGURATION => { '\''hbase.hregion.majorcompaction'\'' => '\''0'\'' } ,  COMPRESSION=>'\''GZ'\''}, SPLITS => ['\''user1'\'', '\''user2'\'', '\''user3'\'', '\''user4'\'', '\''user5'\'', '\''user6'\'', '\''user7'\'', '\''user8'\'', '\''user9'\'']'
+ echo create ''\''usertable'\'',' '{' 'NAME=>'\''family'\'',' CONFIGURATION '=>' '{' ''\''hbase.hregion.majorcompaction'\''' '=>' ''\''0'\''' '}' , 'COMPRESSION=>'\''GZ'\''},' SPLITS '=>' '['\''user1'\'',' ''\''user2'\'',' ''\''user3'\'',' ''\''user4'\'',' ''\''user5'\'',' ''\''user6'\'',' ''\''user7'\'',' ''\''user8'\'',' ''\''user9'\'']'
+ echo 'exit '
+ scp /home/hadoop/git/physical_design/caseresult/case65/create_1.script hadoop@master:/home/hadoop/git/physical_design/caseresult/case65/create_1.script
+ create_table /home/hadoop/git/physical_design/caseresult/case65/create_1.script
+ echo 'creating table...'
creating table...
+ echo /home/hadoop/git/physical_design/caseresult/case65/create_1.script
/home/hadoop/git/physical_design/caseresult/case65/create_1.script
+ ssh hadoop@master /home/hadoop/hbase/bin/hbase shell /home/hadoop/git/physical_design/caseresult/case65/create_1.script
0 row(s) in 1.7440 seconds

+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ false
+ true
+ echo 'loading data...'
loading data...
+ echo 'starting time: '
starting time: 
++ date +%s
+ echo 1405026463
1405026463
++ echo /home/hadoop/git/physical_design/caseresult/case65/load_1.dat
+ ./ld 10000000 20 /home/hadoop/git/physical_design/caseresult/case65/load_1.dat
Loading workload...
Starting test.
2014-07-10 14:07:44:357 0 sec: 0 operations; 
14/07/10 14:07:44 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
14/07/10 14:07:44 INFO zookeeper.ZooKeeper: Client environment:host.name=sceplus-vm43.almaden.ibm.com
14/07/10 14:07:44 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_31
14/07/10 14:07:44 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
14/07/10 14:07:44 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre
14/07/10 14:07:44 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/home/hadoop/ycsb-0.1.4/hbase-binding/lib/hbase-binding-0.1.4.jar:/home/hadoop/ycsb-0.1.4/hbase-binding/conf:/home/hadoop/ycsb-0.1.4/core/lib/core-0.1.4.jar:/home/hadoop/ycsb-0.1.4/jdbc-binding/conf
14/07/10 14:07:44 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/jni:/lib:/usr/lib
14/07/10 14:07:44 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
14/07/10 14:07:44 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
14/07/10 14:07:44 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
14/07/10 14:07:44 INFO zookeeper.ZooKeeper: Client environment:os.arch=amd64
14/07/10 14:07:44 INFO zookeeper.ZooKeeper: Client environment:os.version=3.13.0-24-generic
14/07/10 14:07:44 INFO zookeeper.ZooKeeper: Client environment:user.name=hadoop
14/07/10 14:07:44 INFO zookeeper.ZooKeeper: Client environment:user.home=/home/hadoop
14/07/10 14:07:44 INFO zookeeper.ZooKeeper: Client environment:user.dir=/home/hadoop/ycsb-0.1.4
14/07/10 14:07:44 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181 sessionTimeout=90000 watcher=hconnection-0x3588d364, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, baseZNode=/hbase
14/07/10 14:07:44 INFO zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x3588d364 connecting to ZooKeeper ensemble=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181
14/07/10 14:07:44 INFO zookeeper.ClientCnxn: Opening socket connection to server master/9.1.143.58:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/10 14:07:44 INFO zookeeper.ClientCnxn: Socket connection established to master/9.1.143.58:2181, initiating session
14/07/10 14:07:44 INFO zookeeper.ClientCnxn: Session establishment complete on server master/9.1.143.58:2181, sessionid = 0x4723c67190000e, negotiated timeout = 90000
2014-07-10 14:07:54:358 10 sec: 306202 operations; 30617.14 current ops/sec; [INSERT AverageLatency(us)=489.06] 
2014-07-10 14:08:04:359 20 sec: 338092 operations; 3188.68 current ops/sec; [INSERT AverageLatency(us)=179.13] 
2014-07-10 14:08:14:360 30 sec: 338092 operations; 0 current ops/sec;  
2014-07-10 14:08:24:360 40 sec: 538090 operations; 19999.8 current ops/sec; [INSERT AverageLatency(us)=1072.81] 
2014-07-10 14:08:34:361 50 sec: 788908 operations; 25079.29 current ops/sec; [INSERT AverageLatency(us)=720.04] 
2014-07-10 14:08:44:361 60 sec: 788908 operations; 0 current ops/sec;  
14/07/10 14:08:50 INFO zookeeper.ClientCnxn: Unable to read additional data from server sessionid 0x4723c67190000e, likely server has closed socket, closing socket connection and attempting reconnect
14/07/10 14:08:51 INFO zookeeper.ClientCnxn: Opening socket connection to server slave1/9.1.143.59:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/10 14:08:51 INFO zookeeper.ClientCnxn: Socket connection established to slave1/9.1.143.59:2181, initiating session
14/07/10 14:08:51 INFO zookeeper.ClientCnxn: Session establishment complete on server slave1/9.1.143.59:2181, sessionid = 0x4723c67190000e, negotiated timeout = 90000
14/07/10 14:08:53 INFO zookeeper.ClientCnxn: Unable to read additional data from server sessionid 0x4723c67190000e, likely server has closed socket, closing socket connection and attempting reconnect
14/07/10 14:08:53 INFO zookeeper.ClientCnxn: Opening socket connection to server master/9.1.143.58:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/10 14:08:53 INFO zookeeper.ClientCnxn: Socket connection established to master/9.1.143.58:2181, initiating session
14/07/10 14:08:53 INFO zookeeper.ClientCnxn: Unable to read additional data from server sessionid 0x4723c67190000e, likely server has closed socket, closing socket connection and attempting reconnect
14/07/10 14:08:54 INFO client.AsyncProcess: #20, table=usertable, attempt=10/35 failed 2284 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56376 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:51 PDT 2014, retrying after 10092 ms, replay 2284 ops.
14/07/10 14:08:54 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2273 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56376 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 10018 ms, replay 2273 ops.
14/07/10 14:08:54 INFO client.AsyncProcess: #9, table=usertable, attempt=10/35 failed 2242 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56376 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 10065 ms, replay 2242 ops.
14/07/10 14:08:54 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2219 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56376 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:53 PDT 2014, retrying after 10033 ms, replay 2219 ops.
14/07/10 14:08:54 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 2255 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56376 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:53 PDT 2014, retrying after 10036 ms, replay 2255 ops.
2014-07-10 14:08:54:362 70 sec: 788908 operations; 0 current ops/sec;  
14/07/10 14:08:54 INFO zookeeper.ClientCnxn: Opening socket connection to server slave1/9.1.143.59:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/10 14:08:54 INFO zookeeper.ClientCnxn: Socket connection established to slave1/9.1.143.59:2181, initiating session
14/07/10 14:08:54 INFO zookeeper.ClientCnxn: Unable to read additional data from server sessionid 0x4723c67190000e, likely server has closed socket, closing socket connection and attempting reconnect
14/07/10 14:08:54 WARN zookeeper.RecoverableZooKeeper: Possibly transient ZooKeeper, quorum=sceplus-vm49.almaden.ibm.com:2181,sceplus-vm48.almaden.ibm.com:2181, exception=org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase/meta-region-server
14/07/10 14:08:54 INFO util.RetryCounter: Sleeping 1000ms before retry #0...
14/07/10 14:08:55 INFO zookeeper.ClientCnxn: Opening socket connection to server master/9.1.143.58:2181. Will not attempt to authenticate using SASL (unknown error)
14/07/10 14:08:55 INFO zookeeper.ClientCnxn: Socket connection established to master/9.1.143.58:2181, initiating session
14/07/10 14:08:55 INFO zookeeper.ClientCnxn: Session establishment complete on server master/9.1.143.58:2181, sessionid = 0x4723c67190000e, negotiated timeout = 90000
14/07/10 14:08:56 INFO client.AsyncProcess: #7, table=usertable, attempt=10/35 failed 2292 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56376 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 10069 ms, replay 2292 ops.
14/07/10 14:08:56 INFO client.AsyncProcess: #15, table=usertable, attempt=10/35 failed 2279 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56376 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 10047 ms, replay 2279 ops.
14/07/10 14:08:56 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2311 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56376 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 10010 ms, replay 2311 ops.
14/07/10 14:08:56 INFO client.AsyncProcess: #5, table=usertable, attempt=10/35 failed 2275 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56376 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 10089 ms, replay 2275 ops.
14/07/10 14:08:56 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2225 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56376 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 10050 ms, replay 2225 ops.
2014-07-10 14:09:04:362 80 sec: 788908 operations; 0 current ops/sec;  
14/07/10 14:09:08 INFO client.AsyncProcess: #20, table=usertable, attempt=11/35 failed 2284 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56376 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:51 PDT 2014, retrying after 10038 ms, replay 2284 ops.
14/07/10 14:09:08 INFO client.AsyncProcess: #9, table=usertable, attempt=11/35 failed 2242 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56376 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 10016 ms, replay 2242 ops.
14/07/10 14:09:08 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 failed 2273 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56376 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 10020 ms, replay 2273 ops.
14/07/10 14:09:08 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 2255 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56376 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:53 PDT 2014, retrying after 10031 ms, replay 2255 ops.
14/07/10 14:09:08 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 failed 2219 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56376 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:53 PDT 2014, retrying after 10080 ms, replay 2219 ops.
14/07/10 14:09:10 INFO client.AsyncProcess: #15, table=usertable, attempt=11/35 failed 2279 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56376 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 10006 ms, replay 2279 ops.
14/07/10 14:09:10 INFO client.AsyncProcess: #7, table=usertable, attempt=11/35 failed 2292 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56376 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 10048 ms, replay 2292 ops.
14/07/10 14:09:10 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 failed 2225 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56376 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 10094 ms, replay 2225 ops.
14/07/10 14:09:10 INFO client.AsyncProcess: #5, table=usertable, attempt=11/35 failed 2275 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56376 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 10099 ms, replay 2275 ops.
14/07/10 14:09:10 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 2311 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56376 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 10030 ms, replay 2311 ops.
2014-07-10 14:09:14:362 90 sec: 788908 operations; 0 current ops/sec;  
14/07/10 14:09:20 INFO client.AsyncProcess: #20, table=usertable, attempt=12/35 failed 2284 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=930, waitTime=2310, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:51 PDT 2014, retrying after 20190 ms, replay 2284 ops.
14/07/10 14:09:20 INFO client.AsyncProcess: #6, table=usertable, attempt=12/35 failed 2273 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=930, waitTime=2310, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20052 ms, replay 2273 ops.
14/07/10 14:09:20 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 failed 2255 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=930, waitTime=2310, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:53 PDT 2014, retrying after 20126 ms, replay 2255 ops.
14/07/10 14:09:20 INFO client.AsyncProcess: #9, table=usertable, attempt=12/35 failed 2242 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=930, waitTime=2310, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20101 ms, replay 2242 ops.
14/07/10 14:09:20 INFO client.AsyncProcess: #13, table=usertable, attempt=12/35 failed 2219 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=930, waitTime=2310, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:53 PDT 2014, retrying after 20176 ms, replay 2219 ops.
14/07/10 14:09:22 INFO client.AsyncProcess: #16, table=usertable, attempt=12/35 failed 2225 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=936, waitTime=2498, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20190 ms, replay 2225 ops.
14/07/10 14:09:22 INFO client.AsyncProcess: #15, table=usertable, attempt=12/35 failed 2279 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=936, waitTime=2498, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20041 ms, replay 2279 ops.
14/07/10 14:09:22 INFO client.AsyncProcess: #5, table=usertable, attempt=12/35 failed 2275 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=936, waitTime=2498, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20067 ms, replay 2275 ops.
14/07/10 14:09:22 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 failed 2311 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=936, waitTime=2498, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20010 ms, replay 2311 ops.
14/07/10 14:09:22 INFO client.AsyncProcess: #7, table=usertable, attempt=12/35 failed 2292 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=936, waitTime=2498, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20054 ms, replay 2292 ops.
2014-07-10 14:09:24:363 100 sec: 788908 operations; 0 current ops/sec;  
14/07/10 14:09:33 INFO client.AsyncProcess: #19, table=usertable, attempt=10/35 failed 2253 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=976, waitTime=2542, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:26 PDT 2014, retrying after 10093 ms, replay 2253 ops.
2014-07-10 14:09:34:363 110 sec: 788908 operations; 0 current ops/sec;  
14/07/10 14:09:38 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2250 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=990, waitTime=2027, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:27 PDT 2014, retrying after 10051 ms, replay 2250 ops.
14/07/10 14:09:38 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2253 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=990, waitTime=2027, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:27 PDT 2014, retrying after 10028 ms, replay 2253 ops.
14/07/10 14:09:38 INFO client.AsyncProcess: #12, table=usertable, attempt=10/35 failed 2259 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=990, waitTime=2027, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:27 PDT 2014, retrying after 10097 ms, replay 2259 ops.
14/07/10 14:09:38 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2255 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=990, waitTime=2027, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:27 PDT 2014, retrying after 10091 ms, replay 2255 ops.
14/07/10 14:09:40 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2283 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1003, waitTime=2077, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:31 PDT 2014, retrying after 10083 ms, replay 2283 ops.
14/07/10 14:09:42 INFO client.AsyncProcess: #20, table=usertable, attempt=13/35 failed 2284 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1009, waitTime=2641, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:51 PDT 2014, retrying after 20045 ms, replay 2284 ops.
14/07/10 14:09:42 INFO client.AsyncProcess: #11, table=usertable, attempt=10/35 failed 2255 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1009, waitTime=2641, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:29 PDT 2014, retrying after 10086 ms, replay 2255 ops.
14/07/10 14:09:42 INFO client.AsyncProcess: #4, table=usertable, attempt=10/35 failed 2259 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1009, waitTime=2641, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:29 PDT 2014, retrying after 10068 ms, replay 2259 ops.
14/07/10 14:09:42 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2247 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1009, waitTime=2641, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:29 PDT 2014, retrying after 10003 ms, replay 2247 ops.
14/07/10 14:09:42 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2249 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1009, waitTime=2641, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:29 PDT 2014, retrying after 10048 ms, replay 2249 ops.
14/07/10 14:09:42 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2263 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1009, waitTime=2641, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:30 PDT 2014, retrying after 10085 ms, replay 2263 ops.
14/07/10 14:09:42 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2243 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1009, waitTime=2641, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:30 PDT 2014, retrying after 10034 ms, replay 2243 ops.
14/07/10 14:09:42 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2242 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1009, waitTime=2641, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:30 PDT 2014, retrying after 10036 ms, replay 2242 ops.
14/07/10 14:09:42 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2266 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1009, waitTime=2641, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:31 PDT 2014, retrying after 10090 ms, replay 2266 ops.
14/07/10 14:09:42 INFO client.AsyncProcess: #7, table=usertable, attempt=13/35 failed 2255 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1009, waitTime=2641, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:53 PDT 2014, retrying after 20183 ms, replay 2255 ops.
14/07/10 14:09:42 INFO client.AsyncProcess: #9, table=usertable, attempt=13/35 failed 2242 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1009, waitTime=2641, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20167 ms, replay 2242 ops.
14/07/10 14:09:42 INFO client.AsyncProcess: #13, table=usertable, attempt=13/35 failed 2219 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1009, waitTime=2641, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:53 PDT 2014, retrying after 20141 ms, replay 2219 ops.
14/07/10 14:09:42 INFO client.AsyncProcess: #6, table=usertable, attempt=13/35 failed 2273 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1009, waitTime=2641, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20029 ms, replay 2273 ops.
2014-07-10 14:09:44:364 120 sec: 821780 operations; 3286.87 current ops/sec; [INSERT AverageLatency(us)=6766.44] 
14/07/10 14:09:45 INFO client.AsyncProcess: #7, table=usertable, attempt=13/35 failed 2292 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1030, waitTime=2838, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20191 ms, replay 2292 ops.
14/07/10 14:09:45 INFO client.AsyncProcess: #15, table=usertable, attempt=13/35 failed 2279 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1030, waitTime=2838, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20051 ms, replay 2279 ops.
14/07/10 14:09:45 INFO client.AsyncProcess: #5, table=usertable, attempt=13/35 failed 2275 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1030, waitTime=2838, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20095 ms, replay 2275 ops.
14/07/10 14:09:45 INFO client.AsyncProcess: #19, table=usertable, attempt=11/35 failed 2253 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1030, waitTime=2838, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:26 PDT 2014, retrying after 10023 ms, replay 2253 ops.
14/07/10 14:09:45 INFO client.AsyncProcess: #3, table=usertable, attempt=13/35 failed 2311 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1030, waitTime=2838, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20000 ms, replay 2311 ops.
14/07/10 14:09:45 INFO client.AsyncProcess: #16, table=usertable, attempt=13/35 failed 2225 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1030, waitTime=2838, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20128 ms, replay 2225 ops.
14/07/10 14:09:49 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:27 PDT 2014
14/07/10 14:09:49 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:27 PDT 2014
14/07/10 14:09:49 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:27 PDT 2014
14/07/10 14:09:49 INFO client.AsyncProcess: #12, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:27 PDT 2014
14/07/10 14:09:51 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:31 PDT 2014
2014-07-10 14:09:54:374 130 sec: 990836 operations; 16888.71 current ops/sec; [INSERT AverageLatency(us)=1696.98] 
14/07/10 14:09:55 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 2242 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1116, waitTime=2745, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:30 PDT 2014, retrying after 10074 ms, replay 2242 ops.
14/07/10 14:09:55 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 failed 2249 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1116, waitTime=2745, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:29 PDT 2014, retrying after 10094 ms, replay 2249 ops.
14/07/10 14:09:55 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 2266 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1116, waitTime=2745, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:31 PDT 2014, retrying after 10019 ms, replay 2266 ops.
14/07/10 14:09:55 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 2247 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1116, waitTime=2745, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:29 PDT 2014, retrying after 10048 ms, replay 2247 ops.
14/07/10 14:09:55 INFO client.AsyncProcess: #4, table=usertable, attempt=11/35 failed 2259 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1116, waitTime=2745, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:29 PDT 2014, retrying after 10047 ms, replay 2259 ops.
14/07/10 14:09:55 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 2263 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1116, waitTime=2745, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:30 PDT 2014, retrying after 10070 ms, replay 2263 ops.
14/07/10 14:09:55 INFO client.AsyncProcess: #11, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:29 PDT 2014
14/07/10 14:09:55 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 failed 2243 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1116, waitTime=2745, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:30 PDT 2014, retrying after 10091 ms, replay 2243 ops.
14/07/10 14:09:56 INFO client.AsyncProcess: #19, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:26 PDT 2014
2014-07-10 14:10:04:375 140 sec: 1122324 operations; 13147.49 current ops/sec; [INSERT AverageLatency(us)=1744.55] 
14/07/10 14:10:05 INFO client.AsyncProcess: #6, table=usertable, attempt=14/35 failed 2273 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56376 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20005 ms, replay 2273 ops.
14/07/10 14:10:05 INFO client.AsyncProcess: #13, table=usertable, attempt=14/35 failed 2219 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56376 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:53 PDT 2014, retrying after 20157 ms, replay 2219 ops.
14/07/10 14:10:05 INFO client.AsyncProcess: #9, table=usertable, attempt=14/35 failed 2242 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56376 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20141 ms, replay 2242 ops.
14/07/10 14:10:05 INFO client.AsyncProcess: #7, table=usertable, attempt=14/35 failed 2255 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56376 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:53 PDT 2014, retrying after 20154 ms, replay 2255 ops.
14/07/10 14:10:05 INFO client.AsyncProcess: #20, table=usertable, attempt=14/35 failed 2284 ops, last exception: java.net.SocketTimeoutException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed because java.net.SocketTimeoutException: 2000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/9.1.143.53:56376 remote=sceplus-vm48.almaden.ibm.com/9.1.143.58:60020] on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:51 PDT 2014, retrying after 20114 ms, replay 2284 ops.
14/07/10 14:10:08 INFO client.AsyncProcess: #16, table=usertable, attempt=14/35 failed 2225 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1205, waitTime=2580, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20126 ms, replay 2225 ops.
14/07/10 14:10:08 INFO client.AsyncProcess: #4, table=usertable, attempt=12/35 failed 2259 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1205, waitTime=2580, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:29 PDT 2014, retrying after 20104 ms, replay 2259 ops.
14/07/10 14:10:08 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 failed 2243 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1205, waitTime=2580, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:30 PDT 2014, retrying after 20006 ms, replay 2243 ops.
14/07/10 14:10:08 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 failed 2266 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1205, waitTime=2580, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:31 PDT 2014, retrying after 20136 ms, replay 2266 ops.
14/07/10 14:10:08 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 failed 2242 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1205, waitTime=2580, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:30 PDT 2014, retrying after 20134 ms, replay 2242 ops.
14/07/10 14:10:08 INFO client.AsyncProcess: #2, table=usertable, attempt=12/35 failed 2249 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1205, waitTime=2580, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:29 PDT 2014, retrying after 20178 ms, replay 2249 ops.
14/07/10 14:10:08 INFO client.AsyncProcess: #15, table=usertable, attempt=14/35 failed 2279 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1205, waitTime=2580, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20076 ms, replay 2279 ops.
14/07/10 14:10:08 INFO client.AsyncProcess: #5, table=usertable, attempt=14/35 failed 2275 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1205, waitTime=2580, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20129 ms, replay 2275 ops.
14/07/10 14:10:08 INFO client.AsyncProcess: #7, table=usertable, attempt=14/35 failed 2292 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1205, waitTime=2580, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20175 ms, replay 2292 ops.
14/07/10 14:10:08 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 failed 2263 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1205, waitTime=2580, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:30 PDT 2014, retrying after 20018 ms, replay 2263 ops.
14/07/10 14:10:08 INFO client.AsyncProcess: #3, table=usertable, attempt=14/35 failed 2311 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1205, waitTime=2580, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20079 ms, replay 2311 ops.
14/07/10 14:10:08 INFO client.AsyncProcess: #8, table=usertable, attempt=12/35 failed 2247 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1205, waitTime=2580, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:29 PDT 2014, retrying after 20083 ms, replay 2247 ops.
2014-07-10 14:10:14:375 150 sec: 1202156 operations; 7983.2 current ops/sec; [INSERT AverageLatency(us)=1006.67] 
2014-07-10 14:10:24:376 160 sec: 1361820 operations; 15964.8 current ops/sec; [INSERT AverageLatency(us)=662.96] 
14/07/10 14:10:26 INFO client.AsyncProcess: #6, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014
14/07/10 14:10:26 INFO client.AsyncProcess: #20, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:51 PDT 2014
14/07/10 14:10:27 INFO client.AsyncProcess: #9, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014
14/07/10 14:10:27 INFO client.AsyncProcess: #7, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:53 PDT 2014
14/07/10 14:10:27 INFO client.AsyncProcess: #13, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:53 PDT 2014
14/07/10 14:10:30 INFO client.AsyncProcess: #8, table=usertable, attempt=13/35 failed 2263 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1462, waitTime=2279, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:30 PDT 2014, retrying after 20067 ms, replay 2263 ops.
14/07/10 14:10:30 INFO client.AsyncProcess: #8, table=usertable, attempt=13/35 failed 2242 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1462, waitTime=2279, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:30 PDT 2014, retrying after 20132 ms, replay 2242 ops.
14/07/10 14:10:30 INFO client.AsyncProcess: #2, table=usertable, attempt=13/35 failed 2249 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1462, waitTime=2279, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:29 PDT 2014, retrying after 20007 ms, replay 2249 ops.
14/07/10 14:10:30 INFO client.AsyncProcess: #3, table=usertable, attempt=15/35 failed 2311 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1462, waitTime=2279, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20066 ms, replay 2311 ops.
14/07/10 14:10:30 INFO client.AsyncProcess: #7, table=usertable, attempt=15/35 failed 2292 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1462, waitTime=2279, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20104 ms, replay 2292 ops.
14/07/10 14:10:30 INFO client.AsyncProcess: #8, table=usertable, attempt=13/35 failed 2247 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1462, waitTime=2279, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:29 PDT 2014, retrying after 20165 ms, replay 2247 ops.
14/07/10 14:10:30 INFO client.AsyncProcess: #16, table=usertable, attempt=15/35 failed 2225 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1462, waitTime=2279, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20149 ms, replay 2225 ops.
14/07/10 14:10:30 INFO client.AsyncProcess: #4, table=usertable, attempt=13/35 failed 2259 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1462, waitTime=2279, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:29 PDT 2014, retrying after 20022 ms, replay 2259 ops.
14/07/10 14:10:30 INFO client.AsyncProcess: #15, table=usertable, attempt=15/35 failed 2279 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1462, waitTime=2279, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20165 ms, replay 2279 ops.
14/07/10 14:10:30 INFO client.AsyncProcess: #8, table=usertable, attempt=13/35 failed 2243 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1462, waitTime=2279, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:30 PDT 2014, retrying after 20095 ms, replay 2243 ops.
14/07/10 14:10:30 INFO client.AsyncProcess: #8, table=usertable, attempt=13/35 failed 2266 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1462, waitTime=2279, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:31 PDT 2014, retrying after 20085 ms, replay 2266 ops.
14/07/10 14:10:30 INFO client.AsyncProcess: #5, table=usertable, attempt=15/35 failed 2275 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1462, waitTime=2279, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20184 ms, replay 2275 ops.
2014-07-10 14:10:34:376 170 sec: 1563748 operations; 20192.8 current ops/sec; [INSERT AverageLatency(us)=3425.97] 
2014-07-10 14:10:44:377 180 sec: 1568444 operations; 469.55 current ops/sec; [INSERT AverageLatency(us)=130] 
14/07/10 14:10:52 INFO client.AsyncProcess: #3, table=usertable, attempt=16/35 failed 2311 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1710, waitTime=2835, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20011 ms, replay 2311 ops.
14/07/10 14:10:52 INFO client.AsyncProcess: #8, table=usertable, attempt=14/35 failed 2243 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1710, waitTime=2835, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:30 PDT 2014, retrying after 20191 ms, replay 2243 ops.
14/07/10 14:10:52 INFO client.AsyncProcess: #8, table=usertable, attempt=14/35 failed 2266 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1710, waitTime=2835, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:31 PDT 2014, retrying after 20047 ms, replay 2266 ops.
14/07/10 14:10:52 INFO client.AsyncProcess: #8, table=usertable, attempt=14/35 failed 2263 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1710, waitTime=2835, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:30 PDT 2014, retrying after 20015 ms, replay 2263 ops.
14/07/10 14:10:52 INFO client.AsyncProcess: #2, table=usertable, attempt=14/35 failed 2249 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1710, waitTime=2835, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:29 PDT 2014, retrying after 20185 ms, replay 2249 ops.
14/07/10 14:10:52 INFO client.AsyncProcess: #4, table=usertable, attempt=14/35 failed 2259 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1710, waitTime=2835, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:29 PDT 2014, retrying after 20143 ms, replay 2259 ops.
14/07/10 14:10:52 INFO client.AsyncProcess: #8, table=usertable, attempt=14/35 failed 2242 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1724, waitTime=2418, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:30 PDT 2014, retrying after 20160 ms, replay 2242 ops.
14/07/10 14:10:52 INFO client.AsyncProcess: #5, table=usertable, attempt=16/35 failed 2275 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1724, waitTime=2418, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20196 ms, replay 2275 ops.
14/07/10 14:10:52 INFO client.AsyncProcess: #8, table=usertable, attempt=14/35 failed 2247 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1724, waitTime=2418, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:29 PDT 2014, retrying after 20103 ms, replay 2247 ops.
14/07/10 14:10:52 INFO client.AsyncProcess: #16, table=usertable, attempt=16/35 failed 2225 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1724, waitTime=2418, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20065 ms, replay 2225 ops.
14/07/10 14:10:52 INFO client.AsyncProcess: #7, table=usertable, attempt=16/35 failed 2292 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1724, waitTime=2418, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20000 ms, replay 2292 ops.
14/07/10 14:10:52 INFO client.AsyncProcess: #15, table=usertable, attempt=16/35 failed 2279 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1724, waitTime=2418, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20133 ms, replay 2279 ops.
2014-07-10 14:10:54:377 190 sec: 1681148 operations; 11270.4 current ops/sec; [INSERT AverageLatency(us)=1293.85] 
2014-07-10 14:11:04:378 200 sec: 1873684 operations; 19251.67 current ops/sec; [INSERT AverageLatency(us)=721.94] 
14/07/10 14:11:13 INFO client.AsyncProcess: #3, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014
2014-07-10 14:11:14:440 210 sec: 2169456 operations; 29394.95 current ops/sec; [INSERT AverageLatency(us)=1417.1] 
14/07/10 14:11:14 INFO client.AsyncProcess: #4, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:29 PDT 2014
14/07/10 14:11:14 INFO client.AsyncProcess: #8, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:30 PDT 2014
14/07/10 14:11:14 INFO client.AsyncProcess: #8, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:30 PDT 2014
14/07/10 14:11:14 INFO client.AsyncProcess: #8, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:31 PDT 2014
14/07/10 14:11:14 INFO client.AsyncProcess: #2, table=usertable, attempt=15/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:29 PDT 2014
14/07/10 14:11:14 INFO client.AsyncProcess: #7, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014
14/07/10 14:11:15 INFO client.AsyncProcess: #8, table=usertable, attempt=15/35 failed 2242 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1981, waitTime=2259, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:30 PDT 2014, retrying after 20029 ms, replay 2242 ops.
14/07/10 14:11:15 INFO client.AsyncProcess: #5, table=usertable, attempt=17/35 failed 2275 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1981, waitTime=2259, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20116 ms, replay 2275 ops.
14/07/10 14:11:15 INFO client.AsyncProcess: #15, table=usertable, attempt=17/35 failed 2279 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1981, waitTime=2259, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20144 ms, replay 2279 ops.
14/07/10 14:11:15 INFO client.AsyncProcess: #16, table=usertable, attempt=17/35 failed 2225 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1981, waitTime=2259, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20051 ms, replay 2225 ops.
14/07/10 14:11:15 INFO client.AsyncProcess: #8, table=usertable, attempt=15/35 failed 2247 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=1981, waitTime=2259, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:29 PDT 2014, retrying after 20103 ms, replay 2247 ops.
2014-07-10 14:11:24:440 220 sec: 2286932 operations; 11747.6 current ops/sec; [INSERT AverageLatency(us)=4769.93] 
2014-07-10 14:11:34:441 230 sec: 2286932 operations; 0 current ops/sec;  
14/07/10 14:11:37 INFO client.AsyncProcess: #16, table=usertable, attempt=18/35 failed 2225 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2267, waitTime=2557, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20034 ms, replay 2225 ops.
14/07/10 14:11:37 INFO client.AsyncProcess: #8, table=usertable, attempt=16/35 failed 2242 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2267, waitTime=2557, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:30 PDT 2014, retrying after 20148 ms, replay 2242 ops.
14/07/10 14:11:37 INFO client.AsyncProcess: #8, table=usertable, attempt=16/35 failed 2247 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2284, waitTime=2000, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:29 PDT 2014, retrying after 20048 ms, replay 2247 ops.
14/07/10 14:11:37 INFO client.AsyncProcess: #15, table=usertable, attempt=18/35 failed 2279 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2285, waitTime=2092, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20009 ms, replay 2279 ops.
14/07/10 14:11:37 INFO client.AsyncProcess: #5, table=usertable, attempt=18/35 failed 2275 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2285, waitTime=2092, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20005 ms, replay 2275 ops.
2014-07-10 14:11:44:442 240 sec: 2488860 operations; 20190.78 current ops/sec; [INSERT AverageLatency(us)=1386.99] 
2014-07-10 14:11:54:443 250 sec: 2695484 operations; 20660.33 current ops/sec; [INSERT AverageLatency(us)=511.38] 
14/07/10 14:11:58 INFO client.AsyncProcess: #8, table=usertable, attempt=17/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:30 PDT 2014
14/07/10 14:11:59 INFO client.AsyncProcess: #15, table=usertable, attempt=19/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014
14/07/10 14:11:59 INFO client.AsyncProcess: #8, table=usertable, attempt=17/35 failed 2247 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2619, waitTime=2753, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:29 PDT 2014, retrying after 20086 ms, replay 2247 ops.
14/07/10 14:11:59 INFO client.AsyncProcess: #5, table=usertable, attempt=19/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014
14/07/10 14:11:59 INFO client.AsyncProcess: #16, table=usertable, attempt=19/35 failed 2225 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2619, waitTime=2753, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014, retrying after 20158 ms, replay 2225 ops.
2014-07-10 14:12:04:443 260 sec: 2878628 operations; 18314.4 current ops/sec; [INSERT AverageLatency(us)=3721.75] 
14/07/10 14:12:08 INFO client.AsyncProcess: #3, table=usertable, attempt=10/35 failed 2227 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2761, waitTime=3037, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:11:16 PDT 2014, retrying after 10025 ms, replay 2227 ops.
14/07/10 14:12:08 INFO client.AsyncProcess: #18, table=usertable, attempt=10/35 failed 2238 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2761, waitTime=3037, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:11:15 PDT 2014, retrying after 10002 ms, replay 2238 ops.
2014-07-10 14:12:14:444 270 sec: 2878628 operations; 0 current ops/sec;  
14/07/10 14:12:20 INFO client.AsyncProcess: #3, table=usertable, attempt=11/35 failed 2227 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=2898, waitTime=2134, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:11:16 PDT 2014, retrying after 10079 ms, replay 2227 ops.
14/07/10 14:12:20 INFO client.AsyncProcess: #18, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:11:15 PDT 2014
14/07/10 14:12:21 INFO client.AsyncProcess: #16, table=usertable, attempt=20/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:07:46 PDT 2014
14/07/10 14:12:21 INFO client.AsyncProcess: #8, table=usertable, attempt=18/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:08:29 PDT 2014
2014-07-10 14:12:24:444 280 sec: 3038292 operations; 15966.4 current ops/sec; [INSERT AverageLatency(us)=4580.21] 
14/07/10 14:12:33 INFO client.AsyncProcess: #3, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:11:16 PDT 2014
2014-07-10 14:12:34:445 290 sec: 3320052 operations; 28173.18 current ops/sec; [INSERT AverageLatency(us)=907.05] 
2014-07-10 14:12:44:445 300 sec: 3324748 operations; 469.6 current ops/sec; [INSERT AverageLatency(us)=466.3] 
14/07/10 14:12:49 INFO client.AsyncProcess: #10, table=usertable, attempt=10/35 failed 2262 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3321, waitTime=2008, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:11:58 PDT 2014, retrying after 10032 ms, replay 2262 ops.
14/07/10 14:12:49 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2242 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3322, waitTime=2135, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:11:57 PDT 2014, retrying after 10057 ms, replay 2242 ops.
14/07/10 14:12:49 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2249 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3329, waitTime=2161, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:11:57 PDT 2014, retrying after 10094 ms, replay 2249 ops.
14/07/10 14:12:49 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2244 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3329, waitTime=2161, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:11:57 PDT 2014, retrying after 10002 ms, replay 2244 ops.
14/07/10 14:12:49 INFO client.AsyncProcess: #17, table=usertable, attempt=10/35 failed 2230 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3329, waitTime=2161, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:11:56 PDT 2014, retrying after 10027 ms, replay 2230 ops.
2014-07-10 14:12:54:446 310 sec: 3498500 operations; 17373.46 current ops/sec; [INSERT AverageLatency(us)=1850.17] 
14/07/10 14:13:01 INFO client.AsyncProcess: #10, table=usertable, attempt=11/35 failed 2262 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3500, waitTime=2240, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:11:58 PDT 2014, retrying after 10098 ms, replay 2262 ops.
14/07/10 14:13:01 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 failed 2242 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3500, waitTime=2240, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:11:57 PDT 2014, retrying after 10034 ms, replay 2242 ops.
14/07/10 14:13:02 INFO client.AsyncProcess: #17, table=usertable, attempt=11/35 failed 2230 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3504, waitTime=2833, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:11:56 PDT 2014, retrying after 10029 ms, replay 2230 ops.
14/07/10 14:13:02 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 2244 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3504, waitTime=2833, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:11:57 PDT 2014, retrying after 10083 ms, replay 2244 ops.
14/07/10 14:13:02 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 failed 2249 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=3504, waitTime=2833, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:11:57 PDT 2014, retrying after 10040 ms, replay 2249 ops.
2014-07-10 14:13:04:446 320 sec: 3498500 operations; 0 current ops/sec;  
14/07/10 14:13:12 INFO client.AsyncProcess: #1, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:11:57 PDT 2014
14/07/10 14:13:12 INFO client.AsyncProcess: #10, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:11:58 PDT 2014
14/07/10 14:13:13 INFO client.AsyncProcess: #17, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:11:56 PDT 2014
14/07/10 14:13:13 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:11:57 PDT 2014
14/07/10 14:13:13 INFO client.AsyncProcess: #14, table=usertable, attempt=12/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:11:57 PDT 2014
2014-07-10 14:13:14:497 330 sec: 3708897 operations; 20932.94 current ops/sec; [INSERT AverageLatency(us)=2535] 
2014-07-10 14:13:24:497 340 sec: 3850700 operations; 14180.3 current ops/sec; [INSERT AverageLatency(us)=201.59] 
2014-07-10 14:13:34:498 350 sec: 3850700 operations; 0 current ops/sec;  
2014-07-10 14:13:44:498 360 sec: 4085762 operations; 23506.2 current ops/sec; [INSERT AverageLatency(us)=2081.44] 
2014-07-10 14:13:54:498 370 sec: 4426924 operations; 34116.2 current ops/sec; [INSERT AverageLatency(us)=494.33] 
14/07/10 14:14:00 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2230 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4424, waitTime=3092, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:13:17 PDT 2014, retrying after 10017 ms, replay 2230 ops.
14/07/10 14:14:00 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2278 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4424, waitTime=3092, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:13:14 PDT 2014, retrying after 10076 ms, replay 2278 ops.
14/07/10 14:14:00 INFO client.AsyncProcess: #14, table=usertable, attempt=10/35 failed 2246 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4424, waitTime=3092, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:13:17 PDT 2014, retrying after 10059 ms, replay 2246 ops.
14/07/10 14:14:00 INFO client.AsyncProcess: #2, table=usertable, attempt=10/35 failed 2246 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4424, waitTime=3092, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:13:16 PDT 2014, retrying after 10059 ms, replay 2246 ops.
14/07/10 14:14:00 INFO client.AsyncProcess: #16, table=usertable, attempt=10/35 failed 2263 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4424, waitTime=3092, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:13:15 PDT 2014, retrying after 10013 ms, replay 2263 ops.
14/07/10 14:14:00 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2160 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4424, waitTime=3092, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:13:15 PDT 2014, retrying after 10004 ms, replay 2160 ops.
14/07/10 14:14:00 INFO client.AsyncProcess: #6, table=usertable, attempt=10/35 failed 2226 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4424, waitTime=3092, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:13:16 PDT 2014, retrying after 10064 ms, replay 2226 ops.
14/07/10 14:14:00 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2226 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4424, waitTime=3092, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:13:16 PDT 2014, retrying after 10043 ms, replay 2226 ops.
14/07/10 14:14:01 INFO client.AsyncProcess: #8, table=usertable, attempt=10/35 failed 2254 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4424, waitTime=3092, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:13:16 PDT 2014, retrying after 10058 ms, replay 2254 ops.
14/07/10 14:14:01 INFO client.AsyncProcess: #13, table=usertable, attempt=10/35 failed 2261 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4424, waitTime=3092, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:13:16 PDT 2014, retrying after 10087 ms, replay 2261 ops.
14/07/10 14:14:01 INFO client.AsyncProcess: #1, table=usertable, attempt=10/35 failed 2220 ops, last exception: java.io.IOException: Call to sceplus-vm48.almaden.ibm.com/9.1.143.58:60020 failed on local exception: org.apache.hadoop.hbase.ipc.RpcClient$CallTimeoutException: Call id=4424, waitTime=3092, rpcTimetout=2000 on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:13:16 PDT 2014, retrying after 10074 ms, replay 2220 ops.
2014-07-10 14:14:04:499 380 sec: 4724156 operations; 29720.23 current ops/sec; [INSERT AverageLatency(us)=671.91] 
14/07/10 14:14:11 INFO client.AsyncProcess: #16, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:13:15 PDT 2014
14/07/10 14:14:11 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:13:16 PDT 2014
14/07/10 14:14:11 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:13:17 PDT 2014
14/07/10 14:14:11 INFO client.AsyncProcess: #2, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:13:14 PDT 2014
14/07/10 14:14:11 INFO client.AsyncProcess: #14, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:13:17 PDT 2014
14/07/10 14:14:12 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:13:15 PDT 2014
14/07/10 14:14:12 INFO client.AsyncProcess: #8, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:13:16 PDT 2014
14/07/10 14:14:12 INFO client.AsyncProcess: #6, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:13:16 PDT 2014
14/07/10 14:14:12 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:13:16 PDT 2014
14/07/10 14:14:12 INFO client.AsyncProcess: #1, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:13:16 PDT 2014
14/07/10 14:14:12 INFO client.AsyncProcess: #13, table=usertable, attempt=11/35 SUCCEEDED on sceplus-vm48.almaden.ibm.com,60020,1405054513761, tracking started Thu Jul 10 14:13:16 PDT 2014
2014-07-10 14:14:14:499 390 sec: 5127553 operations; 40339.7 current ops/sec; [INSERT AverageLatency(us)=1285.55] 
2014-07-10 14:14:24:500 400 sec: 5550652 operations; 42305.67 current ops/sec; [INSERT AverageLatency(us)=461.11] 
2014-07-10 14:14:34:500 410 sec: 5813628 operations; 26297.6 current ops/sec; [INSERT AverageLatency(us)=610.17] 
2014-07-10 14:14:44:501 420 sec: 6141036 operations; 32737.53 current ops/sec; [INSERT AverageLatency(us)=736.18] 
2014-07-10 14:14:55:245 430 sec: 6368529 operations; 21173.96 current ops/sec; [INSERT AverageLatency(us)=833.07] 
2014-07-10 14:15:05:245 440 sec: 6755053 operations; 38652.4 current ops/sec; [INSERT AverageLatency(us)=553.81] 
2014-07-10 14:15:15:246 450 sec: 7053126 operations; 29804.32 current ops/sec; [UPDATE AverageLatency(us)=6666596] [INSERT AverageLatency(us)=567.48] [CLEANUP AverageLatency(us)=6666730] 
2014-07-10 14:15:25:246 460 sec: 7396766 operations; 34364 current ops/sec; [UPDATE AverageLatency(us)=5451384] [INSERT AverageLatency(us)=577.94] [CLEANUP AverageLatency(us)=5451790] 
2014-07-10 14:15:35:247 470 sec: 7694007 operations; 29721.13 current ops/sec;  [INSERT AverageLatency(us)=549.38]  
2014-07-10 14:15:45:247 480 sec: 7863063 operations; 16905.6 current ops/sec;  [INSERT AverageLatency(us)=563.66]  
2014-07-10 14:15:55:248 490 sec: 7863063 operations; 0 current ops/sec;    
2014-07-10 14:16:05:248 500 sec: 7863063 operations; 0 current ops/sec;    
2014-07-10 14:16:15:249 510 sec: 8003943 operations; 14086.59 current ops/sec; [UPDATE AverageLatency(us)=38036244] [INSERT AverageLatency(us)=4036.28] [CLEANUP AverageLatency(us)=38036261] 
2014-07-10 14:16:25:249 520 sec: 8055599 operations; 5165.6 current ops/sec;  [INSERT AverageLatency(us)=1427.57]  
2014-07-10 14:16:35:387 531 sec: 8487178 operations; 42570.43 current ops/sec; [UPDATE AverageLatency(us)=5709572] [INSERT AverageLatency(us)=690.93] [CLEANUP AverageLatency(us)=5709586] 
2014-07-10 14:16:45:388 541 sec: 8825005 operations; 33779.32 current ops/sec; [UPDATE AverageLatency(us)=2177922] [INSERT AverageLatency(us)=328.64] [CLEANUP AverageLatency(us)=2177933] 
2014-07-10 14:16:55:388 551 sec: 8825005 operations; 0 current ops/sec;    
14/07/10 14:16:59 INFO client.AsyncProcess: #11, waiting for some tasks to finish. Expected max=0, tasksSent=317, tasksDone=316, currentTasksDone=316, retries=103 hasError=false, tableName=usertable
2014-07-10 14:17:05:389 561 sec: 9167813 operations; 34277.37 current ops/sec; [UPDATE AverageLatency(us)=17853832.25] [INSERT AverageLatency(us)=705.98] [CLEANUP AverageLatency(us)=17853844.25] 
2014-07-10 14:17:15:390 571 sec: 9554877 operations; 38702.53 current ops/sec;  [INSERT AverageLatency(us)=293.31]  
2014-07-10 14:17:25:390 581 sec: 9894709 operations; 33983.2 current ops/sec; [UPDATE AverageLatency(us)=2071778] [INSERT AverageLatency(us)=209.17] [CLEANUP AverageLatency(us)=2071791.71] 
2014-07-10 14:17:35:401 591 sec: 9960207 operations; 6542.6 current ops/sec; [UPDATE AverageLatency(us)=629535] [INSERT AverageLatency(us)=93.22] [CLEANUP AverageLatency(us)=629547.67] 
2014-07-10 14:17:40:075 595 sec: 10000000 operations; 8513.69 current ops/sec; [UPDATE AverageLatency(us)=540395] [INSERT AverageLatency(us)=269.08] [CLEANUP AverageLatency(us)=540405] 
+ echo 'end time:'
end time:
++ date +%s
+ echo 1405027060
1405027060
+ echo 'sleeping for 10 sec ...'
sleeping for 10 sec ...
+ sleep 10
+ false
+ false
+ false
+ false
+ false
+ false
+ false
+ false
+ let counter=1+1
+ read line
+ set +x
